### ISSUE TITLE
netket.nn.Conv module 

### ISSUE THREAD

**Issue by janmen** [netket/netket#1001]
Good morning,
I try to solve 2D J1J2 model with the use of convolutional neural network but I have some issues with Conv module.
I use netket version 3.2.

I try to run following code:

```python
import numpy as np
import netket as nk
import matplotlib.pyplot as plt
import json
import jax
import jax.numpy as jnp
import sys
sys.path.insert(1, "../")
from J1J2model import *   

L  = 4     # length
N  = L**2  # number of spins
J1 = 1.0  # nearest-neighbours exchange interaction
J2 = .2   # next-nearest-neighbours exchange interaction

graph = nk.graph.Hypercube(length=L, n_dim=2, pbc=True)
hilbert = nk.hilbert.Spin(s=0.5, N=graph.n_nodes)
Ha = J1J2model_2D(hilbert, L, J1, J2)

class CNN(nk.nn.Module):
    @nk.nn.compact
    
    def __call__(self, x):
        x = nk.nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=1,kernel_init=nk.nn.initializers.normal(stddev=0.1), bias_init=nk.nn.initializers.normal(stddev=0.1))(x)
        x = nk.nn.activation.relu(x)
        x = jnp.sum(x, asix=-1)
        return x       

model = CNN()

sampler = nk.sampler.MetropolisExchange(hilbert, graph=graph, d_max=2)
vstate = nk.vqs.MCState(sampler, model, n_samples=3000)
optimizer = nk.optimizer.Sgd(learning_rate=0.01)
sr = nk.optimizer.SR(diag_shift=0.01)
gs = nk.driver.VMC(hamiltonian=Ha, optimizer=optimizer, variational_state=vstate, 
                   preconditioner=sr)

output_files = "test"
gs.run(out=output_files, n_iter=3000)

```
########################################################
When I run it, I get this error message:

```python
Traceback (most recent call last):
  File "conv.py", line 36, in <module>
    vstate = nk.vqs.MCState(sampler, model, n_samples=3000)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/mc_state.py", line 206, in __init__
    self.init(seed, dtype=sampler.dtype)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/mc_state.py", line 239, in init
    variables = jit_evaluate(self._init_fun, {"params": key}, dummy_input)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/mc_state.py", line 60, in jit_evaluate
    return fun(*args)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/mc_state.py", line 150, in <lambda>
    lambda model, *args, **kwargs: model.init(*args, **kwargs), model
  File "conv.py", line 28, in __call__
    x = nk.nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=1,kernel_init=nk.nn.initializers.normal(stddev=0.1), bias_init=nk.nn.initializers.normal(stddev=0.1))(x)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/nn/linear.py", line 289, in __call__
    precision=self.precision,
TypeError: 'int' object is not iterable

```
###########################################################

I am not able to find out what is wrong with the code.
Could you please help me?
Thank you.

**Comment by gcarleo** [comment]
there is  a typo 
```
x = jnp.sum(x, asix=-1)
```

should be axis=-1

**Comment by janmen** [comment]
Ah, yes, you are right, but the problem remains.

**Comment by gcarleo** [comment]
Ok, maybe then strides is supposed to be a tuple, can you check the docs?

**Comment by PhilipVinc** [comment]
There's a bunch of issues with your code, other than that typo (and another one, that might arise depending on python version: `@nn.compact should go right above `def __call__`, there should not be a newline in the middle)

1) try to print the shape of x: x has shape `(-1, 16)`. The first dimension is batches, and the other is the data. but you are trying to apply a 2D convolution with kernel (2,2). you should do a reshape first to reconstruct the 2d structure you want.

```python
    def __call__(self, x):
        print(x.shape)
        x = x.reshape((-1, L, L))
        print(x.shape)
        x = nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=1,kernel_init=nk.nn.initializers.normal(stddev=0.1), bias_init=nk.nn.initializers.normal(stddev=0.1))(x)
```

2) If you set the kernel size to a 2d kernel, the stride must also be a 2d stride, otherwise it makes no sense...

```python
        x = nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=[1,1],kernel_init=nk.nn.initializers.normal(stddev=0.1), bias_init=nk.nn.initializers.normal(stddev=0.1))(x)
```

so changing to

```python
class CNN(nk.nn.Module):
    @nk.nn.compact
    def __call__(self, x):
        x = x.reshape((-1, L, L))
        x = nk.nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=[1,1],kernel_init=nk.nn.initializers.normal(stddev=0.1), bias_init=nk.nn.initializers.normal(stddev=0.1))(x)
        x = nk.nn.activation.relu(x)
        x = jnp.sum(x, axis=-1)
        return x       
```

fixes your problem.

BTW, in general when your model fails at initialisation, don't open an issue here on NetKet's repo, but open it at flax. 
That's the library that we use for making the networks and it would be good for them to see issues that arise. 

PS: when you paste code, use triple backticks so that it is actually readable. The GitHub editor has a button to do it for you.

**Comment by PhilipVinc** [comment]
(by the way @gcarleo , in recent versions of flax, flax is smarter and does not throw an error in this case and simply converts the integer stride to a list. But since we have a vendored and modified version of flax 0.3, we don't benefit from all improvements and bug fixes there have been in flax since 0.3, like that one. One more reason to stop venturing it...)

**Comment by PhilipVinc** [comment]
@janmen Please also pay attention to the deprecation warnings that your code throws... `nk.nn.initializers.normal` is deprecated and will be removed in the future. The warning tells you how to upgrade your code.

**Comment by janmen** [comment]
Ok, thank you, it seems there is still something wrong:

`Traceback` (most recent call last):
  File "conv.py", line 45, in <module>
    gs.run(out=output_files, n_iter=3000)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 251, in run
    for step in self.iter(n_iter, step_size):
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/driver/abstract_variational_driver.py", line 167, in iter
    dp = self._forward_and_backward()
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/driver/vmc.py", line 132, in _forward_and_backward
    self._loss_stats, self._loss_grad = self.state.expect_and_grad(self._ham)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/base.py", line 215, in expect_and_grad
    return expect_and_grad(self, Ô, use_covariance=use_covariance, mutable=mutable)
  File "plum/function.py", line 537, in plum.function.Function.__call__
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/base.py", line 368, in expect_and_grad
    return expect_and_grad(vstate, operator, use_covariance, mutable)
  File "plum/function.py", line 537, in plum.function.Function.__call__
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/mc_expect_grad.py", line 117, in expect_and_grad
    σ = vstate.samples
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/mc_state.py", line 429, in samples
    self.sample()
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/vqs/mc_state.py", line 406, in sample
    chain_length=n_discard_per_chain,
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/sampler/base.py", line 290, in sample
    sampler, machine, parameters, state=state, chain_length=chain_length
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/sampler/base.py", line 452, in sample
    return sampler._sample_chain(machine, parameters, state, chain_length)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/sampler/base.py", line 319, in _sample_chain
    return _sample_chain(sampler, machine, parameters, state, chain_length)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/sampler/base.py", line 486, in _sample_chain
    length=chain_length,
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/sampler/base.py", line 480, in <lambda>
    _sample_next = lambda state, _: sampler.sample_next(machine, parameters, state)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/sampler/base.py", line 263, in sample_next
    return sampler._sample_next(wrap_afun(machine), parameters, state)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/netket/sampler/metropolis.py", line 325, in _sample_next
    do_accept = uniform < jnp.exp(proposal_log_prob - s.log_prob)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 6585, in deferring_binary_op
    return binary_op(self, other)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 755, in fn
    x1, x2 =  _promote_args(numpy_fn.__name__, x1, x2)
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 581, in _promote_args
    return _promote_shapes(fun_name, *_promote_dtypes(*args))
  File "/storage/praha1/home/jana_mensikova/.local/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 500, in _promote_shapes
    result_rank = len(lax.broadcast_shapes(*shapes))
ValueError: Incompatible shapes for broadcasting: ((1, 16), (16, 4))

**Comment by PhilipVinc** [comment]
ah yes, sorry. 

You should be able to figure it out yourself if I tell you that the NN should take an input that is shape `(-1, Nspins)`  and return an input that is shape `(-1)` (with -1 I mean that is an arbitrary number.

Add a print statement `print(x.shape)` after every operation in the neural network and try to figure out what you have to do to do. Most likely, since you reshaped the input to a 2D object, you must undo that same operation at some point..

**Comment by janmen** [comment]
Ok, thanks, I'll try to figure it out =)

**Comment by PhilipVinc** [comment]
Once you solve it post here the solution, please and close the issue.
It might help people in the future.

(If you don't manage just ping me again tomorrow).

**Comment by gcarleo** [comment]
Yes I think we should have a 2d convnet example/tutorial around, since this
might pop up quite frequently for new users and indeed the error messages
from Flax unfortunately are not very transparent... (it's true that the 2d
convnet example is on their website, but the need for reshaping of the
input/output is netket specific, so it would be helpful to clarify this)

So maybe after you fix this you could propose a PR with a small tutorial
containing a code snippet that works?

**Comment by janmen** [comment]
Ok, I tried this modification:

`class CNN(nk.nn.Module):
    @nk.nn.compact
    def __call__(self, x):
        x = x.reshape((-1, L, L))
        x = nk.nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=[1,1],kernel_init=nk.nn.initializers.normal(stddev=0.1), bias_init=nk.nn.initializers.normal(stddev=0.1))(x)
        x = nk.nn.activation.relu(x)
        x = x.reshape(-1,L)
        x = jnp.sum(x, axis=-1)
        return x       
`
It worked, however energy of the system converged very quickly to not a number. So, is this solution really right, or is it just a coincidence?

**Comment by janmen** [comment]
Sorry for the formating, here it should be better:
```
`class` CNN(nk.nn.Module):
    `@nk.nn.compact`
    def __call__(self, x):
        x = x.reshape((-1, L, L))
        x = nk.nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=[1,1], dtype=np.complex128,kernel_init=jax.nn.initializers.normal(stddev=0.1), bias_init=jax.nn.initializers.normal(stddev=0.1))(x)
        x = nk.nn.activation.relu(x)
        x = x.reshape(-1,L)
        x = jnp.sum(x, axis=-1)
        return x       
```

**Comment by PhilipVinc** [comment]
Yep exactly.
Well, relu is not really a good initialization with complex numbers because it only acts on the real part. 
Also the initializer has possibly a too large variance. 

(By the way, you can edit your posts)

**Comment by janmen** [comment]
Ok, thanks a lot, I will try to use some other activation functions and variances.

Yes, just now I found out how I can edit my posts =D

**Comment by gcarleo** [comment]
Isn't this wrong?

x = x.reshape(-1,L)

**Comment by janmen** [comment]
Well, I don't know, the program runs, but maybe there's a better way how to do the reshaping.

**Comment by PhilipVinc** [comment]
Not better. You go from `(M, L**2) -> (M, L, L)` then apply the convolution which in this case (luckily for you) gives you back `(M, L, L)`. Now you want to sum over all those `L**2` elements, but your reshape does (M,L,L)->(M*L, L)` and after the sum you get `(M*L)` . This is quite wrong..

**Comment by janmen** [comment]
Well, I tried also x=x.reshape(-1,L**2), but it didn't work out.

**Comment by janmen** [comment]
Also, I'm not sure, if the convolution gives me back (M, L, L).
When I print the shapes, I get this:

When initilizing:(1, 16)
After the first reshaping: (1, 4, 4)
After applying the convolution: (1, 4, 1)
After the second reshaping: (1, 4)
After summing: (1,)

**Comment by PhilipVinc** [comment]
> inputs should be NHWC for a 2d convolution and 

NHWC is the dimensions. It means Number of samples, Height of image, Width of image, color channels.

From the documentation
https://flax.readthedocs.io/en/latest/_autosummary/flax.linen.Conv.html#flax.linen.Conv

This is common for convolutions because they were first written by people working on images. The last dimension is channels. Since we only have 1 channel (the spins) You need to reshape not to `(-1,L,L)` but to `(-1,L,L,1)`.

**Comment by janmen** [comment]
Ok, and the second reshaping is x=x.reshape(-1,L**2), or is it wrong?

**Comment by PhilipVinc** [comment]
yes, but that will only work for the particular kernel and padding you used.
You'd be best doing something like

```python
class CNN(nk.nn.Module):
    @nk.nn.compact
    def __call__(self, x):
        # extra axis 1 because Conv assume NHWC ordering
        x = x.reshape((-1, L, L,1))
        M = x.shape[0]
        x = nk.nn.Conv(features=1,kernel_size=[2,2],use_bias=True,strides=[1,1], dtype=np.complex128,kernel_init=jax.nn.initializers.normal(stddev=0.1), bias_init=jax.nn.initializers.normal(stddev=0.1))(x)
        x = nk.nn.activation.relu(x)
        x = x.reshape(M, -1)
        x = jnp.sum(x, axis=-1)
        return x       
```

**Comment by janmen** [comment]
Ok, thank you very much!
