### ISSUE TITLE
Add python unit tests for ground-state methods 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#102]

**Comment by jamesETsmith** [comment]
Is this issue waiting on something else? If not I can get started on it today.

**Comment by jamesETsmith** [comment]
After some more looking, I will wait to work on this until after #99

**Comment by gcarleo** [comment]
Hi @jamesETsmith , yes, better wait for that one. However there is plenty of other tests that are waiting to be improved/ translated from c++! For example `Hilbert` doesn't test custom Hilberts, I think, and `Hamiltonian` doesn't test custom hamiltonians / graph hamiltonians yet... 
Also, all the `Optimizers` don't have any python test (there it might be necessary to do some small work on the bindings too actually). Let me know if you have time to tackle some of those during thanksgiving :)

**Comment by jamesETsmith** [comment]
@gcarleo I'm pretty sure the Hilbert tests are all set, but you're right, I forgot to circle back and finish up the Hamiltonian tests! So I'll get started on that today. Want me to create an issue and then a PR or just a PR?

**Comment by gcarleo** [comment]
Yeah do an issue and then a pr!

**Comment by gcarleo** [comment]
@femtobit @jamesETsmith what happened with this one? Do we have some tests on the vmc now?

**Comment by jamesETsmith** [comment]
@gcarleo there are tests for the Vmc and ED ground state methods, but not for imaginary time. If you'd like I can open a PR and add those tests.

**Comment by gcarleo** [comment]
If think the tests we have now are good enough! Thanks for checking out @jamesETsmith
