### ISSUE TITLE
Passing optimizer state to logger

### ISSUE THREAD

**Issue by wdphy16** [netket/netket#1055]
That would be helpful, e.g., when we accumulate a running average of the model parameters in the optimizer state (which is a common trick for optimization) and dump it to the file in the logger. If we agree on this, I'll make a PR.

**Comment by PhilipVinc** [comment]
I'd like to collect some more opinions on this before we implement it. 

For starters, this would add a lot of data to what is logged when using most optimisers.

Secondly you can already implement this very easily with a callback, just like a metropolis acceptance ratio.

```python
def optimizer_cb(step, log_data, driver):
    log_data['optimizer_state'] = _optimizer_state
    return True
```
I'd rather add a page to the documentation saying how to do this (it's a 3 liner), together with how to log acceptance than to dump lots of data in the log files...

**Comment by gcarleo** [comment]
yes, I tend to agree, this might log too much stuff for the average simulation that doesn't need it... but indeed it is a good idea to add docs explaining how to log custom things!

**Comment by wdphy16** [comment]
Ok, now I see how to do that using a callback in `VMC.run`.

**Comment by PhilipVinc** [comment]
Still, if you wanted to write a documentation page about using callbacks to do this it would be great.
