### ISSUE TITLE
`nk.dynamics.TDVP.run(T, tstops=...)` progress bar does not get updated if T > tstops[-1]

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#1070]
The progress bar is printed at every tstop.
But if there are no tstops it is never printed, which is annoying, even if not super-important.

Noticed by running `te.run(T=1.0, tstops=np.linspace(0.0, 0.5, 51, endpoint=True))` in the example

**Comment by femtobit** [comment]
Indeed, if no `tstops` are specified, the solver never yields and thus the driver code performing the update is not run.

If it is just about the progress bar, we could a callback to the solver that is called on every internal step (and having the driver pass a callback that just updates the progress bar). That's maybe over-engineering for this particular case, but could be useful for debugging or other applications of the ODE solver too.
