### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by twesterhout** [netket/netket#11]
I've had a very brief look at the code and found found it shocking that `netket::Machine` and `netket::Hamiltonian` (and perhaps more classes) leak memory. They not only do raw memory allocation with `new` (which is already a bad idea in `C++11`: consider using `std::unique_ptr` instead), but are also missing destructors.

**Comment by gcarleo** [comment]
OK thanks, I fixed this in the latest commit 7402132b9f9e35d8b2dc8d53b9566016a72ddc27

**Comment by twesterhout** [comment]
I have a more general question: how would you feel about receiving a whole lot of similar bug reports? Would you be willing to accept PRs improving code quality or is the state where the code "runs" good enough?
The reason I'm asking this is because I'm trying to decide whether it makes sense to abandon my own similar code in favour of this project.

**Comment by gcarleo** [comment]
As long as the bug reports concern potential performance/stability issues in the code, it is perfectly OK and well accepted. Reports concerning coding style issues that do not affect performance, and do not improve the code usability, might not be considered.
Forks and pull requests is of course a good way of actively proposing changes to the code.

**Comment by twesterhout** [comment]
I see. Thanks for the honest answer!
