### ISSUE TITLE
Upgrade `flakehell` in the pre-commit hook

### ISSUE THREAD

**Issue by wdphy16** [netket/netket#1111]
It seems that `flakehell` is not actively maintained, and it is incompatible with `flake8 4.x` released in last October (see flakehell/flakehell#22). That issue is not resolved after a few months. If a new developer of NetKet runs `pre-commit install-hooks`, it will just fail.

We may use [this fix](https://github.com/flakehell/flakehell/pull/23#issuecomment-985879201), or change it to [flakeheaven](https://github.com/flakeheaven/flakeheaven) which seems more actively maintained.

**Comment by gcarleo** [comment]
Do we even really need this stuff?

**Comment by PhilipVinc** [comment]
I like those things. They can be disabled after all and they catches a few bugs from time to time.


@wdphy16 cant we switch to bare flake8? Even flakeven looks very young and small

**Comment by wdphy16** [comment]
Ok, let's try bare `flake8`. A downside is that `flake8` does not support `pyproject.toml` yet, so I created a `.flake8` file for the configuration.

And I have a few suggestions when checking the dev dependencies:

`black 22.0` introduces a breaking change that there are no longer spaces around simple power operators (before: `x ** 2`, after: `x**2`). Shall we upgrade it? I think the new version looks better (especially for numerical code like us). But before we decide, we should pin the version number.

`flaky` and `networkx` are not in our codebase now and we can safely remove them.

Shall we also use `isort` in pre-commit? It's often used in complement to `black`.

**Comment by PhilipVinc** [comment]
Upgradint black is on my to-do list. Finalyl they declared a stable release. 
You have to set the same version in the setup.py, and .pre-commit-config.

I'd really appreciate if you did it.
Please do the black and flake8 in different PRs.

I'll merge black first.

Also please store the hash of the mass-reformat commit in a file named .git-blame-ignore-commit as explained [here](https://akrabat.com/ignoring-revisions-with-git-blame/)

**Comment by PhilipVinc** [comment]
Do remove flaky

**Comment by PhilipVinc** [comment]
https://github.com/csachs/pyproject-flake8

**Comment by wdphy16** [comment]
Hmmm, `pre-commit` requires to specify a version for `pflake8`, and they only have very alpha versions. But as it has not changed for months we can assume it's stable...
