### ISSUE TITLE
Defining constraints on custom Hilbert space

### ISSUE THREAD

**Issue by whatisspin** [netket/netket#1121]
Hello,
I have been trying to solve the Heisenberg Hamiltonian using a custom Hilbert space. I read the docs but still do not understand how to sample the space. To be concrete, I did this:
```
import netket as nk
import jax

def total_mag(states):
    return states.sum(axis=-1)==0

hi= nk.hilbert.CustomHilbert(local_states=[-1,1], N=4, constraint_fn=total_mag)
print(hi.random_state(jax.random.PRNGKey(0)))
```
And as in the docs, I got the error:
```
Traceback (most recent call last):
  File ".../customH.py", line 8, in <module>
    print(hi.random_state(jax.random.PRNGKey(0)))
  File ".../netket/hilbert/abstract_hilbert.py", line 84, in random_state
    return random.random_state(self, key, size, dtype=dtype)
  File "plum/function.py", line 537, in plum.function.Function.__call__
  File ".../netket/hilbert/random/base.py", line 90, in random_state
    return random_state(hilb, key, 1, dtype=dtype)[0]
  File "plum/function.py", line 537, in plum.function.Function.__call__
  File ".../netket/hilbert/random/custom.py", line 25, in random_state
    raise NotImplementedError()
NotImplementedError
```
I tried some things after this to define the function `random_state` myself using `@netket.utils.dispatch.dispatch`, but nothing worked. What would be the correct way to implement this? (I could not find it in the docs.)

Thank you.

**Comment by PhilipVinc** [comment]
It's briefly mentioned in the [documentation of hilbert spaces](https://netket.readthedocs.io/en/latest/docs/hilbert.html#defining-custom-constraints) but we're missing a proper page of documentation on this.

Essentially, you need to _instruct_ netket how to sample uniformly the constrained space, which is used to initialise the markov chain. How to do it is unfortunately only documented in the source code (it would be great to add it to the proper documentation). See [here](https://github.com/netket/netket/blob/master/netket/hilbert/random/__init__.py)

In short, you must define a dispatch rule for `nk.hilbert.random.random_state`
```python
@nk.hilbert.random.random_state.dispatch
def random_state(hilb : nk.hilbert.CustomHilbert, key, size : int, *, dtype):
    # do some jnp magic
    # this will be executed inside of jax.jit, so you must use jax.numpy
    return batch_of_size_states
```

if you need inspiration on how to implement this function, you can have a look [here](https://github.com/netket/netket/blob/2c0bbf5dfcff39a06a5079231fcd803dcb89c65c/netket/hilbert/random/spin.py#L35) where it's implemented already (spins with constrained magnetization)

**Comment by whatisspin** [comment]
Thank you for your answer, and the code link. I am able to do it now.

**Comment by PhilipVinc** [comment]
By the way, in general I'd advise you against using CustomHilbert and just define your own.
```
class MyHilbert(HomogeneousHilbert):

```

in this case you'd have gotten a much more informative error, and I plan to remove CustomHilbert or change it a bit.
Of course, all this when i'll have time to document everything as well...

**Comment by whatisspin** [comment]
Okay, I understand. Thanks for the tip. Had no problems in implementing it this way.
