### ISSUE TITLE
Fix links to `Documentation` in README

### ISSUE THREAD

**Issue by erinaldi** [netket/netket#1125]
Hello,

I noticed that the links at the beginning of the README file are outdated.

- [ ] `Citing` seems to have moved to `cite` at https://www.netket.org/cite/
- [ ] `Documentation` is now at https://netket.readthedocs.io/en/latest/index.html
- [ ] `Tutorials` have also been moved to the readthedocs page https://netket.readthedocs.io/en/latest/tutorials/

**Comment by PhilipVinc** [comment]
Yeah, I forgot to update those.
Can you open a quick PR?

**Comment by PhilipVinc** [comment]
thanks a lot!

**Comment by erinaldi** [comment]
@PhilipVinc the changes are minor. The PR is going through the CI checks right now.
