### ISSUE TITLE
Compiling with USE_LAPACK in v2.0 is broken 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#113]
Reported by @fabienalet

**Comment by fabienalet** [comment]
I think it's related to [this](https://github.com/libigl/libigl/issues/651).
The simplest workaround I found seems to 
````
#undef I
````
before
````
#include "Dynamics/pydynamics.hpp"
````
in [pynetket.cc](https://github.com/netket/netket/blob/v2.0/NetKet/pynetket.cc)
It compiles but it's a bit ugly and I'm not sure if it won't break other things later.

**Comment by gcarleo** [comment]
Oh interesting, I thought we had already solved this before! I personally changed all the I to I_ in a lot of parts in the code. Maybe there is some leftover. In what part of the code do we still have `I` ? Maybe it's easier just to rename those and not use the `#undef`

**Comment by fabienalet** [comment]
It is in pybind11 actually. More precisely [here](https://github.com/pybind/pybind11/blob/a23996fce38ff6ccfbcdc09f1e63f2c4be5ea2ef/include/pybind11/detail/common.h#L473) and perhaps elsewhere

**Comment by gcarleo** [comment]
Oh I see, then we should open an issue on pybind11

**Comment by twesterhout** [comment]
@fabienalet and @gcarleo pybind11 is not the one to blame here! It's basically standard practice in template-heavy C++ code to use `Is` or `I` for integral parameter/parameter packs. Most style guides mandate that template parameters must be in CamelCase and normal code's `i` is thus transformed into `I`.
Not to sound harsh, but anyone who includes `<complex.h>` in C++ code is most likely doing something very wrong. Including `<complex.h>` is really just asking for trouble :)
So if anything, I'd submit a bug report to Eigen which includes it in one of the low-level cblas-related parts and doesn't undefine the macros afterwards.

**Comment by gcarleo** [comment]
@twesterhout I wonder wether with separate compilation we can also fix this old issue ?

**Comment by twesterhout** [comment]
I can give it a try.
