### ISSUE TITLE
[RFC] [bug] `logsumexp` in GCNNs

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#1133]
At the moment, GCNNs fail if they only use real parameters but try to return a negative WF amplitude whose log should be complex. This arises if you use a nontrivial irrep, some entries of which are negative. The problem is `logsumexp`, which returns NaN if it has to take the log of a negative `float`. I am happy to fix this, but I would appreciate some input on which of the following strategies is preferable:
* Promote the outputs of the last layer into complex numbers – wastes memory
* Promote the characters into complex numbers – the code of `logsumexp` suggests that would waste the same amount of memory in type promotions
* Use the `return_sign` option of `logsumexp` and convert the sign part into 0 or iπ – this only works for real networks _and irreps_, so a lot of type checking and conditionals are needed

@chrisrothUT @PhilipVinc @femtobit?

**Comment by PhilipVinc** [comment]
I see.
I think that numerically using `return_sign` and promoting to complex numbers will be very similar.
Memory wise I think the increase of computational cost in promoting to complex numbers will be negligible if compared to eg the memory occupied by the equivariant layers so it's not very important?

I think the most elegant solution would be to use `return_sign`, maybe hidden behind a flag of the gcnn, because if `return_sign=True` then the output of the GCNN will be complex.

**Comment by PhilipVinc** [comment]
>Truthfully as long as we don't do this I am satisfied

You still need to output a complex number from the GCNN, because it outputs the log-amplitude.

**Comment by chrisrothUT** [comment]
> You still need to output a complex number from the GCNN, because it outputs the log-amplitude.

Of course, but the memory bottleneck occurs before the `logsumexp` where you sum over a bunch of terms. After the `logsumexp` it's fine if we use complex numbers.

**Comment by attila-i-szabo** [comment]
It sounds like the best would be to define a `nk.jax.logsumexp` (or some other name like `safe_logsumexp`) that always returns a complex number. Internally, have two cases, depending on what the return dtype of jax `logsumexp` is. This should avoid any upconversion of the last GCNN features (@chrisrothUT is right, that would be a bit of a concern for memory, although there are more memory-intensive steps)

To preserve old behaviour, we could have a switch between the jax `logsumexp` and this new version, but that would only really be helpful if your output WF is guaranteed positive, I'm not sure how important that case is.

**Comment by PhilipVinc** [comment]
>It sounds like the best would be to define a nk.jax.logsumexp (or some other name like safe_logsumexp) that always returns a complex number. Internally, have two cases, depending on what the return dtype of jax logsumexp is. This should avoid any upconversion of the last GCNN features (@chrisrothUT is right, that would be a bit of a concern for memory, although there are more memory-intensive steps)

The reason for defining an helper function in `nk.jax.` would be if we expect to use this elsewhere, and I don't really see (for now) an use anywhere else.
You can have something like this inside of the GCNN, or in the huge `equivariant.py` file, but I really don't see a case for having a more general method.

> To preserve old behaviour, we could have a switch between the jax logsumexp and this new version, but that would only really be helpful if your output WF is guaranteed positive, I'm not sure how important that case is.

We can't keep breaking old behaviour. You should add a flag. Besides, there are people who use those things.

>@chrisrothUT is right, that would be a bit of a concern for memory, although there are more memory-intensive steps)

At worst we double the memory requirement for a single layer. 
When back propagating, I really don't see how this can be the bottleneck...

**Comment by attila-i-szabo** [comment]
> The reason for defining an helper function in `nk.jax.` would be if we expect to use this elsewhere, and I don't really see (for now) an use anywhere else.

I noticed the issue when building a different model which kept NaNing. For NQS purposes, the default behaviour of logsumexp is annoying, so it would make sense to have it in a discoverable place.

> At worst we double the memory requirement for a single layer. When back propagating, I really don't see how this can be the bottleneck...

That doesn't mean we should waste memory...

**Comment by attila-i-szabo** [comment]
> > To preserve old behaviour, we could have a switch between the jax logsumexp and this new version, but that would only really be helpful if your output WF is guaranteed positive, I'm not sure how important that case is.
> 
> We can't keep breaking old behaviour. You should add a flag. Besides, there are people who use those things.

Should the flag default to the new (no NaNs) or old (no breaking change™) behaviour

**Comment by PhilipVinc** [comment]
>I noticed the issue when building a different model which kept NaNing. For NQS purposes, the default behaviour of logsumexp is annoying, so it would make sense to have the alternative behaviour in a discoverable place.

You kinda have a point.
If we're to add it there I'd rather change it's name to something more like `logsumexpcomplex` or alike.

**Comment by PhilipVinc** [comment]
>Should the flag default to the new (no NaNs) or old (no breaking change™) behaviour. BTW, the only thing that breaks is the dtype returned, the numerical value remains identical by construction (at least for the return_sign option)

Wait, if we just change the output type like this I think that the optimisation should (should...) be resistant, as in, the result should not change (provided there were no nans). so maybe we don't need to worry too much
