### ISSUE TITLE
Hangs in TDVP

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#1183]
Running TDVP on  GPUs sometimes hangs during the first iteration with no calculations being done.
I saw this only happening on older CUDA versions (11.1) on izar cluster. Locally can't reproduce on CUDA 11.3/11.4.
Only happens on GPU. Only happens with some models.

The hang can be avoided by pre-compiling the jax functions that will be executed in the callback of TDVP. 
For example, I added this line
```python
nkx.driver._tdvp.odefun(vs, te, 0.0, vs.parameters)
```
before `TDVP.run`.

Surely it's caused by us compiling code in the callback. Then, what exactly is causing it... who knows.

Should be investigated

**Comment by PhilipVinc** [comment]
From private communications: re-entrant compilation in callbacks will not be officially supported in the nearby future (it 's hard to handle from a memory-management point of view, apparently). 

@femtobit the only viable path forward I see is to disable `@jit`ting the ODE solvers.
Maybe we could add some jit-s decorators to some sub-computations to attenuate the effect, but for large systems I expect the effect to be minimal.

**Comment by femtobit** [comment]
Yes, agreed. It could make sense to try and jit some sub-computations, but I also expect it to not matter a lot in most t-VMC applications.

We should probably make `jit`ing the solver optional, it may still be useful is some cases (and it does usually work on the CPU).
