### ISSUE TITLE
Time cost of tutorials

### ISSUE THREAD

**Issue by liwt31** [netket/netket#12]
I tried to run the first tutorial example [transverse field Ising model](http://www.netket.org/tutorials/ising/) and found it took the computer (Xeon E5-2630 with enough memory) 10 min to finish the calculation in serial mode. 
If the tutorial example really needs 10 min time, I think it'll be nice to point it out in the tutorial because a minimal working example usually does not take so much time. If something of my compilation or computer went wrong, it'll also be helpful for me to know that the example should take less than 1 min.
So, my suggestion is to add some comment on running time in the tutorial. I think it's beneficial for helping new users know about the program.

**Comment by gcarleo** [comment]
You can always run the tutorial in parallel. It seems your CPU has up to 6 cores and 12 threads, just use mpirun -n 12 netket ... I suspect that the running time will be around 1 minute. 

But anyway, it is a good suggestion, I will try to add in the tutorial that while the code is running it is possible to run the plot_ising.py (and similar for the other tutorials), so to visualise the progress of the simulation in real time and/or quit the simulation when some accuracy is reached.
