### ISSUE TITLE
MetropolisGaussian not sampling correctly

### ISSUE THREAD

**Issue by druidowm** [netket/netket#1213]
Hello! 

I have taken the Harmonic Oscillator demo (https://github.com/netket/netket/blob/master/Examples/Continuous/HO.py) and it actually does not work. The energy drops to a very large negative number before eventually becoming nan, and the $\hat{R}$ stays at approximately 1.4, which seems to suggest that the sampler is causing the issue. Here are a few snapshots of the printout:

2% | 2/100 [00:03<02:28,  1.52s/it, Energy=-791595740.7 ± 46731030.5 [σ²=1118100077599132544.0, R̂=1.4136]]]

10% | 10/100 [00:15<02:18,  1.54s/it, Energy=-8.345e+164 ± nan [σ²=inf].

I suspect that there is a bug with nk.sampler.MetropolisGaussian that is producing this issue. Of course, I may be doing something wrong. I am using netket version 3.4.1 and jax version 0.3.7.

Thank you in advance for looking into this!

**Comment by gcarleo** [comment]
maybe can you try to update to 3.4.2 ? support for continous systems is somehow still experimental and in my recollection a bug was recently fixed

**Comment by gpescia** [comment]
Hi @druidowm 

the bug should be fixed in the newest github version on the master branch (3.4.3). Can you try that?

**Comment by gcarleo** [comment]
maybe we should release this fix in a stable version soon

**Comment by PhilipVinc** [comment]
I will do that tomorrow morning

**Comment by druidowm** [comment]
I tested the newest github version, and the demo appears to work now! Thank you for your help with this! 😀

**Comment by PhilipVinc** [comment]
Hi @druidowm, 
I just tagged a new release (v3.4.3) which contains the fixes that were not published on PyPi.
You can just install the official version now.

And thanks for raising the issue!
