### ISSUE TITLE
Issue on page /tutorials/quickstart.html

### ISSUE THREAD

**Issue by nikosavola** [netket/netket#1215]
This tutorial doesn't seem to currently contain anything. Should it be removed?

https://netket.readthedocs.io/en/latest/tutorials/quickstart.html

**Comment by PhilipVinc** [comment]
Yes I actually have a PR to remove that page, but how did you end up on it? I don't find any link to it.

**Comment by nikosavola** [comment]
> Yes I actually have a PR to remove that page, but how did you end up on it? I don't find any link to it.

I just found it in the tutorials folder in the repo and it seems to exist in the docs with the corresponding path as well.

**Comment by PhilipVinc** [comment]
ah thanks a lot for reporting that. 
I'll delete it.
