### ISSUE TITLE
NaN energy during optimisation

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#1222]
Sometimes an experiment might produce nan energies during optimisation. However, the optimisation continues. I think it would be best to stop the optimisation because nothing is being optimised.

**Comment by femtobit** [comment]
This can be implemented as a callback, right? Something like:
```python3
def callback(_, _, driver):
    return np.isfinite(driver.loss_stats.mean)  # or `not np.isnan(...)` for a more fine-grained criterion
```

**Comment by femtobit** [comment]
I agree. Technically, the energy could be `NaN` but as long as that is a fluke and the gradient is fine, the optimization could recover. Though this seems unlikely to happen in practice (I don't recall seeing this, at least).

In any case, I'd suggest adding something like a `StopOnInvalidLoss` callback and add it to the list of callbacks by default in our drivers, unless it is disabled by some flag, to implement this functionality.

**Comment by VolodyaCO** [comment]
A couple of days ago I saw the energy going to `NaN` and then recover. Not reproducible, though. I'll just create the stop on invalid loss.
