### ISSUE TITLE
Hamiltonian(s) giving wrong results with different hilbert spaces

### ISSUE THREAD

**Issue by jwnys** [netket/netket#1317]
The `nk.operator._hamiltonians.py` Hamiltonians take a Hilbert space as input. However, e.g. `nk.operator.Ising` is implemented specifically with `nk.hilbert.Spin` in mind. If you call it with `nk.hilbert.Qubit`, the results are incorrect, and no error or warning is thrown. Pauli matrices in the corresponding Hilbert spaces should be used, as I've done in `nk.operator.PauliStrings`.

![image](https://user-images.githubusercontent.com/17109783/188220985-0bd1cf76-7dc4-413f-a3a4-77bdf0713d13.png)

**Comment by PhilipVinc** [comment]
For now we should throw an error if it's not Spin.
Then, we should address this and support all spaces.

To support other spaces we could use the local_values to decide what to do.

**Comment by PhilipVinc** [comment]
This has been addressed, and we now throw an informative error.
