### ISSUE TITLE
[RFC] Nice syntax to _combine_ two PermutationGroup

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#1322]
Say I wanna combine two groups, like permutation and rotation group of a Lattice,.

```python
In [1]: import netket as nk
g = nk.
In [2]: g = nk.graph.Square(2)

In [3]: tg = g.translation_group()

In [4]: rg = g.rotation_group()

In [6]: trg = nk.utils.group.PermutationGroup(tg.elems+rg.elems, degree=tg.degree)
```

Can we have a nicer syntax to take the union of the two groups? (IIUC that is the union of the two) such that

$$ (T \cup R ) \vec{\sigma} = T\vec{\sigma} ?? R\vec{\sigma} $$ 

In Python, + represents the concatenation, so maybe that would be the good operator? But it does not convince me fully because it would suggest that

$$ (T + R ) \vec{\sigma} = T\vec{\sigma} + R\vec{\sigma} $$ 

which is a bit weird

cc @attila-i-szabo 

Also, on a minor note: could we automatically infer the degree if it's not specified or is this impossible?

**Comment by attila-i-szabo** [comment]
Not sure what you mean – the _union_ of two groups is almost never a group (it's not closed under multiplication).

**Comment by PhilipVinc** [comment]
True, but the case I showed is still a group. The fact that this is not true in general does not mean that it's not true sometimes.

And I think we can relatively easily check if it's still a group, can' twe?

**Comment by attila-i-szabo** [comment]
> ```python
> In [3]: tg = g.translation_group()
> 
> In [4]: rg = g.translation_group()
> ```

It only works in your example because the two groups are identical.

> And I think we can relatively easily check if it's still a group, can' twe?

Of course we can, but I'm pretty sure (I'm too busy to formally prove) that it only works if one group is a subgroup of another. I.e., it's not interesting in any nontrivial case.

**Comment by PhilipVinc** [comment]
>It only works in your example because the two groups are identical.

Ops, it's a typo. I wanted to combine rotations and translations.

**Comment by PhilipVinc** [comment]
I'll rephrase, what I am talking about is taking the product of two permutation groups, which is still a group.
Do we support it already or...not?

**Comment by attila-i-szabo** [comment]
Product we support, I'm pretty sure `group1 @ group2` is valid and generates a Cartesian product (going beyond that is too much effort).

The code you've written is the union of groups though, which is different.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PhilipVinc** [comment]
Indeed.

I al ways forget that python's product symbol is `@`...

**Comment by PhilipVinc** [comment]
Though, @attila-i-szabo, we should prune duplicate elements:

```python
>>> (tg@rg)
PermutationGroup(elems=[Id(), Rot(180°), Rot(90°), Rot(-90°), Translation([0, 1]), Translation([0, 1]) @ Rot(180°), Translation([0, 1]) @ Rot(90°), Translation([0, 1]) @ Rot(-90°), Translation([1, 0]), Translation([1, 0]) @ Rot(180°), Translation([1, 0]) @ Rot(90°), Translation([1, 0]) @ Rot(-90°), Translation([1, 1]), Translation([1, 1]) @ Rot(180°), Translation([1, 1]) @ Rot(90°), Translation([1, 1]) @ Rot(-90°)], degree=4)
>>> (tg@rg).to_array()
array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 2, 1, 3],
       [0, 2, 1, 3],
       [1, 0, 3, 2],
       [1, 0, 3, 2],
       [2, 0, 3, 1],
       [2, 0, 3, 1],
       [2, 3, 0, 1],
       [2, 3, 0, 1],
       [1, 3, 0, 2],
       [1, 3, 0, 2],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 1, 2, 0],
       [3, 1, 2, 0]])
```

**Comment by femtobit** [comment]
@PhilipVinc I think this is a case of what we describe in the docstring:
https://github.com/netket/netket/blob/3a90c14e671947af5a7aaa5d7cbb5592b64cf991/netket/utils/group/_permutation_group.py#L93-L95

`(tg@rg).remove_duplicates()` is not as concise, but should work.

**Comment by attila-i-szabo** [comment]
Exactly. I wouldn't make it part of the behaviour of `@` because we often rely on the Cartesian product structure, which would be messed up for eg. small systems


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
