### ISSUE TITLE
Issues implementing metropolis on a Hamiltonian

### ISSUE THREAD

**Issue by Gautameshwar** [netket/netket#1374]
I'm trying to train a model using NN. My Hamiltonian is a Hubbard model with varying on-site interaction (not constant V). So I wrote a customized Hamiltonian as per my need and input it for training a NN given in [this](https://netket.readthedocs.io/en/latest/tutorials/gs-matrix-models.html?highlight=eigenvalue#neural-network-quantum-state) tutorial. However, I am getting errors in training this Hamiltonian, saying it is an incompatible class for training. Can anyone please suggest a workaround for this and some info about what is going on? Attaching the relevant codes and errors:

* The Hamiltonian
```
Lambda = 4  # cutoff of each bosonic Fock space
N = 9  # number of bosons in our system 
L = 11 # no of sites in our bosonic system

hi = nk.hilbert.Fock(n_max = Lambda, N = L, n_particles = N)  # n_max -> Maximum occupation for a site

#the system parameters

V = 1.0
J = 1.0
U = 1.0

from netket.operator.boson import create, destroy, number

# we loop over all "sites" -> loop over N bosons
H_hop = sum([-J * (create(hi, i) * destroy(hi, i+1) + create(hi, i+1) * destroy(hi, i)) for i in range(N)])

H_onsite = sum([V * (i - L//2)**2 * (create(hi, i) * destroy(hi, i)) for i in range(L)])

H_interact = sum([U/2 * number(hi, i)*(number(hi, i) - 1) for i in range(N)])

H = H_hop + H_onsite + H_interact

eig_vals = nk.exact.lanczos_ed(
  H, k=13, compute_eigenvectors=False
)
```
* The error in training:

```
# trying out a different MLP variant
class MLP(flax.linen.Module):
  n_hidden_units: int

  @flax.linen.compact
  def __call__(self, x):
    
    W_0 = flax.linen.Dense(features=self.n_hidden_units, 
                    dtype=np.complex128,  
                    kernel_init=jax.nn.initializers.normal(stddev=0.1), 
                    bias_init=jax.nn.initializers.normal(stddev=0.1))(x)
    
    #W_0 = nn.activation.tanh(W_0)

    W_1 = flax.linen.Dense(features=2, 
                      dtype=np.complex128, 
                      kernel_init=jax.nn.initializers.normal(stddev=0.1), 
                      bias_init=jax.nn.initializers.normal(stddev=0.1))(W_0)
        
    y = flax.linen.tanh(W_1)
    return jnp.sum(y,axis = -1)

model = MLP(n_hidden_units = 20)

# Create the an exact sampler over the Hilber space , if it is not too large
sampler = nk.sampler.MetropolisLocal(H, n_chains = 6)

# create the VMC state
vstate = nk.vqs.MCState(sampler, model, n_samples=2**10)

optimizer = nk.optimizer.Sgd(learning_rate=0.05)
preconditioner = nk.optimizer.SR(diag_shift=0.1)

# Notice the use, again of Stochastic Reconfiguration, which considerably improves the optimisation
gs = nk.driver.VMC(
    H, optimizer, variational_state=vstate, preconditioner=preconditioner
)

# logging and running : sometimes need to rung longer than 300 to exit a plateaux
log = nk.logging.RuntimeLog()
gs.run(n_iter=300, out=log)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-55-f6ba8b9948e2>](https://localhost:8080/#) in <module>
     24 
     25 # Create the an exact sampler over the Hilber space , if it is not too large
---> 26 sampler = nk.sampler.MetropolisLocal(H, n_chains = 6)
     27 
     28 # create the VMC state

4 frames
[/usr/local/lib/python3.7/dist-packages/netket/sampler/base.py](https://localhost:8080/#) in __post_init__(self)
    119             raise ValueError(
    120                 "hilbert must be a subtype of netket.hilbert.AbstractHilbert, "
--> 121                 + "instead, type {} is not.".format(type(self.hilbert))
    122             )
    123 

ValueError: hilbert must be a subtype of netket.hilbert.AbstractHilbert, instead, type <class 'netket.operator._local_operator.LocalOperator'> is not.
```

**Comment by PhilipVinc** [comment]
It's telling you that the first argument passed to `MetropolisLocal` must be an hilbert object, not an operator.

Just change this line 
```python
# Create the an exact sampler over the Hilber space , if it is not too large
sampler = nk.sampler.MetropolisLocal(H, n_chains = 6)
```
to 
```python
# Create the an exact sampler over the Hilber space , if it is not too large
sampler = nk.sampler.MetropolisLocal(hi, n_chains = 6)
```

**Comment by Gautameshwar** [comment]
I'm embarrassed at myself for not seeing this silly typo. Apologies! But now I have another error in initializing the stochastic configuration. Please let me know what it says.. (I'm extremely sorry if I sound too much of a noob. I'm just getting introduced to this library, and getting to solve these errors helps me learn it)

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-69-4152f5438d42>](https://localhost:8080/#) in <module>
     34 # Notice the use, again of Stochastic Reconfiguration, which considerably improves the optimisation
     35 gs = nk.driver.VMC(
---> 36     H, optimizer, variational_state=vstate, preconditioner=preconditioner
     37 )
     38 

[/usr/local/lib/python3.7/dist-packages/netket/driver/vmc.py](https://localhost:8080/#) in __init__(self, hamiltonian, optimizer, variational_state, preconditioner, sr, sr_restart, *args, **kwargs)
     73                     the hamiltonian has hilbert space {hamiltonian.hilbert}.
     74                     The two should match.
---> 75                     """
     76                 )
     77             )

TypeError: the variational_state has hilbert space Fock(n_max=4, n_particles=9, N=11)
                    (this is normally defined by the hilbert space in the sampler), but
                    the hamiltonian has hilbert space Fock(n_max=4, n_particles=9, N=11).
                    The two should match.
```

**Comment by PhilipVinc** [comment]
When you create a driver, it checks that `variational_state.hilbert == H.hilbert` because it cannot optimise an hamiltonian on an Hilbert space different from that of the variational state.

But judging from the error message, it seems that the two are indeed identical, so you indeed found small bug in our code!
The error originates because 
```python
>>> nk.hilbert.Fock(n_max = Lambda, N = L, n_particles = N) == nk.hilbert.Fock(n_max = Lambda, N = L, n_particles = N)
False
```
which of course is wrong.

I will fix this. In the meantime you can work around the bug by being careful in only creating the Hilbert object once and always reusing the same

**Comment by PhilipVinc** [comment]
@Gautameshwar the fix is in master now, so you can 
- either use the workaround I mentioned above of only creating the Hilbert space once, and update netket in a week or so once we release a new version with the fix.
- install master (not recommended) by running `pip install git+https://github.com/netket/netket`

**Comment by Gautameshwar** [comment]
Thank you very much for letting me know about this! :) I'll try to stick with the former suggestion for noww. One last thing. The neural network in the tutorial seems to work fine for smaller hilbert sizes but gives pretty unpredictable and incoherent results everytime I run it for larger hilbert size systems. Is this also somehow related to this bug? Or is it something else...

**Comment by PhilipVinc** [comment]
> . The neural network in the tutorial seems to work fine for smaller hilbert sizes but gives pretty unpredictable and incoherent results everytime I run it for larger hilbert size systems. Is this also somehow related to this bug? Or is it something else...

@Gautameshwar No, the bug was only an error in how we reported... errors. typically if you can solve small systems reliably and you can't solve large systems, it's often either an initialisation problem (your parameters are drawn from a too wide or peaked distribution) and/or a learning rate problem.
