### ISSUE TITLE
`nkx.operator.FermionOperator2nd` are transposed

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#1385]
It seems that those operator's `O.get_conn(x)` methods return the `xp` such that `<xp|O|x> != 0` instead of the `<x|O|xp>` used as convention in the rest of NetKet and opposed to the documentation.

This is not really a problem for optimising the energy if the hamiltonian is real-valued, but can create issues with non-symmetric operators or observables.

**Comment by gcarleo** [comment]
it is true that, in a sense, the convention <x|O|xp> maybe makes more sense, but yeah we should be consistent ... !

**Comment by gcarleo** [comment]
indeed given the definition of the local energy it makes more sense to define get_conn in the way it is defined now, even though I suspect nobody ever documented this in get_conn? (mostly because for real operators it's the same indeed, so maybe we never bothered)

**Comment by PhilipVinc** [comment]
> mostly because for real operators it's the same indeed, so maybe we never bothered

though this matters for non symmetric operators which might show up in a correlation...

**Comment by gcarleo** [comment]
is this still an open issue? is it the only remaining bug to be addressed before we can declare that fermions are not experimental anymore? @jwnys ?

**Comment by PhilipVinc** [comment]
This is the main one. There's the fact that they are very slow to be symbolically manipulated but I won't consider it as a blocker...

**Comment by gcarleo** [comment]
is this "only" a matter of adding a few complex conjugate in the get_conn or is it more complicated than that?

**Comment by jwnys** [comment]
The main reason they are experimental to my knowledge is to wait for feedback from users... Except for this issue, no bugs have been found that I'm aware of. The main additional thing to include would be to include physical Hamiltonian that @inailuig is working on. (the current version is very inefficient for some of those)

**Comment by jwnys** [comment]
Another thing is that it's written to be very general. So, it doesn't take into account any information from the Hilbert space. If there is a fixed number of fermions, the number of estimated connected elements will be much too large..

**Comment by gcarleo** [comment]
OK I see, this can be later improved maybe merging some of the things @inailuig is working on... But if the implementation is correct but slow, it's not a big problem for now

**Comment by PhilipVinc** [comment]
Indeed.
Apart from bugs, my main issue was documentation. Now @gcarleo contributed a nice tutorial and that helps a lot, but for example how to build those objects starting from PyScf or an hamiltonian in other formats is an art that is kept secret, and it is one of the large use-cases of this stuff.

Several people let me know recently that they were frustrated with trying to use our fermionic operators with chemistry hamiltonians. It's not impossible, but it takes a lot of effort and decent understanding of the difference in how the spin sector is handled in the two setups. 

And it's not made simple by the fact that if you start having more than 12 total orbitals the symbolic manipulations slow down to a crawl. 

This point stands, in my opinion.

**Comment by gcarleo** [comment]
Agreed, we should improve on that by providing a dedicated chemistry hamiltonian, but we can do this after moving the whole thing to stable netket, I am not sure we will change the interface anymore, we will just add new hamiltonians / operators

**Comment by jwnys** [comment]
This is also what I mean: quantum chemistry Hamiltonian are just a specific type of Hamiltonians (that are hard in general btw). For this there should be a specific class "QuadraticHamiltonian" or whatever that optimizes that (this is what @inailuig is working on). The current implementation focuses on lattice fermions applications.

**Comment by jwnys** [comment]
FYI, making different types of Hamiltonians is also how e.g. openfermion does it (see e.g. https://quantumai.google/reference/python/openfermion/ops/InteractionOperator). This makes sense to me.
And about the comment from the matching of pyscf: I've explained this API to many people, and nobody's given feedback on how to improve the understanding of this. It's just a different convention with a single boolean flag. If you have suggestions from talking to people, they remain welcome.

**Comment by jwnys** [comment]
Furthermore, pyscf integration is a whole different beast that requires connecting two libraries. It makes sense to know the conventions of both packages. So, we can make a better integration with pyscf (which is again something @inailuig was working on).

**Comment by gcarleo** [comment]
can't we just have a `from_pyscf` converter that does what is needed? I think that would be largely sufficient

**Comment by gcarleo** [comment]
indeed there is no need to change the interface of our fermionic operators, that is fine, and we are not going to change it soon anymore, so I think we are all agreeing that after fixing this bug we can move stuff to non experimental

**Comment by jwnys** [comment]
We can add that yes, we have that available. @inailuig

**Comment by inailuig** [comment]
> can't we just have a `from_pyscf` converter that does what is needed? I think that would be largely sufficient

I have exactly this function already in my repo, I can open a PR to merge it to netket soon.

Also I have an efficient version of the operator for chemistry which jannes mentioned above

**Comment by PhilipVinc** [comment]
There is also this https://github.com/netket/netket/pull/1277 that should be merged as it reduces the number of connected elements

**Comment by PhilipVinc** [comment]
As I said a while back, having a `from_pyscf` + a simple tutorial or at least example would be enough to move fermions out of experimental. Of course, on top of fixing the existing issues.

Other hamiltonians can be released later

**Comment by jwnys** [comment]
I'd rather say that having proper lattice fermions is enough to move out of experimental. #1277 was solved in another merged PR.

**Comment by inailuig** [comment]
> > can't we just have a `from_pyscf` converter that does what is needed? I think that would be largely sufficient
> 
> I have exactly this function already in my repo, I can open a PR to merge it to netket soon.
> 
https://github.com/netket/netket/pull/1602

**Comment by PhilipVinc** [comment]
I would like this fixed for the next release...

**Comment by gcarleo** [comment]
Who is willing to solve this transpose issue ? @inailuig @jwnys ?

**Comment by jwnys** [comment]
I will fix it

**Comment by inailuig** [comment]
Has been closed by https://github.com/netket/netket/pull/1640.
