### ISSUE TITLE
The parameter 'Alpha' in RbmSpinSymm for custom Hamiltonian

### ISSUE THREAD

**Issue by lazerjet** [netket/netket#139]
in `netket/Tutorials/CustomHamiltonian/custom_hamiltonian.py`,
changing the machine to RbmSpinSymm and leaving the rest of the code untouched (so Alpha is left as 1) results in the output 
'# Graph created'
'# Number of nodes = 20'
'# RBM Initizialized with nvisible = 20 and nhidden = 1'
'# Symmetries are being used : 22 parameters left, instead of 41'
.....
which implies that only 1 hidden unit is used instead of 20. Moreover, if the value of Alpha is changed then the nhidden as displayed will change accordingly (and equal to Alpha).

**Comment by lazerjet** [comment]
whereas in `netket/Tutorials/Ising1d/ising1d.py`
the same modification results in the output
`# No colors specified, edge colors set to 0`
`# Hypercube created`
`# Dimension = 1`
`# L = 20`
`# Pbc = 1`
`# Transverse-Field Ising model created`
`# h = 1`
`# J = 1`
`# RBM Initizialized with nvisible = 20 and nhidden = 20`
`# Symmetries are being used : 22 parameters left, instead of 440`

**Comment by gcarleo** [comment]
This is most likely because you are writing 
```python
# defining the wave function
pars['Machine'] = {
    'Name': 'RbmSpinSymm',
    'Alpha': 1.0,
}
```
and not 
```python
pars['Machine'] = {
    'Name': 'RbmSpinSymm',
    'Alpha': 1,
}
```

This is (mostly) a JSON-related  conversion between integers and doubles. Again, in version 2.0 there is no such issues. I encourage you to work with that one as soon as we release the beta version (most likely this or next week).
