### ISSUE TITLE
LocalOperator should return error when same site is used twice

### ISSUE THREAD

**Issue by chrisrothUT** [netket/netket#1404]
Simple example of computing σ^2 for a single site. 

```
>>> hi = nk.hilbert.Spin(s=0.5, total_sz = 0, N=4)
>>> heisenberg = np.array([[1, 0, 0, 0],[0, -1, 2, 0],[0, 2, -1, 0],[0, 0, 0, 1]])
>>> ha = nk.operator.LocalOperator(hilbert=hi,operators=[heisenberg],acting_on=[(0,0)])
>>> vstate.expect(ha)
1
```
The answer should be 3 of course but Netket returns 1 because it doesn't account for SxSx and SySy returning the state back to itself.

**Comment by gcarleo** [comment]
This should just error though, Im surprised it doesn't give an error when
you give the same site twice in acting_on!

**Comment by chrisrothUT** [comment]
Yeah I guess you shouldn't be able to construct a Hilbert space using the same site twice :). This should return an error though. Is there a convenient way to compute the square of an operator in Netket?

**Comment by gcarleo** [comment]
operator*operator?

**Comment by chrisrothUT** [comment]
That is certainly convenient! I will leave this up though because I think this shouldn't error out silently

**Comment by wdphy16** [comment]
I also encountered this and I fixed this in #1392

**Comment by gcarleo** [comment]
Great Dian! so why is this not erroring in this case?

**Comment by wdphy16** [comment]
That PR is not released yet, and I guess he is not using the master branch

**Comment by chrisrothUT** [comment]
Sorry, I now realize I was using an older version when I encountered the error!
