### ISSUE TITLE
Error in fermi-hubbard example

### ISSUE THREAD

**Issue by GiantElephant123** [netket/netket#1486]
Hello, there.

It seems that the definition of create and annihilation operators are defined reversely in fermi-hubbard model, and results are wrong. [link](https://github.com/netket/netket/blob/26372e3527ae12861cc7953c24654614e8679d87/Examples/Fermions/fermi_hubbard.py#L25C1-L26)

**Comment by PhilipVinc** [comment]
@jwnys wrote those examples...
Jannes, do you agree with the above?

**Comment by imi-hub** [comment]
By putting the correct definitions of the creation and annihilation operators, the model seems to converge towards the ground state energy. We can compare the variational state (red curve) with the ED results (black lines).
![test_fermions](https://github.com/netket/netket/assets/80409000/3cdcd76e-a0ef-4f6f-a803-8ea75ae964e2)
Could you perhaps explain what type of errors you are getting?

**Comment by PhilipVinc** [comment]
good! Could you please open a quick PR to correct this issue?

**Comment by PhilipVinc** [comment]
Hmm.. just because you are using `.number` instead of doing cdag c.... as  $cc^\dagger = 1-c^\dagger c$. 
But good, at least the result was not wrong.

**Comment by imi-hub** [comment]
PR: 
https://github.com/netket/netket/pull/1487

**Comment by GiantElephant123** [comment]
Thanks for the prompt response and sorry for causing confusion. I should be more specific:

I actually changed the setting in the original file to 1d hubbard chain model (L=2, D=1, t=1, U=0.01, n_fermion=(1,1)), and find VMC results has an overall minus sign compared to exact results $`E_0`$.
![image](https://github.com/netket/netket/assets/96293191/ae3d02bf-077b-4dec-9399-957a209cb32b)

I think the reason is the wrong hopping term in orignal file, which reads
```math
H_{\rm wrong}=-t\sum_i a_{i+1}a_i^\dagger + a_ia_{i+1}^\dagger
```
Since $`a_ia_{i+1}^\dagger=-a_{i+1}^\dagger a_i`$, I think there should be a overall minus sign compared to the correct hopping term and this explains the sign problem in VMC and exact values. 

After I swap the name, the results becomes reasonable:
![image](https://github.com/netket/netket/assets/96293191/c441ae5d-b24f-467e-823f-c967cd814acc)

Strangely, for D=2, 2d hubbard model $`H_{\rm wrong}`$ will still gives the right answer and I don't know why. Maybe due to the particle-hole symmetry for half filling system?

**Comment by gcarleo** [comment]
The naming issue was not affecting the number operator, that was defined separately and in the correct way, so since the hopping is invariant under renaming of c and cdagger, there was no actual problem with the energy... On the other hand I'm not sure I understand the context of the minus sign issue you mention

**Comment by GiantElephant123** [comment]
I'm afraid the hopping is not invariant under renaming of fermion operator $a_i$ and $a_i^\dagger$.
According to the original wrong naming and code
```python
def c(site, sz):
    return nkx.operator.fermion.create(hi, site, sz=sz)


def cdag(site, sz):
    return nkx.operator.fermion.destroy(hi, site, sz=sz)


def nc(site, sz):
    return nkx.operator.fermion.number(hi, site, sz=sz)


up = +1 / 2
down = -1 / 2
ham = 0.0
for sz in (up, down):
    for u, v in g.edges():
        ham += -t * cdag(u, sz) * c(v, sz) - t * cdag(v, sz) * c(u, sz)
for u in g.nodes():
    ham += U * nc(u, up) * nc(u, down)
```
The hamiltonian used is actually given as below:
```math
H_{\rm wrong}=-t\sum_i a_{i}a_{i+1}^\dagger+a_{i+1}a_{i}^\dagger  
```
But the correct hopping term reads
```math
H_{\rm correct}=-t\sum_i a_{i}^\dagger a_{i+1}+a_{i+1}^\dagger a_{i}  = t\sum_{i}a_{i+1}a_i^\dagger+a_ia_{i+1}^\dagger={\color{red} -}H_{\rm wrong}
```
Sorry if I have made some stupid mistakes.

**Comment by gcarleo** [comment]
yes you are actually right, it was my oversight. Thank you for catching this issue, indeed this is still in the `Experimental` branch of netket because it is not fully tested, so if you find other inconsistencies please tell us.

**Comment by GiantElephant123** [comment]
Never mind, I have learned a lot from this example.
