### ISSUE TITLE
Replace old tutorials with Jupyter notebooks

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#156]
The tutorials [on the website ](https://www.netket.org/tutorials/home/) should be replace by Jupyter notebooks, and should be part of the main NetKet repository. 
This has several advantages: 
1. ipython notebooks are easily converted to markdown, thus can be immediately put on the website 
2. both the documentation and the tutorials will leave on the main repo, thus being updated more regularly with PRs and also being tested more efficiently 

@kchoo1118 has a very nice example of how the tutorials should be, please do a PR with it and let's help him finish the other tutorials!

**Comment by jamesETsmith** [comment]
The build of NetKet might be a bit complicated for use with [Binder](https://mybinder.org/), but I think it's worth mentioneing if we're going to have tutorials as Jupyter notebooks. It lets you run jupyter notebooks on virtual machines so users could run a few simple tutorials using only a browser. For more information about Binder you can check out their docs [here](https://mybinder.readthedocs.io/en/latest/). Do you think this would be worthwhile?

**Comment by fabienalet** [comment]
Hi 
sorry I'm asking a very very basic question. I'd like perhaps to contribute to tutorials while learning Netket v2.0 on the way. 
But I'm currently unsure on how should I install / compile / use the python bindings proposed in the v2.0. I tried to do cmake, make and make install, but that didn't seem to install the python library netket, only a shared object (thus any python code gets stucks when importing netket).
Probably I'm missing something very basic (but I guess the basic user of netket could as well).

**Comment by gcarleo** [comment]
Hi @fabienalet !

There is some installation instructions here https://github.com/netket/netket/pull/82 , basically you don't need to run make yourself, but do 
```
pip install . 
```
in the main repo. This will automatically register the library in python, and you can start using it as shown in the folder Examples/. Only requirement here is the c++11 mpi compiler. 

For the stable version, one will not need to download the repository, but just go on the command line and do 
```
pip install netket
```
this uses che centralized python distribution systems and automatically downloads/compiles everything. If you do that now you will get some earlier version that I registered on the server maybe two weeks ago. I would advise at this stage to always follow the first strategy, to use the latest version. 

It would be great if you could help us write tutorials! We are actually very close to releasing a beta for 2.0 and update the website, but we are still missing several tutorials...

**Comment by gcarleo** [comment]
@everthemore @ShHsLin , do you like python notebooks? 
It would be great to have a short tutorial on supervised learning, similar to what you find in `Tutorials/` !

**Comment by gcarleo** [comment]
@fabienalet you mentioned you had some issue in the revised version of the tutorials you are working on?

**Comment by fabienalet** [comment]
@gcarleo Sorry I've not been active on this, I will take this over very soon. My main issue was that in 1d RBM seems quite superior to everything, hence a tutorial comparing to other more elaborated networks was not very much pledging in favor of using the later ... 
I'll try to see what can be done
