### ISSUE TITLE
[Fermions] fermion.create/destroy have inconsistent 

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#1604]
Docstrings for fermionic creation and destruction operators say that the spin must be passed as an integer, however it actually wants a float value to be passed in, so the docstring should be fixed. 
See https://netket.readthedocs.io/en/latest/api/_generated/operator/netket.experimental.operator.fermion.destroy.html#netket.experimental.operator.fermion.destroy

Moreover, I think it's a wrong choice to go for this choice, because throughout netket we label spins up and down with -1 and 1 so we should do the same here as well instead of changing the standard.

**Comment by gcarleo** [comment]
True, even though it's not super clean to use -1,+1 for fermions (we should specify we use eigenvalues of the Pauli matrix and not the actual spin... mmm)

**Comment by PhilipVinc** [comment]
what should we use if not +-1?

**Comment by jwnys** [comment]
I see float everywhere, where do you see int?

**Comment by PhilipVinc** [comment]
I fixed it a while back https://github.com/netket/netket/pull/1615 .
