### ISSUE TITLE
Rename `MestropolisSampler.n_sweeps` to `sweep_size`

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#1657]
The current name is confusing.

cc @gcarleo .

Someone wants to do it? Needs also a deprecation warning and doing some search and replace in the documentation.

**Comment by iamoeg** [comment]
Hello @PhilipVinc! As I'm no quantum physicist (and relatively new to programming), I'd like to understand your requirements before committing to the work.

If I understand well, you need the `n_sweeps` property renamed to `sweep_size` (and all references to it updated accordingly) in the `MetropolisSampler` and related classes, specifically in the following packages (please correct me if I'm missing something):

- `netket.sampler.metropolis`
- `netket.sampler.metropolis_numpy`
- `netket.experimental.sampler.metropolis`
- `netket.experimental.sampler.metropolis_numpy`

These changes also need to be reflected in the documentation where relevant.

As for the deprecation warning, what's the format and where would you need it to be placed? The docs, the class' docstrings, both, somewhere else entirely?

And finally, per the [developer docs](https://netket.readthedocs.io/en/latest/docs/contributing.html), you need the code to:

- pass the entire test suite (is there a preferred format for sharing test reports?)
- be squashed in a single commit
- be formatted using Black

Do I get it right? Also, is there anything special I should keep in mind or pay attention to while making the updates?

**Comment by iamoeg** [comment]
Hello again @PhilipVinc 

So I went ahead and dived into the codebase and documentation, and I managed to make the changes that were needed. I think I figured out most of the questions I asked in my previous comment, but please review PR #1673 and let me know if there is anything that needs to change.
