### ISSUE TITLE
PypI registration issue in 2.0

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#170]
While everything works smoothly when installing the repository locally, a.k.a.
```
pip install .
```
the version registered on PypI has issues.

Part of the issues came from the fact that the binaries I had registered are not compatible with other platforms. I have since removed binaries and kept only source files in the PypI, as obtained doing

```
python3 setup.py sdist
```
and registered this on the test PipI envinronment. 

Now, in this test PypI envinroment the real problem emerges 
```
python3 -m pip install --index-url https://test.pypi.org/simple/ netket

Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: netket in /Users/giuscarl/Works/NetKet/netket (2.0b2)
Collecting cmake (from netket)
  Using cached https://test-files.pythonhosted.org/packages/21/3f/14e8756101e8045e341afdc340cf12471843ae9b819e231de01106c59d19/cmake-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g_/_vb4dpb54t13bq0543dd2qg00000gn/T/pip-install-14jd6l_w/cmake/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g_/_vb4dpb54t13bq0543dd2qg00000gn/T/pip-install-14jd6l_w/cmake/
```
that I have absolute no idea how to solve. 

HELP is very much needed. We might think moving to a conda install (including openmpi) if this fails.

**Comment by femtobit** [comment]
Interesting. This seems to be an issue with the installation of the `cmake` PyPI package. [This issue](https://gitlab.kitware.com/cmake/cmake/issues/17950) seems related, but it sounds like it should have been fixed some time ago. Maybe the version of `cmake` from `test.pypi.org` is not current?

Maybe you can install `cmake` first from the PyPI (not the test server)?
```
$ python3 -m pip install cmake
$ python3 -m pip install --index-url https://test.pypi.org/simple/ netket
```

**Comment by gcarleo** [comment]
This seems to be a packaging problem. The sources do not include the actual
NetKet directory and all related things... Looking into solving this now

**Comment by gcarleo** [comment]
Can anybody please try
```
pip install -i https://test.pypi.org/simple/ netket
```
thanks!

**Comment by jamesETsmith** [comment]
On my mac, the jobs crashes and gives a bunch of output. It looks like it's building numpy as well as netket and it appears to fail while building numpy.  But, it works on redhat linux cluster! 

```bash
...
...
    File "numpy/core/setup.py", line 686, in get_mathlib_info
      raise RuntimeError("Broken toolchain: cannot link a simple C program")
  RuntimeError: Broken toolchain: cannot link a simple C program
  
  ----------------------------------------
  Failed building wheel for numpy
  Running setup.py clean for numpy
Successfully built netket
Failed to build numpy
Installing collected packages: numpy, netket
  Running setup.py install for numpy ... error

...
...
```

**Comment by gcarleo** [comment]
It might be because I am not installing cmake as a dependency... Maybe on
the Mac you can try to install cmake independently and then redo pip install

**Comment by jamesETsmith** [comment]
After installing `cmake` separately it crashes with much the same error, but if I install`numpy` separately in the env, NetKet works. When I install `numpy` separately it just builds the package from a wheel file, but when it was installed along with NetKet it looks like it's actually building `numpy`. Do you know why that's happening?

**Comment by femtobit** [comment]
For me the installation works now:
```
neon ~> pip3 install --user -i https://test.pypi.org/simple/ netket
Collecting netket
  Downloading https://test-files.pythonhosted.org/packages/5b/0e/9be3ba296c2dad0cc36e5dc569b28fcf1e5ad63223280c1e944fe2d544d5/netket-2.0b6.tar.gz (139kB)
    100% |████████████████████████████████| 143kB 2.7MB/s 
Collecting numpy (from netket)
  Downloading https://test-files.pythonhosted.org/packages/4f/96/b3329750a04fcfc316f15f658daf6d81acc3ac61e3db390abe8954574c18/numpy-1.9.3.tar.gz (4.0MB)
    100% |████████████████████████████████| 4.0MB 446kB/s 
Building wheels for collected packages: netket, numpy
  Running setup.py bdist_wheel for netket ... done
  Stored in directory: /home/damian/.cache/pip/wheels/d7/aa/56/5b0ad9bedf951f17bc9ed8a746f4030bddb83ce7b2e2d65323
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /home/damian/.cache/pip/wheels/11/31/e0/3589a9ed32bdf64bc022c97a3703ac9962681e0e0087d6f566
Successfully built netket numpy
Installing collected packages: numpy, netket
Successfully installed netket-2.0b6 numpy-1.16.1
```

Though it does compile numpy as well in addition to netket, which seems unnecessary as I do have it already installed (in a slightly older version, but still).

Also, after installing it, Python crashes on importing the module due to MPI issues:
```
neon ~> python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netket
[neon:20792] mca_base_component_repository_open: unable to open mca_patcher_overwrite: /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi/mca_patcher_overwrite.so: undefined symbol: mca_patcher_base_patch_t_class (ignored)
[neon:20792] mca_base_component_repository_open: unable to open mca_shmem_mmap: /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi/mca_shmem_mmap.so: undefined symbol: opal_show_help (ignored)
[neon:20792] mca_base_component_repository_open: unable to open mca_shmem_sysv: /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi/mca_shmem_sysv.so: undefined symbol: opal_show_help (ignored)
[neon:20792] mca_base_component_repository_open: unable to open mca_shmem_posix: /usr/lib/x86_64-linux-gnu/openmpi/lib/openmpi/mca_shmem_posix.so: undefined symbol: opal_shmem_base_framework (ignored)
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
[...]
```
This seems to be the same issue I encountered in the discussion of PR #128. I worked around it by compiling against MPICH instead of OpenMPI. I wonder whether this occurs on other Ubuntu machines as well.

**Comment by gcarleo** [comment]
OK, further test 
```
pip install -i https://test.pypi.org/simple/ netket
```
I have put the dependency on numpy in requirements.txt, since it is not strictly needed during installation

**Comment by ooreilly** [comment]
Installation works for me in Ubuntu, but crashes in OS X.

Installation fails to download Eigen.

```
    warning: CMakeBuild: Scanning dependencies of target eigen_project
    [  5%] Creating directories for 'eigen_project'
    [ 11%] Performing download step (download, verify and extract) for 'eigen_project'
    -- downloading...
         src='https://github.com/eigenteam/eigen-git-mirror/archive/3.3.5.tar.gz'
         dst='/private/var/folders/zz/bq1sb4ws53n05vhzt_bw4s880000gn/T/pip-install-q77absm9/netket/build/temp.macosx-10.6-intel-3.6/eigen_project-prefix/src/3.3.5.tar.gz'
         timeout='none'
    CMake Error at /private/var/folders/zz/bq1sb4ws53n05vhzt_bw4s880000gn/T/pip-install-q77absm9/netket/build/temp.macosx-10.6-intel-3.6/eigen_project-prefix/src/eigen_project-stamp/download-eigen_project.cmake:27 (message):
      error: downloading
      'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.5.tar.gz' failed
     status_code: 35
        status_string: "SSL connect error"
        log:   Trying 192.30.255.112...

      Connected to github.com (192.30.255.112) port 443 (#0)

      Unknown SSL protocol error in connection to github.com:-9836

      Closing connection 0

```

**Comment by gcarleo** [comment]
Thanks @ooreilly , this is odd... ! Did you check if this is just a temporary server error from github? Maybe trying again later helps

**Comment by ooreilly** [comment]
@gcarleo I still get the same problem. However, I haven't used my mac in a while so my python 2.7 is outdated. I used `pip3` to use Python 3.6.4. I can see if I can update my Python 2.7 later and see what happens then.

**Comment by gcarleo** [comment]
@ooreilly just to understand better: the error you reported on Mac Os is with pip3 or with pip (and python 2.7) ?

**Comment by ooreilly** [comment]
@gcarleo The error I reported is with pip3 and Python 3.6.4. I can currently not use pip right now because my Python 2.7 version is outdated. Trying to update it.

**Comment by ooreilly** [comment]
@gcarleo . OK. I installed python 2.7.15, but when running `pip ...` CMake was still detecting system Python 2.7.11. As a quick fix, I temporary moved the system version. Now, CMake finds Python 2.7.15. I see the same error as before:  unable to download Eigen. I also tried installing Python 3.7.2. Running `pip3 ...` gives the same error. It is weird, because the link to Eigen works if you try it manually.

**Comment by gcarleo** [comment]
OK thanks @ooreilly, this is really strange... it might be even be some firewall related thing, who knows! 
Maybe you could check (last one) if downloading from master and then doing pip install . works, just to understand where the origin of the problem is

**Comment by gcarleo** [comment]
As far as I understand the last version available on the test server 
```
pip install -i https://test.pypi.org/simple/ netket
```
works for everybody but for @ooreilly. Is that correct @femtobit @kchoo1118 @jamesETsmith ? By the way, there MUST be a way to do unit testing of this thing, otherwise we get crazy every time we have a new release!

**Comment by ooreilly** [comment]
@gcarleo I think I can fix the problem by setting pypi as a trusted hosted host. Unfortunately, I have run out of batteries in my MacBook and my charger is broken, will replace it tomorrow. Glad to hear that the installation is working for everybody else.

**Comment by jamesETsmith** [comment]
@gcarleo that's correct, although on the macbook it did require separate installation of numpy and cmake.
