### ISSUE TITLE
vmap for modules

### ISSUE THREAD

**Issue by hendrydouglas11** [netket/netket#1715]
I want get the  outputs of multiple vwfs (same architectures  but different parameters) for the same inputs.  I'm using the flax.linen.vmap to create a vectorized module.  The vectorized module 's call function  is a vmap the individual module's call function and the parameters are all the individual module parameter arrays concatenated with same pytree structure.  When I try to use a netket module decorated with @deprecate_dtype i get an error "missing 1 required positional argument: 'self'" when initializing.

Here is an example code which follows the implementation in https://flax.readthedocs.io/en/latest/developer_notes/lift.html.  This code works as expected with a custom RBM module which is exactly the same as netket's but without the   @deprecate_dtype decorator.

```python
import os
os.environ["JAX_PLATFORM_NAME"]="cpu"
from typing import Union, Any,Callable, Sequence,Dict
from dataclasses import dataclass, field
import netket as nk
from netket import jax as nkjax
import json
import numpy as np
import jax
import jax.numpy as jnp
from jax import random
from jax.flatten_util import ravel_pytree
from jax.nn.initializers import normal
import flax.linen as nn
import flax
from flax.core import FrozenDict
from netket import nn as nknn

# RBM_custom is the same netket's RBM except without  @deprecate_dtype decorator
from vwf_custom import RBM_custom

#individual vwf model
#VWF_Module=nk.models.RBM #will give an error
VWF_Module=RBM_custom # will work as excepted and is same as above but without @deprecate_dtype decorator
vwf_module_meta={'alpha': 2,'use_hidden_bias':True,'use_visible_bias':True,'param_dtype':complex}

def pyt_shape(tree):
  return jax.tree_map(lambda x: x.shape, tree)

L =32 # number of spins
nch=8  # number of chains
chl=500 # length of each chain
nsamp=nch*chl # total samples

#random input
key_use, key_split = random.split(random.key(0))
x = random.normal(key_use , (nch,chl,L) )
key_use, key_split = random.split(key_split)


#Initializing an individual model for individual calls (ind_vars is not used again)
model_ind = VWF_Module(**vwf_module_meta)
ind_vars = model_ind.init(key_use, x) 
key_use, key_split = random.split(key_split)
print("indvidual model params shape")
print(pyt_shape(ind_vars['params']))
y=model_ind.apply(ind_vars,x)
print(f" indvidual model output shape: {y.shape} for {nch} chains and with length {chl} \n")


#Module containing (n_model) individual VWF_Module models each with different params vectorized using nn.vmap
class VWF_Module_Vec(nn.Module):
  n_model: int = 1
  ind_module_meta: Dict[str,Any] = field(default_factory=dict) # intializing meta variables for the individual module (not sure if this is a smart way to do it)

  @nn.compact
  def __call__(self, input):
    Vmap_vwf = nn.vmap(VWF_Module, variable_axes={'params': 0}, split_rngs={'params': True}, in_axes=None,axis_size=self.n_model)
    return Vmap_vwf(**self.ind_module_meta,name='ind_params_stacked')(input)

nvwf=10 # number indivdual vwfs
#creating a model of vectorized individual models which defines nvwf separate vwfs with one model
model_vec = VWF_Module_Vec(n_model=nvwf,ind_module_meta=vwf_module_meta)
vec_vars = model_vec.init(key_use, x)
key_use, key_split = random.split(key_split)
#vec_model params are all the ind_model params stacked (concatenated as the first index) insde (ind_params_stacked)
print(f'vectorized model params shape for {nvwf} vwfs')
print(pyt_shape(vec_vars['params']))
# vec_model outputs are all ind_model outputs stacked (concatenated as the first index)
y=model_vec.apply(vec_vars,x)
print(f" indvidual model output shape: {y.shape} for {nvwf} vwfs and {nch} chains and with length {chl} \n")


#get a new random input and output
x = random.normal(key_use , (nch,chl,L) )
key_use, key_split = random.split(key_split)
y=model_vec.apply(vec_vars,x)

#verify vectorized model gives the same outputs as the individual model

def pyt_index_in_dim(tree,i):
  return jax.tree_map(lambda x: jax.lax.index_in_dim(x,i,keepdims=False), tree)

print(" relative error between vec and ind vwf model outputs ")
for i in jnp.arange(nvwf):
  vec_vars_slice = {'params': pyt_index_in_dim(vec_vars['params']['ind_params_stacked'],i)} # ith vwf's vars from vec vars
  y_ind = model_ind.apply(vec_vars_slice,x) #output given by the ind model
  y_vec= jax.lax.index_in_dim(y,i,keepdims=False) #output given by the vec model
  err = jnp.linalg.norm( y_vec - y_ind ) / jnp.linalg.norm( y_ind )
  print(f' vwf_{i} error: { err }')


``

**Comment by PhilipVinc** [comment]
You're right, it's a netket bug. 

It arises because the decorator `@deprecate_dtype` transforms the `nn.Module` it decorates into a standard `function` with the additional `dtype` argument and warning.
We had added this in august 2022 because in older versions of netket the dtype of the parameters was stored as `dtype`, while starting from flax 0.5 and their support for complex number this was renamed to `param_dtype`.
We added the warning+deprecation to avoid breaking all our examples and code of users.

This behaviour breaks all flax transformations such as `nn.vmap` because they check that the object they transform is a module, and this wrapper is not.

There are two solutions: 
 - either we complete the deprecation, which dates back to Netket 3.5 released in august 2022 (so about 18 months ago) and completely remove completely support for the old argument `dtype` (note that in general we've been keeping things around for 2 years)
 - Or we keep the status-quo, and our modules are not compatible with flax transforms.

I would err in favour of removing all those `@deprecate_dtype` since 18 months is quite a long time anyway... I dunno what @gcarleo thinks

**Comment by gcarleo** [comment]
Let's remove the deprecations, I agree...

**Comment by PhilipVinc** [comment]
@hendrydouglas11 can you make a PR? It is as easy as removing all `@deprecate_dtype` that occur in netket, the definition of `deprecate_dtype` itself, and probably remove a few tests here and there checking that `deprecate_dtype` works.
