### ISSUE TITLE
Warning: Another transport will be used instead, although this may result in lower performance.

### ISSUE THREAD

**Issue by SemyonSinchenko** [netket/netket#173]
I want to thank you for this beautiful library and ask some questions.

What does the following warning means?

> [[63177,1],0]: A high-performance Open MPI point-to-point messaging module
> was unable to find any relevant network interfaces:
> 
> Module: OpenFabrics (openib)
>   Host: main-non-gpu
> 
> Another transport will be used instead, although this may result in
> lower performance.
> 
> NOTE: You can disable this warning by setting the MCA parameter
> btl_base_warn_component_unused to 0.

I try to fit the 1d Heisnberg RBM (like in the Science 2017 article). My code is [here](https://github.com/SemyonSinchenko/NetKetTests/blob/master/python/src/Heisenberg1d.py) I tried to add the row `from mpi4py import MPI` (like in the [tutorial](https://www.netket.org/tutorials/j1j2/)) but it didn't help. Also I see that in my Google Cloud instance with 24 cores only one core is using. Is it OK? And can anyone explain what does this row `from mpi4py import MPI` in the tutorial do?

Versions:
cycler==0.10.0
kiwisolver==1.0.1
matplotlib==3.0.3
mpi4py==3.0.1
netket==2.0b2
numpy==1.16.2
pandas==0.24.1
patsy==0.5.1
pkg-resources==0.0.0
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0
statsmodels==0.9.0
tqdm==4.31.1

Python version 3.6.7

Many thanks in advance!

**Comment by gcarleo** [comment]
Hi @SemyonSinchenko , thanks! To run it in parallel you need to do mpirun -n N_cores_you_want_to_use python your_pyhon_script.py 

This means that we should add this in the tutorials... Also, notice that you don't need mpi4py, but just a working mpi compiler, we also need to remove that line from the tutorials

**Comment by fabienalet** [comment]
Hi @gcarleo 
I've (very slightly) improved the J1-J2 and CustomHamiltonian. They can be found [here](https://github.com/fabienalet/netket/tree/tutorials/Tutorials). I'm not doing a PR yet as I haven't finished another tutorial (currently in progress), but this might be useful though.

**Comment by gcarleo** [comment]
Thanks @fabienalet , those are really nice, looking forward to the PR then!

**Comment by SemyonSinchenko** [comment]
@gcarleo Thank you! Now It works! I'm sorry for my noob question I'm not familiar with Open MPI and didn't work with it before.
