### ISSUE TITLE
Bug in hilbert space indexing with MPI

### ISSUE THREAD

**Issue by jwnys** [netket/netket#1734]
I'm getting an error when trying to take vs.to_array() with the new Hilbert indexing. If I take a spinless fermionic hilbert space with fixed number of fermions, I get:
```python
v0 = vs.to_array(normalize=False)
    xs = hilbert.numbers_to_states(states_per_rank[mpi.rank])

  File "xxx/netket/vqs/mc/mc_state/state.py", line 690, in to_array

  File "xxx//netket/hilbert/discrete_hilbert.py", line 154, in numbers_to_states
    return nn.to_array(

  File "xxx/netket/nn/utils.py", line 123, in to_array

    xs = hilbert.numbers_to_states(states_per_rank[mpi.rank])

    raise ValueError("numbers outside the range of allowed states")

ValueError: numbers outside the range of allowed states
```
only when using MPI.

**Comment by PhilipVinc** [comment]
Please provide a reproducer

**Comment by PhilipVinc** [comment]
@jwnys Do you have more info about this? It's unclear to me in what context you get the bug.  What code.

**Comment by PhilipVinc** [comment]
Is there a reproducer?

**Comment by jwnys** [comment]
This occurred exclusively with lots of (order 1k) mpi ranks. I haven't been able to reproduce the error recently. We can close it, and when I encounter it again, I'll make a reproducer.
