### ISSUE TITLE
TDVP not implemented for Squared LocalLiouvillian operators

### ISSUE THREAD

**Issue by simonchenyf** [netket/netket#1758]
Hi,

I was trying to run TDVP for the Square of a LocalLiouvillian but found it not applicable. Will this feature be supported in the future?

The main obstacles are in
- the `collect` method called in line 98 of tdvp_common.py `op = operator.collect()`, and 
- line 660 through 663 of mc_state/state.py

```python
>         if isinstance(O, Squared):
>             raise NotImplementedError(
>                 "expect_and_forces not yet implemented for `Squared`"
>             )
```

By commenting out these lines I am able to run TDVP, but I am not sure if this gives the correct result or not.

**Comment by simonchenyf** [comment]
A repro:

> import netket as nk
> import netket.experimental as nkx
> from netket.operator.spin import (
>     sigmax as sx,
>     sigmaz as sz,
>     sigmam as sm,
> )
> from netket.operator import Squared
> 
> N = 40
> 
> hi0 = nk.hilbert.Spin(s=1/2, N=N)
> hi = nk.hilbert.DoubledHilbert(hi0)
> 
> g = 1.
> V = 1.
> gamma = 1.
> 
> H = sum([g * sx(hi0, i) for i in range(N)])
> H += sum([V * sz(hi0, i) * sz(hi0, i+1) for i in range(N-1)])
> L = nk.operator.LocalLiouvillian(ham=H, jump_ops=[gamma * sm(hi0, i) for i in range(N)])
> 
> sampler = nk.sampler.MetropolisLocal(hi)
> 
> vstate = nk.vqs.MCMixedState(sampler, model=nk.models.NDM(beta=1), 
>                             n_samples=2000, n_samples_diag=500)
> 
> LdL = Squared(L)
> 
> evo = nkx.TDVP(LdL, vstate, nkx.dynamics.Heun(dt=0.01))

and my netket version is 3.11.2

**Comment by simonchenyf** [comment]
For reproduction of the problem:

> import netket as nk
> import netket.experimental as nkx
> 
> from netket.operator.spin import (
>     sigmax as sx,
>     sigmam as sm,
> )
> 
> from netket.operator import Squared
> 
> N = 10
> 
> hi0 = nk.hilbert.Spin(s=1/2, N=N)
> hi = nk.hilbert.DoubledHilbert(hi0)
> 
> g = 1.
> gamma = 1.
> 
> H = sum([g * sx(hi0, i) for i in range(N)])
> L = nk.operator.LocalLiouvillian(ham=H, jump_ops=[gamma * sm(hi0, i) for i in range(N)])
> 
> sampler = nk.sampler.MetropolisLocal(hi)
> 
> vstate = nk.vqs.MCMixedState(sampler, model=nk.models.NDM(beta=1), 
>                             n_samples=2000, n_samples_diag=500)
> 
> LdL = Squared(L)
> 
> evo = nkx.TDVP(LdL, vstate, nkx.dynamics.Heun(dt=0.01))

My netket version is 3.11.2

**Comment by PhilipVinc** [comment]
The method that is missing is `Squared(L).collect()`, which is not implemented. 
This would be supposed to put `LdagL` back in a Liouvillian-like form.

By the way, even if this is not implemented you could try to do it by hand by finding yourself how to rewrite a LdagL as a Liouvillian and then just building `nk.operator.LocalLiouvillian` with a proper hamiltonian and some weird jump operators. I'm not sure if it's possible but maybe it is.

Regardless, however, I wonder why you want to do the dynamics of LdagL? 
This is highly non physical and would converge more slowly, and would be quadratically more expensive...

**Comment by PhilipVinc** [comment]
>Will this feature be supported in the future?

We implement algorithms that are at least on the arxiv. The algorithm you proposed has not been discussed by anyone in the literature.

> By commenting out these lines I am able to run TDVP, but I am not sure if this gives the correct result or not.

It's most likely not what you want. The gradient of LdagL is computed using the formulas given in my 2019 PRL. They are not the _variational forces_ that are usually needed to do TDVP.

**Comment by PhilipVinc** [comment]
This has never been published in a scientific paper, so it's not planned at the moment.
