### ISSUE TITLE
Issue with shapes when using parallel tempering sampler on MPI

### ISSUE THREAD

**Issue by lindamauron** [netket/netket#1763]
Hello, 
I have encountered a bug when using Pt samplers on MPI. The following code : 
```python
N = 3
hi = nk.hilbert.Spin(1/2,N)

n_chains = 24
ma = nk.models.Jastrow()
sa = nkx.sampler.MetropolisLocalPt(hi, n_chains=n_chains, sweep_size=10*N, n_replicas=32)
vs = nk.vqs.MCState(sa,ma,n_samples_per_rank=1500, n_discard_per_chain=500)

vs.sample()
``` 
works perfectly fine when called on one rank. However, when using multiple ranks (here 12), it gives the following errors : 
```shell
  File "/Users/lindamauron/environments/csqs/lib/python3.11/site-packages/netket/experimental/sampler/metropolis_pt.py", line 221, in loop_body
    beta.reshape((-1,)) * (proposal_log_prob - s["log_prob"])
(...)
TypeError: mul got incompatible shapes for broadcasting: (768,), (64,).
``` 

I think this is due to the usage of `n_chains` instead of `n_chains_per_rank` in general inside the Pt sampler. See the declaration of beta in `MetropolisPtSampler._init_state` : 
```python 
beta = 1.0 - jnp.arange(sampler.n_replicas) / sampler.n_replicas
beta = jnp.tile(beta, (sampler.n_chains, 1))
```

**Comment by PhilipVinc** [comment]
I think it's easier. There's `n_batches` for that that is already correctly defined.

We must have missed renaming that line from
```python
            n_accepted_per_beta = s["n_accepted_per_beta"] + do_accept.reshape(
                (sampler.n_chains, sampler.n_replicas)
            )
```

```python
            n_accepted_per_beta = s["n_accepted_per_beta"] + do_accept.reshape(
                (sampler.n_batches, sampler.n_replicas)
            )
```

There might be other places where we missed this. @lindamauron  Would you care for opening a PR with this fix?


Ps: As you are using the Tempering sampler, which I never understood 100% if it works or not because the tests do not pass... Do you find issues? Does it work correctly?

**Comment by lindamauron** [comment]
I think the `n_batches` had to be adapted because each usual chain possesses `n_replicas` chains (one for each temperature).

**Comment by PhilipVinc** [comment]
@lindamauron As for tests, you can drop this file in the test/sampler folder to get some tests that run in MPI (sampler tests are disabled under MPI at the moment, so we need a different file). Feel free to add more tests.

This one, currently, fails.

https://gist.github.com/PhilipVinc/cc2f65b6bbb452c95180e20071fdf335
