### ISSUE TITLE
Generalized Hartree fock

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#1764]
For spinful fermions, `Slater2nd` implements a product of determinants for each spin component. For example for spin 1/2 it gives 

$$ \psi(n)=\mathrm{Det}(\phi^{d}_i(r^{d}_j) ) \times \mathrm{Det} (\phi^{u}_i(r^{u}_j) ) $$

where $r^{u}_j$ are the position of up particles and $r^{d}_j$ of down particles. 

The `restricted=True` flag sets : 

$$ \phi^d=\phi^u $$

Thus for the unrestricted case one would have a total of N_fermions X N_sites parameters. 

Now, the problem is that the true unrestricted determinant is 

$$ \psi(n)=\mathrm{Det}(\phi_i(r_j) )  $$

where now we have 2 X N_sites X N_fermions parameters. 

It would be nice if the flag restricted=False actually implemented this and not that form of unrestricted determinant that is not what is commonly associated to unrestricted HF. It should be enough to just define a larger matrix, of size (N_orbitals X N_spin_species, N_fermions) as if we were dealing with spinless fermions.

**Comment by jwnys** [comment]
I don't fully understand what you want:
- do you want the full matrix with a single determinant (to me this doesn't make that much sense if the Hamiltonian is spin independent and if the fermions have spin quantum numbers). Having 0 off diagonal blocks simply indicate that the fermions cannot occupy orbitals of the opposite spin (which I think makes sense).
- or do you mean something else?

**Comment by gcarleo** [comment]
the first one, namely you can mix up and down spin orbitals, that's what unrestricted HF is (and yes, it makes sense)

**Comment by jwnys** [comment]
Hm, maybe we have a different definition of UHF then, but to my knowledge UHF orbitals still have **definite spin**, just a different spatial orbital part per spin (this is also the convention of UHF of PySCF for example). The 'mixing' people refer to is not mixing of \alpha electrons in \beta orbitals, but rather the fact that singlets and triplets tend to mix. So in principle the number of modes here is 2 * n_sites, where they also have a spin index. You can still only occupy the n_per_subsector[0] fermions of type \alpha only in the first n_sites modes, so you'll always get 0 off diagonal blocks.

**Comment by gcarleo** [comment]
ok so I think the naming is actually fine, what I wanted/referred to is the **generalized hartree fock**, and could be implemented quite easily adding a further flag to Slater2nd ...
