### ISSUE TITLE
Bug in MinSR code

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#1794]
If we don't supply the mean energy to the `SRt` function, it tries to generate it by calling `mpi.mean`

https://github.com/netket/netket/blob/15ffdec738e3af51b9e119e7c4333b96622da9e1/netket/experimental/driver/vmc_srt.py#L52-L54

which doesn't exist. Could we please fix this? Which of `mpi_mean` and `mpi_mean_jax` should be used here? 

(This doesn't affect the driver as currently written, but can mess with other applications.)

**Comment by PhilipVinc** [comment]
Good point.
It should be `nk.stats.mean`
