### ISSUE TITLE
Updating the installation documentation

### ISSUE THREAD

**Issue by Exferro** [netket/netket#1807]
Hey guys, I am starting to learn NetKet, and my first hiccup happened shortly after the installation. I tried to follow [the Commented Example on the installation page](https://netket.readthedocs.io/en/latest/docs/install.html#commented-example) and failed. 

In particular, it doesn't let me to pass `n_samples` and `n_discard_per_chain` to the constructor of `VMC`. After reading other tutorials, it seems that there was a change of NetKet API, and now one first fuses a model and a sampler into an `MCState`, and only then passes it to `VMC`.

If the change is indeed that minimal, I can make a pull request, would that be okay?

Thanks!

**Comment by gcarleo** [comment]
yes good catch ! it would be nice if you could do a small PR to the documentation yes please !
