### ISSUE TITLE
Flax ConvNet with double precision (float64) slows down QGTJacobianDense

### ISSUE THREAD

**Issue by MarcMachaczek** [netket/netket#1870]
I wanted to define a custom NQS using a flax convolutional layer. I configured it in a way to behave similar to the built-in GCNN (only using translational symmetries) to compare performance and noticed that training the custom flax CNN took way longer.
In short, I noticed (minimal example below) that using a flax conv layer with double precision in combination with a QGTJacobianDense takes almost a minute to run the optimization below. On the other hand, using either float32 as param_dtype or QGTOnTheFly performs the below optimization in a few seconds. 

I observed the same behaviour using larger system sizes and networks. However, in this case using just a simple dense layer does not reproduce this issue. Maybe this is related to [https://github.com/netket/netket/issues/1153](url)?

```
import netket as nk
import jax.numpy as jnp
import jax
import flax

from typing import Optional, Any


class TestNet(flax.linen.Module):
    features: int
    kernel_size: int
    param_dtype: Any = jnp.float64
    precision: Optional[jax.lax.Precision] = None

    def setup(self):
        self.conv_layer = flax.linen.Conv(features=self.features,
                                          kernel_size=self.kernel_size,
                                          param_dtype=self.param_dtype,
                                          precision=self.precision
                                          )

        self.dense_layer = flax.linen.Dense(features=self.features,
                                            param_dtype=self.param_dtype,
                                            precision=self.precision)

    def __call__(self, x: jax.Array) -> jax.Array:
        x = jnp.expand_dims(x, axis=-1)
        x = self.conv_layer(x)
        x = jax.scipy.special.logsumexp(x, axis=(-2, -1))
        # x = self.dense_layer(x)
        # x = jax.scipy.special.logsumexp(x, axis=-1)
        return x


L = 4
lattice = nk.graph.Hypercube(length=L, n_dim=2, pbc=True)

hilbert = nk.hilbert.Spin(s=1 / 2, N=lattice.n_nodes, total_sz=0)

hamiltonian = nk.operator.Heisenberg(hilbert=hilbert, graph=lattice, J=1.0)

# RBM Spin Machine
model = TestNet(
    features=4,
    kernel_size=3,
)

update_rule = nk.sampler.rules.ExchangeRule(clusters=lattice.edges())
sampler = nk.sampler.MetropolisSampler(hilbert=hilbert,
                                       rule=update_rule,
                                       n_chains=32,
                                       dtype=jnp.int8)

# Optimizer
op = nk.optimizer.Sgd(learning_rate=0.01)

# SR
preconditioner = nk.optimizer.SR(qgt=nk.optimizer.qgt.QGTJacobianDense,
                                 diag_shift=1e-3,
                                 holomorphic=False)

# Variational state
vqs = nk.vqs.MCState(sampler, model, n_samples=1024, n_discard_per_chain=20)

# Variational monte carlo driver with a variational state
gs = nk.VMC(hamiltonian, op, variational_state=vqs, preconditioner=preconditioner)

# Run the optimization for 300 iterations
gs.run(n_iter=30, out=None)
```

**Comment by PhilipVinc** [comment]
cc @wdphy16, @inailuig  (do you know?) 

There are multiple possibilities, what version of cudnn are you using? what gpu model?
one possibility is that the implementation that jax is using for the backward pass that comes from CUDNN is not implemented for double precision. As jacobian and onthefly will be using different implementations, maybe some are not there fore single precision...
One way to check would be to check what implementation XLA ends up using.

In any case, I 



FYI: If you set the environment variable `NETKET_USE_X64=0` before importing netket we will disable double precision alltogether...

**Comment by MarcMachaczek** [comment]
I'm using the following versions:
netket==3.12.0
jax==0.4.28
flax==0.8.3

This is running on CPU only (tested on my mac). Is it possible that this causes the issue?
I will double check how this behaves on the cluster.

**Comment by PhilipVinc** [comment]
Can you check if you still see that on linux?

**Comment by MarcMachaczek** [comment]
After testing on the cluster (ofc running on linux) with an A100 GPU, the time difference is not noticable anymore. I used more samples (4096) on a larger system size (L=8) with more features etc. so things take a bit more time to make a proper comparison) So indeed it seems like a backend issue.
Also, like you said it must be something specific to the jax.lax.conv mapping.
Using the below model (which afaik should perform pretty much the same operation with a fully connected kernel) works without any issues even if param_dtype=jnp.float64.
```
realGCNN = nk.models.GCNN(symmetries=lattice.translation_group(),
                          layers=1,
                          features=4,
                          param_dtype=jnp.float64,
                          )
```
