### ISSUE TITLE
API changes after removing stored Graph from Hilbert

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#188]
Since we are still in beta, I believe it is a good time to discuss some possible changes to the APIs. 

Here is one issue that has emerged discussing with @PhilipVinc : for future developments it would be important to have more flexible `Hilbert` objects, that are not necessarily bound to a `Graph`. These objects would naturally allow for example to define heterogeneous hilbert spaces (say an ensemble of spins and bosons, of spins and fermions etc), and also perform product of two or more Hilbert spaces automatically.

For example one could do   
```python
n_spins=10
n_bosons=10
n_sites_bosons=12

hi = nk.hilbert.Spin(s=0.5,n_spins)*nk.hilbert.Boson(n_sites_bosons,n_bosons) 
```

or just double the hilbert space, when considering density matrices 

```python
n_spins=10

# doubled hilbert space for density matrices 
hi = nk.hilbert.Spin(s=0.5,n_spins)*nk.hilbert.Spin(s=0.5,n_spins)
```

In general it is cumbersome to carry along the `Graph` object inside `Hilbert`, since strictly speaking the only thing `Hilbert` needs to know is the number of sites and the local quantum numbers, not the structure of the edges etc. 

In practice this means that the `Graph` object now stored in `Hilbert` should be removed. As a consequence, a few classes now deducing `Graph` from `Hilbert` should accept `Graph` in the constructor. For example  

```python
# Ising spin hamiltonian 
ha = nk.operator.Ising(h=3.0, hilbert=hi)
```

would become

```python
ha = nk.operator.Ising(h=3.0, hilbert=hi,graph=g)
```

and similarly for `RbmSpinSymm`. 

For `Hamiltonians`-like objects, it might make sense also to just do 
```python
ha = nk.operator.Ising(h=3.0, graph=g)
```
and then ask `ha` to compute/return the `Hilbert` space when needed (since `Ising` in this case also defines the local hilbert space, so strictly speaking we don't need to pass it in the constructor). 

I believe that these interface changes are not a huge problem, but I wanted to have some comments before doing these breaking changes.

**Comment by femtobit** [comment]
These are indeed good points, @gcarleo, and I agree that it makes a lot of sense to decouple the Hilbert space from the graph structure.

I am wondering, however, how we would handle heterogeneous Hilbert spaces (i.e., `Spin(1/2) * Boson(...)` in relation to the graph structure. How do we express a model where there is one bosonic mode and a spin at each site or a model where we have a lattice of spins that all couple to the same bosonic mode? Can we do it in a general way? (It seems we have both a case where we have one graph with a heterogeneous Hilbert space at each site and a case where the graph structure of one part of the system is not related to the structure of the other part.)

**Comment by gcarleo** [comment]
Good point @femtobit . The thing is that, strictly speaking, a `Hilbert` object defines only a set of vertices, not a set of edges. The edges themselves are determined by the hamiltonian or any other operator that acts on the hilbert space. So, strictly speaking, it is the hamiltonian and other of these objects that would need to carry the graph information... In your example, the difference between the two cases you write would be given by the different implementation of the two hamiltonians. 

Ideally we would need a good strategy to keep some "connection" between hilbert and graph, passing for an intermediate, more primitive object that stores only the vertices of the graph and not also the edges.

**Comment by gcarleo** [comment]
Here is my proposal: 

we keep the interface unchanged, i.e. it will be possible to do:
```python
# 1D Lattice
g = nk.graph.Hypercube(length=20, n_dim=1, pbc=True)

# Hilbert space of spins on the graph
hi = nk.hilbert.Spin(s=0.5, graph=g)

# Ising spin hamiltonian
ha = nk.operator.Ising(h=1.0, hilbert=hi)
```
as always. 
However, we also have: 

```python
N=20
hi = nk.hilbert.Spin(s=0.5)**N 

assert(hi.graph==null)
hi.graph=nk.graph.Hypercube(length=hi.size, n_dim=1, pbc=True)
#here at assignment time it is checked that the number of nodes is compatible

# Ising spin hamiltonian
ha = nk.operator.Ising(h=1.0, hilbert=hi)
```

so, basically, internally the member `graph` in hilbert is not explicitly assigned by default. The only thing that is known is the number of nodes i.e. `hilbert.size`. 

When a tensor product of two hilbert space is done, if both states have a graph assigned, the resulting graph will be by default the union of the two graphs (we can discuss about this...). If either of the two internal graph is null, then the resulting graph is null. 

The advantage of this strategy is that we don't change the current usage, but we allow for more flexible and advanced manipulations of hilbert spaces. 

@PhilipVinc @femtobit @kchoo1118 etc your thoughts about this?

**Comment by PhilipVinc** [comment]
> I am wondering, however, how we would handle heterogeneous Hilbert spaces (e.g., Spin(1/2) * Boson(...)) in relation to the graph structure. How do we express a model where there is one bosonic mode and a spin at each site or a model where we have a lattice of spins that all couple to the same bosonic mode?

 As long as we are able to keep the the list of local Hilbert spaces and the list of vertices in sync (i.e. both are vectors indexed in the same order), I don't see any problem... do you agree?

With this need to keep both the vertices and the local Hilbert spaces indexed according to the same order, issues might arise when building the graph/space for non-homogeneous spaces. Maybe we should reason about the API for this?

> When a tensor product of two hilbert space is done, if both states have a graph assigned, the resulting graph will be by default the union of the two graphs

Why this behaviour? And then, what about the symmetries of the resulting graph? If you are still thinking about doubled Hilbert space for Open Quantum Systems, then I don't think the symmetries are not that of the union of the two graphs.

--
The idea is not bad, but it introduces some sort of `hidden state` in the Hilbert space which I'm not sure about.

**Comment by gcarleo** [comment]
> As long as we are able to keep the the list of local Hilbert spaces and the list of vertices in sync (i.e. both are vectors indexed in the same order), I don't see any problem... do you agree?

yes, this is the crucial point, but I believe it can be done... Basically if we have setters and getters for the `Graph` contained in the `Hilbert`, then every time you set or get it you can check that the graph is consistent with `Hilbert`, otherwise you have a runtime error. Basically the getter should return a const reference then. 

> Why this behaviour? And then, what about the symmetries of the resulting graph? If you are still thinking about doubled Hilbert space for Open Quantum Systems, then I don't think the symmetries are not that of the union of the two graphs.

Well, strictly speaking the graph must be the union of the two graphs. But it's a bit of a problematic situation anyways... maybe the best thing is just to set the resulting graph to an undefined value, then it's up to the user to specify the correct symmetries etc... 

This solution, overall, can be implemented without too much pain. The problem is generalizing the object inside `Hilbert` that generates the local states, to the case where you have a locally varying number of states, as we were discussing already...

**Comment by PhilipVinc** [comment]
> yes, this is the crucial point, but I believe it can be done... Basically if we have setters and getters for the Graph contained in the Hilbert, then every time you set or get it you can check that the graph is consistent with Hilbert

That's not what I meant. Of course the *fake* `Graph` object inside `Hilbert` must be in sync with his parent, but that's easy to accomplish as you describe. 
What about the real `Graph` object? What guarantees that when you call
```
ha  = nk.operator.Ising(h=3.0, hilbert=hi,graph=g)
net = nk.machines.rbmsymm(graph=g, hilbert=hi, ....)
```
 `hilbert` and `graph` are indeed ordered in the same way? We would rely on the user to be careful enough when creating the two separate objects so that the order of vertices and local spaces is in sync.

**Comment by gcarleo** [comment]
But the thing is that 
```python
net = nk.machines.rbmsymm(graph=g, hilbert=hi, ....)
```
should not happen? I would do  
```python
hi=nk.hilbert.Spin(1//2)**N 
hi.graph=g 
net = nk.machines.rbmsymm(hilbert=hi, ....)
```
for hilbert spaces constructed as a product of local hilberts, 
or this if hilbert is constructed directly on a graph

```python
hi = some_hilbert(graph=g,...) 
net = nk.machines.rbmsymm(hilbert=hi, ....)
```

sure, in the first case there is no control that the graph you are assigning to hilbert has the same ordering (you would only check that number of edges is the same, when doing `hi.graph=g`, but this should be good enough?) 

In the case of the density matrix, we really need to define some meaningful operation on the graph that results from doubling the hilbert space, but that is independent of the APIs of hilbert we are discussing here, I believe...

**Comment by gcarleo** [comment]
http://qutip.org/docs/latest/guide/guide-tensor.html#superoperators-and-tensor-manipulations can we do something like `to_super` ? this seems neat

**Comment by PhilipVinc** [comment]
Sorry for the delay, I went completely AFK for holidays...

>so, basically, internally the member graph in hilbert is not explicitly assigned by default. The only thing that is known is the number of nodes i.e. hilbert.size.

I understand what you mean. Basically you propose keeping the current behavior, and just changing the way we construct Hilbert spaces. 
This is not different from assuming that the default graph of any Hilbert space is a graph with no edges and N sites. Why don't we just do that?

Slightly related: for an heterogeneous system like N spins with NN couplings and all coupled to a bosonic mode, you would do something along the lines of ...?
```python
hi = nk.hilbert.Spin(s=0.5,n_spins)*nk.hilbert.Boson(n_cutoff)
graph =  nk.graph.Hypercube(length=n_spins, n_dim=1, pbc=False)
graph.add_site() # add site at index n_spins
for i in range(n_spins):
    graph.add_edge(i, n_spins) #add all to boson mode connections
hi.graph = graph
```

**Comment by PhilipVinc** [comment]
Regarding `to_super`: I'm not sure what you mean.

In QuTip, `SuperOperators` are different objects than operators. They re-implement multiplication so that SuperOp-SuperOp multiplication and SuperOp-Operator are the only two defined operations (which internally perform a matrix-matrix and matrix-vector operation respectively). This is to prevent the user from doing SuperOp-Ket products, for example. 

This goes somewhat in the opposite direction of what we had discussed, namely having the Lindbladian behave like a standard linear operator (with custom rules) and the density matrix be a generic Machine on a doubled space.

**Comment by gcarleo** [comment]
> I understand what you mean. Basically you propose keeping the current behavior, and just changing the way we construct Hilbert spaces.

Yes exactly, and that's how I implemented it now in the PR 

> This is not different from assuming that the default graph of any Hilbert space is a graph with no edges and N sites. Why don't we just do that?

We could do that... actually it's maybe an even better solution. But then again, what do you do when you double/multiply the Hilbert space, what edges do you keep and what do you discard?

**Comment by gcarleo** [comment]
The other problem I see is that graphs are now basically static objects, they are not meant to be grown dynamically... for example if you have a `Lattice` it doesn't make too much sense to add a new dangling edge, unless you go from a `Lattice` to some more general lattice, but loosing specific methods and functionalities that you have for a `Lattice`... Also, automorphisms are a pain

**Comment by PhilipVinc** [comment]
>We could do that... actually it's maybe an even better solution. But then again, what do you do when you double/multiply the Hilbert space, what edges do you keep and what do you discard?

With respect to the doubling of the graph to obtain the doubled space where operators live, you literally consider the graph two times (you have two disjoint subgraphs).

**Comment by PhilipVinc** [comment]
>for example if you have a Lattice it doesn't make too much sense to add a new dangling edge

I agree, but how do you compose the system I was talking about in the example then? You could make it so that `Lattice.add_vertice()` convert the Lattice object to a `CustomGraph` object and then adds a site to it (which should be relatively easy to implement I believe?).

Automorphisms are indeed a pain, though.

**Comment by PhilipVinc** [comment]
@gcarleo we can close this
