### ISSUE TITLE
New jax rng key breaks VQS serialization with flax

### ISSUE THREAD

**Issue by MarcMachaczek** [netket/netket#1881]
While trying to serialize a vqs I noticed that `flax.serialization.to_bytes(state_dict)`, where in my case `state_dict = flax.serialization.to_state_dict(vqs)`, throws the following error: 
`ValueError: Object and structured dtypes not supported for serialization of ndarrays.`

I narrowed it down to the "rng" entry of "sampler state", removing it or overwriting it with None, for instance, solved the issue.
I believe the reason is that the new jax rng keys created by `jax.random.key(seed)` are no longer just uint arrays but of some random_key type.

I worked around that by simply setting this entry to None and manually setting the key back when de-serializing it.
I don't know if there is an easy fix, but maybe this info helps someone.

**Comment by PhilipVinc** [comment]
Ah nice catch!

I think the solution is to use Jax.random.key_data() and jax.random.wrap_key_data() in the functions that serialize and deserialise SamplerState.

those are the two functions here for example, for Metropolis Sampler 

https://github.com/netket/netket/blob/0b2e9e467003e407649eeb360aaa4894f025c65f/netket/sampler/metropolis.py#L123

The dictionary ‘state_dict’ is what is serialised and should only contain Jax or jumpy arrays. You can simply unwrap the ‘rng’ entry and then to the opposite in the deserialistion method.


See https://jax.readthedocs.io/en/latest/jax.random.html

happy to take a PR about this!

**Comment by MarcMachaczek** [comment]
I'd be happy to look into this, but it will have to wait until next week. Best, Marc
