### ISSUE TITLE
Improper chunking of Jax Operators's connected elements

### ISSUE THREAD

**Issue by chrisrothUT** [netket/netket#1937]
I'm finding some extremely strange behavior with vstate.expect. 

```python
import netket as nk
import netket.experimental as nkx
import flax
import jax
import jax.numpy as jnp

n_samples = 16
chunk_size = 4
U = 0.1

graph = nk.graph.Triangular([12,12])
N = graph.n_nodes
hi = nkx.hilbert.SpinOrbitalFermions(N, s = 1/2, n_fermions_per_spin = (N//2,N//2))
samp_graph = nk.graph.disjoint_union(graph, graph)
sa = nk.sampler.MetropolisExchange(hilbert=hi,n_chains=n_samples,graph=samp_graph,d_max=1,chunk_size=chunk_size)

class Model(flax.linen.Module):
  @flax.linen.compact
  def __call__(self,x):
    print(x.shape)
    return nk.models.RBM()(x)

ma = Model()

terms = []
weights = []

for edge in graph.edges():
  terms.append(((edge[0],1),(edge[1],0)))
  weights.append(1)
  terms.append(((edge[1],1),(edge[0],0)))
  weights.append(1)
  terms.append(((N + edge[0],1),(N + edge[1],0)))
  weights.append(1)
  terms.append(((N + edge[1],1),(N + edge[0],0)))
  weights.append(1)

for node in graph.nodes():
  terms.append(((node,1),(node,0),(node+N,1),(node+N,0)))
  weights.append(U)

ha = nkx.operator.FermionOperator2ndJax(hi,terms,weights)

vstate = nk.vqs.MCState(sampler=sa, model=ma, n_samples=n_samples,n_discard_per_chain=2,chunk_size=chunk_size)
```

When I call vstate.expect(ha) this is the output I get:
```python
(1, 288)
(16, 288)
(4, 288)
(4, 288)
(4, 288)
(1, 288)
(1729, 288)
(1, 288)
(1729, 288)

xp, mels = ha.get_conn_padded(vstate.samples)
print(xp.shape)

(16,1,1729,288) 
```
So it appears that the input is not being chunked properly and instead the model is being applied along all connected elements.

**Comment by PhilipVinc** [comment]
So, I have updated your example (BTW, it's much nicer to post something that runs...)

Anyhow, sampling does chunk
```python
In [5]: vstate.samples
(4, 288)
(4, 288)
(4, 288)
(4, 288)
(4, 288)
(4, 288)
(4, 288)
(4, 288)
```

it is the local estimator calculation that does not chunk
```oython
In [6]: vstate.local_estimators(ha)
(1, 288)
(1729, 288)
(1, 288)
(1729, 288)
```
and expect as well.
```python
In [7]: vstate.expect(ha)
(1, 288)
(1729, 288)
(1, 288)
(1729, 288)
```
if I convert to numba operators I get
```python
In [9]: vstate.local_estimators(ha)
(1, 288)
(1, 288)
(1, 288)
(1, 288)

In [10]: vstate.expect(ha)
(1, 288)
(1, 288)
(1, 288)
(1, 288)
```

which does not clarify whether it is chunking, but I suspect he is.

So, long story short, this might be jax operators not chunking correctly.

**Comment by PhilipVinc** [comment]
it's probably all jax operators, not only femrionic ones.

**Comment by PhilipVinc** [comment]
It's probably because of the laziness of whoever implemented this (I guess me :) )

https://github.com/netket/netket/blob/03e8e1f59c0b667c98d6a94606ad1016735a6e63/netket/vqs/mc/kernels.py#L188

It is chunking, but the actual chunk size used is `max(chunk_size, op.max_conn_size)` .

which is what is happening here.
This can easily be addressed by rewriting this code to chunk both samples and connected entries.

Would you mind contributing a PR?

**Comment by chrisrothUT** [comment]
Ahh yeah I see, yes I can PR this

**Comment by PhilipVinc** [comment]
@inailuig do you have any idea (not too crazy) on how to handle the chunking of the connected elements without instantiating the full array of connected elements? 

It should be possible to scan over the input samples, only computing their connected elements, and computing the amplitudes in chunks of chunk size...

Or maybe the simplest thing is to do a scan over some common divisor of chunk size and n connected?

**Comment by chrisrothUT** [comment]
My plan was to rewrite `local_value_kernel_jax` such that the computation of apply(op) is chunked
