### ISSUE TITLE
Problem with convergence for Ising model

### ISSUE THREAD

**Issue by SemyonSinchenko** [netket/netket#210]
Dear colleges!

I get the problem with plateau on the learning curve when I try to fit the Ising model for short-chain (4-12 spins in the chain) systems.
For example [here](https://raw.githubusercontent.com/SemyonSinchenko/NetKetTests/master/IsingRun/Run_4_1_0.0__folder/FittingCurve.png) is the curve for 4-spins model. Similar curves I get also for chains less than around 12-14 spins. I tried to reproduce the plot like the Fig. 2 from article of Pierre Pfeuty (Annals of physics, 57, 79-90 (1970) for chains of different length and for different combinations of h and J. But I get the results like [that](https://raw.githubusercontent.com/SemyonSinchenko/NetKetTests/master/DifferentNSpins.png) for short chains. From article of Pfeuty I understand that the curve must not be depend from the chain length and I see that is true for Langzos exact diagonalization results. But for fitting results I can not reproduce it. I have some experience in "classical" deep learning (CV, NLP, etc.) and I tried the "standard" tricks for solve the plateau problem: decreasing of the learning rate, playing with decay or momentum parameters, trying different optimizers. But these tricks does not help me solve that problem.

Now I cannot fully understand that problem is in the optimization plane but not in the physics plane or in the plane of NQS model. It is not fully clean for me what is happened with NQS-method for short-chains. It seems that Metropolis-Hastings sampler can "crashed" when we trying to get about 500 samples from Hilbert space with only 16 possible vectors (for chain of length 4) and that can explain for me why with rising of the chain length we get more and more expected results. Another fact that I do not fully understand is what will happened with our formula for local energy estimation (I found it in the G. Carleo lectures "Machine learning methods for many body physics", Lectures for the Advanced School on Quantum Science and Quantum technology, September 8-9 2017, ICTP, Trieste, Italy). How can I understand from articles about NQS and G. Carleo lectures we replace the sum over all Hilbert space by sum over limited part of permutations and I understand that for many-spins chains it is the single possible way because the Hilbert space is immense. But what is happened when all Hilbert space is around 16-1000 possible vectors? May be the problem is here? Another fact that point for this is the Variance curve. It is incomprehensive for me why Variance converge to zero not in the ground state? From physical view it look like we get the state that is very probable but it is not the ground state. It seems that it is impossible.

I am a newbie in this filed and it can help me very much if some one can suggest me what do I wrong. Many thanks in advance!

Code for reproduce the problem:
* main script - [link](https://github.com/SemyonSinchenko/NetKetTests/blob/master/run_ising.py)
* ising model script - [link](https://github.com/SemyonSinchenko/NetKetTests/blob/master/python/src/Ising.py)
* script for save results - [link](https://github.com/SemyonSinchenko/NetKetTests/blob/master/python/src/Report.py)

**Comment by gcarleo** [comment]
@SemyonSinchenko thanks for the detailed report and for sharing your code. Can you try to replicate your results using NetKet though?

**Comment by SemyonSinchenko** [comment]
> @SemyonSinchenko thanks for the detailed report and for sharing your code. Can you try to replicate your results using NetKet though?

@gcarleo Thank you for answer! But I do not fully understand you... That results I get with the latest netket version from pip. All my code is simple python cover on netket...

**Comment by gcarleo** [comment]
Alright sorry, I was confused by the different layers. You are doing a spin 1 Hilbert space, but using the Ising model Hamiltonian that is defined for spin 1/2, this is certainly a problem

**Comment by SemyonSinchenko** [comment]
@gcarleo I am dummy! =(

I looked at the [wiki page](https://en.wikipedia.org/wiki/Ising_model) and see +-1 values... Thank you very much!
