### ISSUE TITLE
Is there a way to add internal links to the docs? 

### ISSUE THREAD

**Issue by twesterhout** [netket/netket#216]
All the documentation generators I'm familiar with have some ways to create internal links between different parts of the docs. E.g. if I want to refer to another function in Sphinx, I can do ```py:func:`some_function` ```. What's the proper way to accomplish that in mydocstring?

**Comment by gcarleo** [comment]
There is not such a functionality yet. We can add it I guess...

**Comment by ooreilly** [comment]
If you know where the docs are for that function, it might be possible to use a markdown link. Example: `[some_function](functions.md#some_function)`.  
I would also recommend including some tool that can check for dead links.

**Comment by twesterhout** [comment]
> If you know where the docs are for that function, it might be possible to use a markdown link. Example: [some_function](functions.md#some_function)

This kind of defeats the purpose of having a tool generate the docs, doesn't it?

@ooreilly how difficult would it be to add such functionality to mydocstring?

**Comment by ooreilly** [comment]
@twesterhout  if you do not not like that solution, let us come up with something better. What should the syntax look like and what should you be able to achieve with it? How do you want dead links to be handled? Or do you prefer to reuse the Sphinx syntax, and if so what features should be supported?
The simplest solution I can think of would be to let the tool parse your custom link and convert it into a markdown link, which would then eventually get converted to html.

Here is one idea. We could use the markdown syntax for a link but leave the label empty. Example : `[](some_function)` which would then get converted into `[some_function](#some_function)` for `some_function` residing in the same module as the docstring containing the reference. Or if the thing that you are referencing is in some other module, then maybe you would write `[](netket.module.class.method)` which would get converted into `[netket.module.class.method](docs/module.md#method)`. If there are multiple things on the same page with the same name, then I believe they are referenced by `#method`, `#method-1`, `#method-2` in the order of apperance, at least that is how it works for github flavored markdown.  If the link is broken, then the documentation generator can emit a warning and render the link as plain-text instead.

**Comment by twesterhout** [comment]
> What should the syntax look like and what should you be able to achieve with it?

Here's a quote from [standardese](https://github.com/foonathan/standardese) docs:
> To link to an entity, use the syntax `[link-text](<> "unique-name")` (a CommonMark link with empty URL and a title of `unique-name`). If you don't want a special `link-text`, this can be shortened to `[unique-name]()` (a CommonMark link with empty URL and the name of an entity as text).
You can also use an URL of the following form `[link-text](standardese://unique-name/ "optional-title")` (a normal CommonMark link with the `standardese://` protocol, the '/' at the end is important).
In either case `standardese` will insert the correct URL by searching for the entity with the given `unique-name`.

Something similar would be nice. It should handle name resolution properly. I.e. if I have an attribute `handle` in a class and a function with the same name, I should get a link to the attribute if I'm documenting something within the class, but still be able to link to the function by writing `module-name.handle`.

>  How do you want dead links to be handled? 

Trying to link to non-existent objects should product a warning when building the docs. As for the actual link, I don't have a preference. Generating an invalid link is perfectly okay, I think.


@ooreilly this is very similar to your suggestion except that link generation is more involved than a simple regex match and replace.
