### ISSUE TITLE
Compilation Issue with Clang 4.0.1 and Json v3.6.0+ on Mac OSX

### ISSUE THREAD

**Issue by jamesETsmith** [netket/netket#228]
This is a semi-solved problem. I wanted to post it so that we have a record of it and so that anyone else with using NetKet on a Mac at least one workaround solution. I had a problem compiling NetKet when using Clang 4.0.1 (from miniconda) on my mac, see the error below:

```
    warning: CMakeBuild: [ 16%] Built target json_project
    [ 32%] Built target pybind11_project
    [ 48%] Built target eigen_project
    [ 50%] Building CXX object CMakeFiles/netket.dir/Sources/pynetket.cc.o
    In file included from /Users/jets/apps/pull_requests/netket/Sources/pynetket.cc:18:
    In file included from /Users/jets/apps/pull_requests/netket/Sources/netket.hpp:21:
    In file included from /Users/jets/apps/pull_requests/netket/Sources/GroundState/ground_state.hpp:23:
    In file included from /Users/jets/apps/pull_requests/netket/Sources/GroundState/imaginary_time.hpp:9:
    In file included from /Users/jets/apps/pull_requests/netket/Sources/Output/json_output_writer.hpp:10:
    In file included from /Users/jets/apps/pull_requests/netket/Sources/Machine/abstract_machine.hpp:24:
    /Users/jets/apps/pull_requests/netket/build/temp.macosx-10.7-x86_64-3.6/External/json/include/nlohmann/json_fwd.hpp:24:23: error: template parameter redefines default argument
    template<typename T = void, typename SFINAE = void>
.
.
.
```

We discovered that this was caused by versions 3.6.0 and 3.6.1 (the latest) versions of the `json` library. If you revert to v3.5.0 then NetKet compiles without issue.

**Comment by twesterhout** [comment]
@jamesETsmith by the way, I can't reproduce that error on a loaner Mac...

**Comment by jamesETsmith** [comment]
Hmm, curious. I will try from a fresh conda env and get back to you

**Comment by gcarleo** [comment]
Here I second @twesterhout's suggestion : I think we should just get rid of the json library... at this point we only use json output to save machines and write log files with simulation outputs. Both things can be (easily?) implemented in pure python (including json dumps if necessary)!

**Comment by twesterhout** [comment]
Can anybody else reproduce this issue? I should give back my loaner Mac, so in a day or two I won't be able to help out with this anymore.
