### ISSUE TITLE
Custom Hamiltonian failure

### ISSUE THREAD

**Issue by artemborin** [netket/netket#25]
The file custom_hamiltonian.py relies on the function json.dump() , which doesn't support complex numbers. Therefore, there is an error when creating the hamiltonian with complex entries.

**Comment by gcarleo** [comment]
Hi @artemborin, the easiest is to extend the standard Json Python library: 

def encode_complex(z):
    if isinstance(z, complex):
        return (z.real, z.imag)
    else:
        type_name = z.__class__.__name__
        raise TypeError(
            f"Object of type '{type_name}' is not JSON serializable")

and then dump with 

json_file = "input.json"
with open(json_file, 'w') as outfile:
    json.dump(pars, outfile, default=encode_complex)

**Comment by alidiak** [comment]
Implementing the encode_complex function let me create the json input file, but when trying to execute the file with NetKet, the following error appears: 
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be array, but is number 
The complex operator is just sigmay and I have also tried to just enter it as [[0, [-0.0, -1.0]], [[0.0, 1.0], 0]]. I am using version 1.0.5, perhaps this is not an issue with 2.0, but all of the scripts I use are in the previous formats.
