### ISSUE TITLE
Non-physical energies in Vmc

### ISSUE THREAD

**Issue by sindhura97** [netket/netket#252]
Hi, I am trying to learn RBM parameters for a ground state wave function using VMC. I am getting energies below ground state energy. Is this a bug/error in energy computations?

**Comment by gcarleo** [comment]
Vmc uses a stochastic sampling, thus as a result of statistical fluctuations the average energy can be lower than the exact one. The crucial thing is that the average energy carries an error bar, thus fluctuations within that error bar are completely normal and expected. If the fluctuation is significantly larger than the error bar, than it means that the sampling you are doing is not ergodic/ has some other issue.
