### ISSUE TITLE
Support for GPU

### ISSUE THREAD

**Issue by jhrmnn** [netket/netket#282]
Awesome package, if only all science had this kind of approach to software.

Are there any short- or long-terms plans to support evaluation/training on GPUs?

**Comment by jhrmnn** [comment]
I have just noticed https://github.com/netket/netket/projects/1, which mostly answers my question.

**Comment by gcarleo** [comment]
Thank you @jhrmnn for your kind words, we appreciate that! 
Yes, indeed we have been working hard to include support for PyTorch and other GPU enabled software. At the moment we already support JAX in the 2.1 branch, however to see substantial benefit from it you'd need to use rather large networks/batch sizes. With PyTorch we are trying to implement everything in C++, thus it should be faster also on mid-sized networks...
