### ISSUE TITLE
Adding inexact time evolution for neural quantum states

### ISSUE THREAD

**Issue by emprice** [netket/netket#289]
Big fan of this project, and the paper(s) that have inspired it! This is less an issue than a question. If I understand correctly, the original Carleo & Troyer (2017) Science paper goes into some detail about doing time evolution on a neural network state. I've had some trouble implementing this on my own, however, to replicate the results of that paper. I'd love to see that functionality added to NetKet, but I know that may not be in the works. If not, perhaps I could talk to one of the authors (who seem to be the drivers of this project) about how the time evolution was implemented for their paper. I am interested in building on the method for a research project.

**Comment by gcarleo** [comment]
Hi @emprice , thanks for your interest! This is in the making, it will be one of the features to appear in 2.1, later this year (https://github.com/netket/netket/milestone/1). We also have plans to implement the algorithm for the density-matrix dynamics (see https://github.com/netket/netket/projects/3) . Stay tuned!

**Comment by ericntunctu** [comment]
Hi, is there a tutorial for the time evolution example? I want to see the weight in the machine changing with the time evolution.
