### ISSUE TITLE
2.1: Change options names in sr 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#296]
In 2.1 we should change options in the `sr` driver to 
```python
sr.store_rank = True
sr.store_covariance_matrix = True
```

**Comment by femtobit** [comment]
In PySR, these options are now obsolete as rank and S matrix are always stored when available. As far as I can see, there is no overhead from doing that at the moment, so we can do without the options.

If at some point a solver option is added where it makes a performance difference, re-adding those options in some v3 release would not be a problem.

So I think this can be closed now.

**Comment by gcarleo** [comment]
Agreed
