### ISSUE TITLE
netket build failure on CentOS-7 linux system

### ISSUE THREAD

**Issue by toddpfaff** [netket/netket#303]
I'm attempting to install netket on a CentOS-7 linux system.

[root@phys-ugrad netket-2.0]# c++ --version
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I believe I have all the documented dependencies satisfied but the build is failing as shown in the attached file.
[netket-build-log.txt](https://github.com/netket/netket/files/3691379/netket-build-log.txt)

**Comment by gcarleo** [comment]
@toddpfaff the log file seems truncated, at the beginning there should something like 
```
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
```
it would be important to know what compiler you are using to build, thanks

**Comment by toddpfaff** [comment]
compiler info added to original issue post above.

**Comment by gcarleo** [comment]
you are using gcc 4.8.5, but that's too old, you should upgrade your compiler to at least gcc>5, otherwise support for c++11 and other things was still experimental

**Comment by toddpfaff** [comment]
Sorry, I must have missed that depedency in the documentation.

Will try that now.

**Comment by toddpfaff** [comment]
On CentOS-7 I can quite easily install newer development toolsets for g++ up to version 8.

Is there a netket dependency on g++ == 5 or g++ >= 5?  Should I got for 6, 7 or 8?

**Comment by gcarleo** [comment]
I'd suggest to just go for the latest versions

**Comment by toddpfaff** [comment]
The  netket build worked with devtoolset-8 (g++-8).
It failed with devtoolset-6 (g++-6).

**Comment by gcarleo** [comment]
Interesting, indeed I see that we are testing on gcc 7 up to gcc 9, for some reason support for gcc 6 was dropped (most likely some bug in the compiler/incomplete feature) but we should update the docs on the website. Thanks
