### ISSUE TITLE
MetropolisHop does not preserve total number of particles

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#311]
I am needing a sampler that does the following: given a number of bosons and sites, remove a boson from a random site (that has at least one boson), and then creates a boson on a random site (My Hilbert space is defined so that the maximum number of bosons per site is at least the number of bosons in the system, so that the configuration of all bosons in one site is possible). From https://github.com/netket/netket/issues/148#issuecomment-552215173, it seems that MetropolisHop does that.

After importing netket, qutip and numpy I wrote the following code to reproduce Saito's paper (I have correctly reproduced it using just numpy, and I minimize the energy to the exact value):

```
def BH_Saito(machine, J=1, U=2, L=11, V=1, n_bosons=9, n_max=5, n_hidden=5):
    
    assert L%2==1
    
    V_list = V * (np.arange(L) - (L-1)//2)**2
    edges = []
    for i in range(L-1):
        edges.append([i, i+1])
        
    g = nk.graph.CustomGraph(edges)
    
    # hilbert space for each site
    hi = nk.hilbert.Boson(graph=g, n_max=n_max, n_bosons=n_bosons)
    
    #boson operators
    a = destroy(n_max + 1).full()
    adag = create(n_max + 1).full()
    num = np.matmul(adag, a)
    
    # fill operators and sites
    operators = []
    sites = []
    
    # Local term
    for i in range(L):
        op_loc = V_list[i] * num + 0.5*U * np.matmul(num, num - np.eye(n_max + 1))
        operators.append(op_loc.tolist())
        sites.append([i])
    
    # Hopping term
    for i in range(L - 1):
        op_loc = -J * np.kron(a, adag)
        operators.append(op_loc.tolist())
        sites.append([i, i+1])
        op_loc = -J * np.kron(a, adag)
        operators.append(op_loc.tolist())
        sites.append([i+1, i])
    
    op = nk.operator.LocalOperator(hi, operators=operators, acting_on=sites)
    
    # Define the fully-connected FFNN    
    if machine == "ffnn":
        layers = (nk.layer.FullyConnected(input_size=L,output_size=n_hidden,use_bias=True),
                  nk.layer.Tanh(input_size=n_hidden),
                  nk.layer.FullyConnected(input_size=n_hidden, output_size=2, use_bias=True),
                  nk.layer.SumOutput(input_size=2))
        for layer in layers:
            layer.init_random_parameters(seed=1234, sigma=0.1)

        ffnn = nk.machine.FFNN(hi, layers)
    
    elif machine == "rbm":
        ffnn = nk.machine.RbmSpinSymm(hi, alpha=n_hidden)
    
    elif machine == "jastrow":
        ffnn = nk.machine.JastrowSymm(hilbert=hi)
    
    ffnn.init_random_parameters(seed=1234, sigma=0.01)
    
    print('Parameters of wavefunction:', ffnn.n_par)
    
    # Define the sampler that exchanges particles 
    #sa = nk.sampler.MetropolisHamiltonian(machine=ffnn, hamiltonian=op) # This one doesn't work well, even though it preserver the number of bosons, the energy is not minimized completely.
    sa = nk.sampler.MetropolisHop(machine=ffnn, d_max=L)
    
    # Define the optimizer
    opt = nk.optimizer.Sgd(learning_rate=0.03, l2_reg = 1e-5, decay_factor=1)
    
    
    gs = nk.variational.Vmc(hamiltonian=op,
                        sampler=sa,
                        optimizer=opt,
                        n_samples=1000,
                        discarded_samples=200,
                        use_iterative=True,
                        method='Gd')
    
    # Define observables for mean number of bosons in each site:
    for i in range(L):
        op_num_i = [num.tolist()]
        sites_i = [[i]]
        n_i =  nk.operator.LocalOperator(hi, op_num_i, sites_i)
        gs.add_observable(n_i, "n_{0}".format(i))
        
    gs.run(output_prefix='test', n_iter=5000)
    if n_bosons <= 5 and L <= 5:
        res = nk.exact.lanczos_ed(op, first_n=1, compute_eigenvectors=True)
        print("Exact ground state energy = {0:.3f}".format(res.eigenvalues[0]))
        E0 = res.eigenvalues[0]
    else:
        E0 = None
    return ffnn, gs, E0
```

Now, I run the function:

```
n_bosons = 4
n_sites = 5
m, vmc, E0 = BH_Saito(machine="rbm", L=n_sites, n_max=n_bosons + 1, n_bosons=n_bosons, n_hidden=6)
```
If everything works well, energy should be minimized and the samples should preserve the number of bosons. However, after I read the results:

```
# Load the data from the .log file
import json

data = json.load(open("test.log"))

# Extract the relevant information
iters = []
energy = []
num = []
for iteration in data["Output"]:
    n = []
    iters.append(iteration["Iteration"])
    energy.append(iteration["Energy"]["Mean"])
    for i in range(n_sites):
        n.append(iteration["n_{0}".format(i)]["Mean"])
    num.append(n)
```

I get that the configuration of the last group of samples has the following expectation occupancy of sites:

![Screenshot_2019-11-11_19-13-57](https://user-images.githubusercontent.com/31494271/68631148-a4e1a900-04b7-11ea-8100-575539e0deee.png)

The sum of the mean number of excitations is 2.04, and it should be 4.0, as this is the number of bosons I selected at the beginning.

**Comment by gcarleo** [comment]
Sorry, I didn't remember correctly. Indeed as it can be easily seen from the [source code](https://github.com/netket/netket/blob/master/Sources/Sampler/metropolis_hop.hpp), `MetropolisHop` does not preserve the number of particles. Basically, it is just a two-side extension of `MetropolisLocal`, thus it picks two sites at random and generate two states compatible with the possible local quantum numbers, but there is no need that the total number of particles is conserved. 

`MetropolisHamiltonian` (if used with the BoseHubbard hamiltonian without chemical potential) conserves the number of particles, and does exactly what you want... That's what is used also in the [Example](https://github.com/netket/netket/blob/master/Examples/BoseHubbard1d/bosehubbard1d.py)

Notice however that in general there is no reason why RbmSpin should work well for bosons... RbmSpin is really designed for binary (+1,-1) local degrees of freedom, not unbounded integers like for bosons
