### ISSUE TITLE
`init_random_parameters` and standard deviation

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#320]
Are we sure `init_rand_pars` sets the standard deviation? (this is on nk 2.1) 

```
>>>import netket as nk
>>>import numpy as np

>>>g = nk.graph.Hypercube(length=20, n_dim=1, pbc=True)
>>>hi = nk.hilbert.Spin(s=0.5, graph=g)
>>>ma = nk.machine.RbmSpin(alpha=10, hilbert=hi)
>>> ma.init_random_parameters(seed=1234, sigma=0.5)
>>> np.std(ma.parameters)
0.7042321266518814
>>> np.var(ma.parameters)
0.4959428882086316
```

Is in contradiction with [the docs](https://www.netket.org/modules/netket.machine.RbmSpin.html#netket.machine.RbmSpin.init_random_parameters)

**Comment by gcarleo** [comment]
I have fixed this in version 3.0, just calling ```numpy.random.normal(scale=sigma)```
