### ISSUE TITLE
Remove MPI from C++ code

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#324]
At this stage, MPI is the only library we are forced to link against (except python of course), and this has proven tricky to maintain properly. 
Currently, MPI calls in C++ are limited to 2 main things: 

- [x] computing statistics
- [x]  seeding random number generators
- [ ] SR matrix-less multiplication

When #299 is completed, 1. won't be necessary anymore in C++ (we will have numpy-style statistics based on mpi4py). 2 can also be addressed on the python side, just slightly refactoring the C++ parallel random engine

**Comment by PhilipVinc** [comment]
I think you are forgetting computing the product of the SR matrix times a vector iteratively when not building the full matrix. 
This will require a trampoline method

**Comment by gcarleo** [comment]
Yes I was hoping to rewrite also SR in python. The full solver is just a call to scipy.linalg.solve, so it's fine. The sparse solver will require defining a scipy.sparse.linalg.LinearOperator that performs the average... I think this should be all good in terms of performance, but we need to test

**Comment by gcarleo** [comment]
Closing this because C++ is gone in 3.0
