### ISSUE TITLE
get wavefunction after supervised learning

### ISSUE THREAD

**Issue by NnktYoshioka** [netket/netket#329]
Hi,

I was taking a look at the supervised learning tutorial, and noticed that the usual `ma.to_array()` does not return the expected wavefunction although the optimization seems to suggest the fidelity between the exact calculation is quite high.
Is this a bug, or is there any other way to get the wf?

Thanks in advance!

**Comment by kchoo1118** [comment]
The to_array() method is not imposing any symmetry like total magnetization, while in the optimisation, depending on the choice of the sampler, some symmetry could have been imposed. The wavefunction is only optimised within the symmetry sector.

**Comment by NnktYoshioka** [comment]
I see, the optimization indeed assumes total_sz = 0. I confirmed that the amplitudes are correct within this sector.
The optimization does not seem to work properly without the assumption, so if we want the machine for the full Hilbert space I guess we can 
    1. simply take the Hamiltonian to be the projection operator
    2. add hidden neurons that projects onto symmetry sector after the supervised learning

**Comment by gcarleo** [comment]
Indeed this is the case thanks @kchoo1118 . Let me also add that doing the optimization without the constraint total_sz=0 is intrinsically harder for mainly two reasons 

1. For the heisenberg model, any local sampler will not efficiently explore all subspaces at fixed total s_z, thus most likely it will automatically learn only one or two subspaces at most 

2. If your target wave function for the supervised learning is the ground-state, even with exact sampling it is likely that the overlap with excited sectors is anyways quite low, and you might end up having not enough samples to learn other magnetization sectors

I hope this helps!
