### ISSUE TITLE
nk.machine.RbmSpin(hilbert=ma.hilbert) fails

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#337]
Found on v2.1. 
I must have gotten some conversions wrong somewhere.

```python
➜ python
Python 3.7.4 (default, Sep  7 2019, 18:27:02)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netket as nk
MPI successfully initialized by NetKet.
>>>
>>> g = nk.graph.Hypercube(length=20, n_dim=1, pbc=True)
>>> hi = nk.hilbert.Spin(s=0.5, graph=g)
>>> ma = nk.machine.NdmSpinPhase(hilbert=hi, alpha=1)
# Phase NDM Initizialized with nvisible = 20 and nhidden  = 20 and nancilla = 0
# Using visible   bias = 1
# Using hidden    bias  = 1
# Using ancillary bias  = 1
>>> ma2 = nk.machine.RbmSpin(hilbert=ma.hilbert, alpha=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Unable to cast from non-held to held instance (T& to Holder<T>) of type 'std::__1::shared_ptr<netket::AbstractHilbert const>''

**Comment by gcarleo** [comment]
Oh interesting, how come this is not already tested in test_machine.py?

**Comment by PhilipVinc** [comment]
I think At the time I had not thought about building a standard machine from the Hilbert space of a density matrix-machine.

The error is probably because something is returned by reference but is expected to be a shared pointer, or I have a missing copy constructor in DoubledHilbert... I’ll check soon

I’m doing that now because I am trying to build a density matrix wrapper for arbitrary FFNN.


Il 5 feb 2020, 12:20 +0100, Giuseppe Carleo <notifications@github.com>, ha scritto:

**Comment by IanAuckes** [comment]
I'm getting the same error on a Hamiltonian constructed using PauliStrings.
The same process with other Hamiltonian constructions (Heisenberg, GraphOperator, LocalOperator) work fine.

![Error](https://user-images.githubusercontent.com/25305000/88958119-a4937300-d2bd-11ea-9d9e-fe76ef7c2d8b.png)
