### ISSUE TITLE
progress bar for interactive VMC run 

### ISSUE THREAD

**Issue by orialb** [netket/netket#341]
Hi, 
First of all thanks for developing this very nice library!

This is a minor feature, but it would be nice to have a progress bar when playing with the library interactively. It is quite simple to implement it using the `tqdm` library, it would look something like this:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/1208196/74938571-8d875580-53ee-11ea-8a54-4a8791df5ab2.png">

It could be enabled/disabled by a keyword argument `show_progress` (or something like this) for `Vmc.run` (I think it could also be made to work with MPI, but in case not it can be disabled by default and enabled by the user request). 

If there is interest I could make a PR for this.

**Comment by orialb** [comment]
(actually maybe there is no problem at all with MPI, because it is used somewhere inside `Vmc.advance` as far as I understand and the progress bar only tracks the number of iterations in `Vmc.run`)

**Comment by gcarleo** [comment]
Thank you @orialb for this proposal, it seems like a very nice idea! Yes please, it'd be great if you could make a PR (just remember to do it to the branch v2.1, not to master) thank you

**Comment by orialb** [comment]
Great, I'll make the PR at some point during the following days.
Regarding the feature:
1. Are there any other statistics that are useful to print other than the mean energy?
2. Would you prefer the progress bar to be disabled or enabled by default?

**Comment by gcarleo** [comment]
1. It is OK to put only the energy, but ideally you might want to do something a bit more general, say 
```python
show_progres=["Energy","SigmaX"...]
```
and it fetches the associated observables using the method get_observable_stats (take a look at netket/_vmc.py)

on the other hand, something like 
```python
show_progress=True 
```
or 
```python
show_progres=[]
```
would show the iteration progress only

2. I would say that by default show_progress=None
