### ISSUE TITLE
RFC: Unify utility methods between VMC and Steadystate

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#348]
After the recent nice PR #344 I would like to port those same utilities over to the steady-state solver mc.

The steady-state solver shares the same high-level behaviour of VMC, but has a (slightly) different `advance()` and `get_observable_stats` implementations.

As such, I'd like to factor out all common functionalities, mostly related to observables and json input/output into an abstract base class, dubbed `AbstractVMCRunner` or something like that, change `netket.variational.vmc` and `netket.steadystate` to subclass it.

@gcarleo what do you think?

**Comment by gcarleo** [comment]
I think it's an excellent and long overdue idea, we should definitely do this. Is it possible to abstract it to something a bit more general than VMC-like simulations? (For example we also have the unsupervised learning and supervised learning drivers that have similar structure)

**Comment by femtobit** [comment]
Yes, I think we should take this opportunity to unify that code. I have some draft code for `Vmc.run` on the new VMC driver. I can make a work-in-progress PR on that, then we can maybe see what can be extracted as common functionality.

At least the JSON-writing part of the `run()` logic should be possible to extract easily (though I'm not convinced it has to be in a base class, we could just as well extract the output code into an external function). If we also get rid of `add_observable` etc., that'd probably already cover most of the repeated code.

**Comment by femtobit** [comment]
If the `advance()` and `get_observable_stats()` logic is also very similar, as it seems to be the case for VMC and steady-state computations, @PhilipVinc's suggestion of a common base class also makes sens, I think. Maybe less so for the other types of learning.

**Comment by gcarleo** [comment]
I think that basically all learning algorithms have a stage where you measure observables (get_observable_stats...), where you update the parameters of the machine, and finally where you do i/o of this (say on json or anything you like) 

we can certainly abstract these 3 concepts?

**Comment by PhilipVinc** [comment]
@femtobit I agree that it would make more sense to factor out the Json logic.
As to have for example different output bins and be able to append to them or something similar.
But in the end all runners need to dump informations into those and those methods will be mostly equivalent.

**Comment by PhilipVinc** [comment]
Closed by #353
