### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#360]
When we reach some beta-stable state, we should consider submitting a conda recipe to Conda-forge (see [How to add a recipe to conda-forge](https://conda-forge.org/#add_recipe)).

For posterity, I've been using for a while [this Conda-build recipe](https://gist.github.com/PhilipVinc/75fee700c0a306cf21f387223d498b66) which works quite well..

It handles MKL and no MKL variants, but disables Lapacke. 
If someone manages to make it work, I'd like to know how.

**Comment by gcarleo** [comment]
Thanks @PhilipVinc for the hard work on this
