### ISSUE TITLE
Rename `netket.stats.Stats.R` to `Rhat`?

### ISSUE THREAD

**Issue by femtobit** [netket/netket#384]
As we have seen in the discussion on #365, the `stats.R` parameter is ambiguously named; it is sometimes called "Gelman-Rubin" statistic or "potential scale reduction", but I think the most common way to refer to it is $\hat R$ in LaTeX math or "Rhat" in words (this name is used, e.g., by the [stan](https://mc-stan.org/rstan/reference/Rhat.html) framework). So I propose we also call it `Rhat` starting in 3.0.

What do you think?

**Comment by gcarleo** [comment]
Agreed, R is really confusing

**Comment by fabienalet** [comment]
Definitively agree
