### ISSUE TITLE
Add Monte Carlo sweeps for equilibration before making measurement 

### ISSUE THREAD

**Issue by wuyukai** [netket/netket#40]
In ground_state.hpp the sampling of the spin configurations directly starts from an initial configuration, which is random at iteration 0. Therefore at this step the sampled derivatives can have large error as the Monte Carlo sampling has not reached equilibrium for the first few sweeps. This is not a big problem for large number of iterations; but if I want to start the iteration from a previous one by specifying "InitFile", even the first few iterations become important. So I suggest to add some sweeps, say, 1/10 of the total number of sweeps, after setting random initial spin configurations. This will not significantly change the timing because it is not needed for the later iterations.

**Comment by gcarleo** [comment]
Thanks for the report @wuyukai. This is indeed a valid point. We should specify the number of iterations to be skipped as a parameter inside the input file. Would you like to do a pull request to include this feature?

**Comment by wuyukai** [comment]
I can do this. Maybe I can add an entry "SkipInitSamples" under "Learning", with the default value 0?

**Comment by gcarleo** [comment]
Maybe `DiscardedSamples` is a better name? Yes, actually maybe default value should actually be 10% of the total number of samples, not 0. Also, I would implement this thing in a way that if you specify `NSamples`=1000 you are always guaranteed to perform at least 1000 samples, even if you have a certain number of discarded samples. Basically the Discarded samples should run the sweep in a separate loop.

**Comment by gcarleo** [comment]
Implemented with pr #41
