### ISSUE TITLE
Write DbmSpinPhase with a couple of backends 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#409]
Jax and numpy are good candidates for that! Maybe we could first do this in Jax since it is quite straightforward and then see how to do it in numpy trying to recycle at maximum the code used in the pure state case. 

@PhilipVinc make us dream

**Comment by VolodyaCO** [comment]
Can this machine be implemented also for Boson Hilbert spaces? Something like an open quantum system version of the RBMMultiVal

**Comment by gcarleo** [comment]
It would be a minimal change of what we are already implementing in Jax now #407 (still not working 100%)... It's essentially the same machine with the addition of a one-hot encoding layer, it's a one-line modification!
