### ISSUE TITLE
Make JaxSr work for more than one MPI process

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#412]
The current implementation breaks for more than one MPI process, but it could be fixed adding a netket.stats.mean that works for jax types over mpi

**Comment by gcarleo** [comment]
This is fixed, is that right @PhilipVinc ?

**Comment by PhilipVinc** [comment]
Yep
Il 21 mag 2020, 00:36 +0200, Giuseppe Carleo <notifications@github.com>, ha scritto:
