### ISSUE TITLE
Automatic dispatch for SR and optimizers

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#413]
Ideally, we should have automatic dispatch for (at least) the correct SR version needed for a given backend, so that JaxSr is automatically instantiated when dealing with a Jax machine etc

**Comment by PhilipVinc** [comment]
To achieve this I think one possible option is to rename the current SR class to `NumpySR`, and create a new `SR` class that is a very lightweight dict-like class holding the options for SR.
Then, in the `__init__` method of drivers, we use our knowledge of the machine to instantiate the correct `SR` implementation (numpy, jax, torch...).

The main complication is that one might possibly change the sr parameters after some iterations, and we have to make sure that this still works, for example by keeping a reference to this sr parameters object in the implementation.
```python
sr = nk.optimizer.SR(shift=0.01)
ss = nk.steadystate(sampler, lind, .... sr=sr)
for i in range(100):
  ss.advance(1)
  sr.shift = 0.01 ** ( i /10)
```  

We could play the same trick with samplers

**Comment by gcarleo** [comment]
Yes, this is a good plan! For the issue you mention, can't we just define a base class and then derive it for numpy and jax respectively?

**Comment by PhilipVinc** [comment]
yes I guess we could.

But we also need an extra class that is the one that only stores the parameters, decoupled from the implementation
