### ISSUE TITLE
Add more tests for Jax backend

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#415]
We are a little short of tests for the jax backend

**Comment by jamesETsmith** [comment]
Hi @gcarleo, I'm happy to help with this. I assume I should start with branch v3.0?

**Comment by gcarleo** [comment]
Hey @jamesETsmith , yes v3.0 is the one! I would maybe wait for a couple of days though, so that we stabilize a few things on the jax side

**Comment by gcarleo** [comment]
It looks like a lot of new tests have already been added by @PhilipVinc while we has fighting to fix a few issues with Jax objects, so we might as well close this one too!
