### ISSUE TITLE
How can I track parameters? (not an issue)

### ISSUE THREAD

**Issue by dambuck** [netket/netket#443]
Hi,

This might be trivial but I could not figure out how to save the parameters during optimization. The save_params_every argument seems to overwrite the .wf file which holds the parameters. I would like to average over the parameters of the last x optimization steps in order to do a mc run afterwards without optimizing. 

Thanks

**Comment by gcarleo** [comment]
Hi @dambuck , I would suggest you use the iterator interface of Vmc if you need to have more control on what you print/store during each iteration of the learning. 

essentially you can do something like 

```python
for step in vmc.iter(steps, 1):
     print(wf.parameters)
```

etc...

**Comment by dambuck** [comment]
Thank you for your quick response. That looks very pythonic, will I loose speed in using iter? Can this still be executed in parallel through mpirun?

**Comment by gcarleo** [comment]
Not really, there is no penalty, unless each vmc iteration costs much less than a millisecond or so, which seems unlikely :) 
Yes, it can run in mpi. If you need to print/do operations node-wise, you will need to use mpi4py to control/know which node you are using.

**Comment by PhilipVinc** [comment]
@gcarleo BTW, IMO it would be worth implementing something like this.

**Comment by gcarleo** [comment]
You mean an averaged stochastic gradient descent à la Polyak? Yes, we could add that as an option I guess... but then you need to specify also the averaging windows etc, a bit too much for the run interface?

**Comment by dambuck** [comment]
thanks! good to know

**Comment by PhilipVinc** [comment]
Yes, as a separate optimiser maybe.
