### ISSUE TITLE
about running netket example

### ISSUE THREAD

**Issue by sassan72** [netket/netket#446]
Hi everybody. I am new with netket. I have installed it but I don't know how to run an example of netket. I will be appreciated if you help me with that.

**Comment by sassan72** [comment]
I run it with jupyter notebook. I got this error. 

ImportError: dlopen(/opt/anaconda3/lib/python3.7/site-packages/netket/_C_netket.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.40.dylib
  Referenced from: /opt/anaconda3/lib/python3.7/site-packages/netket/_C_netket.cpython-37m-darwin.so
  Reason: image not found

**Comment by PhilipVinc** [comment]
it looks like there is a problem with your `mpi` /`mpi4py` installation.

Can you try running
```bash
python -c "import mpi4py; print(mpi4py.get_config())"
```

**Comment by sassan72** [comment]
python -c "import mpi4py; print(mpi4py.get_config())"
after running:
{'mpicc': '/usr/local/bin/mpicc', 'mpicxx': '/usr/local/bin/mpicxx', 'mpifort': '/usr/local/bin/mpifort', 'mpif90': '/usr/local/bin/mpif90', 'mpif77': '/usr/local/bin/mpif77'}

**Comment by PhilipVinc** [comment]
could you also do
```
/usr/local/bin/mpicc --showme:link
```

The output should be something like 
```
-L/usr/local/opt/libevent/lib -L/usr/local/Cellar/open-mpi/4.0.3/lib -lmpi
-I/usr/local/Cellar/open-mpi/4.0.3/include
```
then run
```
ls XXX
```
where `xxx` is `-LXXXX -lmpi` from the output above (so in my case that would be `/usr/local/Cellar/open-mpi/4.0.3/lib`).

can you also tell me more about your installation?
I guess you are on linux, you have installed mpi through some system-provided channel (apt-get or similar) and you have conda installed.
how did you install netket ? conda install or pip install?

**Comment by sassan72** [comment]
thanks Philipe. I used pip install on Mac OS. I think you're right. the problem is about mpi4py library. I don't have a directory in /usr/local/bin/mpicc: No such file or directory with the name of mpicc. but the netket is installed without any error by using pip install netket.

**Comment by PhilipVinc** [comment]
As it's specified in netket docs, you must install yourself a working mpi installation. pip cannot install it for you.
If you are on Mac, the easiest way is to do `brew install mpich`. (if you don't know what is brew or this does not work, check here `https://brew.sh`)

Alternatively, since I see you are using anaconda, `conda install netket` will install absolutely all dependencies required. Be warned that before installing netket with conda you probably should uninstall the pip version...
