### ISSUE TITLE
about Bose Hubbard Hamiltonian

### ISSUE THREAD

**Issue by sassan72** [netket/netket#462]
I want to use netket to obtain ground state wave function for 2d Bose Hubbard hamiltonian. I checked the Hamiltonian parameters. It seems that Hamiltonian parameters are // Bose Hubbard
  pars = {
      {"Graph",
       {{"Name", "Hypercube"}, {"L", 10}, {"Dimension", 2}, {"Pbc", true}}},
      {"Hamiltonian", {{"Name", "BoseHubbard"}, {"U", 4.0}, {"Nbosons", 23}}}};
I can't see tight binding and chemical potential parameters. 

for example, I have these two commands to find hamiltonian for Bose Hubbard model. 
# 1D Periodic Lattice
g = nk.graph.Hypercube(length=3, n_dim=2, pbc=True)

# Boson Hilbert Space
hi = nk.hilbert.Boson(graph=g, n_max=9)

# Bose Hubbard Hamiltonian
ha = nk.operator.BoseHubbard(U=4.0, hilbert=hi,mu=1.0, t=05) t parameter for tight binding model.

**Comment by VolodyaCO** [comment]
From the documentation:

    Args:
           hilbert (netket.hilbert.Boson): Hilbert space the operator acts on.
           U (float): The Hubbard interaction term.
           V (float): The strenght of density-density interaction term.
           J (float): The hopping amplitude.
           mu (float): The chemical potential.

**Comment by sassan72** [comment]
thanks
