### ISSUE TITLE
LocalOperator __add__ strange behaviour

### ISSUE THREAD

**Issue by jwnys** [netket/netket#463]
This issue is related to version 3 (commit #664eae8).

Here's an example of a problem I encountered while creating the total spin operator S^2 by adding the individual contributions
- I first create single-spin operators: \sum_i S_i^2 using: 
```python
S2_a = LocalOperator(hi, [ss] * L, [[i] for i in range(L)]) # here ss = (sx@sx+sy@sy+sz@sz) the S_i^2 operator
```
- next, I create the two-body terms: \sum_i<j 2* S_i . S_j using: 
```python
combinations = [[i,j] for i,j in itertools.combinations(range(L), 2)]
S2_b = LocalOperator(hi, [2*(sxsx+sysy+szsz)]*len(combinations), combinations) # here sxsx = np.kron(sx, sx)
```
- then, I add them together: 
```python
S2_c = S2_a + S2_b
```

However, I find that E[S2_a] + E[S2_b] != E[S2_c], where E is the mc_stats computed expectation value.

I'm adding here an analysis on some strange behaviour that might lead to this (?).

Looking in the code, local_operator.py does something odd: in the __add__ operator of LocalOperator, the self._acting_on is reshaped in "_add_operator" when it reaches the two-body terms. It is reshaped into a shape with # columns = 2 (while it is initially # columns = 1 when the S2_a operator is analysed). 
At this point, the reshaping fills the second column in a rather strange way, while the first column indeed is filled with the original "acting_on" values. Here's an example:

``` python
old_array = self._acting_on
self._acting_on = _np.resize(old_array, (old_n_op, self._max_acting_size))
print("reshape:", self._acting_on)
self._acting_on[:, : old_array.shape[1]] = old_array
print("store_old:", self._acting_on)
```
yields the following for 4 spins (1D)

reshape: [[0 1]
 [2 3]
 [0 1]
 [2 3]]
store_old: [[0 1]
 [1 3]
 [2 1]
 [3 3]]

I'm not sure what the intention is here (code is undocumented), but notice that at this point, after adding the operators of S2_a (the 1 body terms), we also have the acting_on = [1 3]. When adding the two-body operators in S2_b, we now do not add the operator that acts on 1 and 3: [1 3], but rather add it to the original 1 body operator.

This would not be an issue, except that this triggers the following support check:
```python
if support_i is not None:
            dim = min(operator.shape[0], self._operators[support_i].shape[0])
            _opv = self._operators[support_i][:dim, :dim]
            _opv += operator[:dim, :dim]

            self._append_matrix(
                self._operators[support_i],
                self._diag_mels[support_i],
                self._mels[support_i],
                self._x_prime[support_i],
                self._n_conns[support_i],
                self._acting_size[support_i],
                self.mel_cutoff,
                self._local_states,
            )
            return
```
where we take the minimum dimension (which is 2 here, not 4 as we would want it to for the 2 body case). Also, _opv is never used again.

Might be that I'm misunderstanding what is happening, but in any case the results don't make much sense now. Clarification would be much appreciated!

**Comment by jwnys** [comment]
Suggestion would be to change the following to avoid triggering the support clause:
```python
old_array = self._acting_on
# default is -1 to avoid triggering the support clause
self._acting_on = _np.full((old_n_op, self._max_acting_size), -1)
self._acting_on[:, : old_array.shape[1]] = old_array
```

**Comment by gcarleo** [comment]
Thank you @jwnys , unfortunately in 3.0 I had to write LocalOperator in a rather ugly way to be able to have it work in an efficient way. So it might well be that there is still some small bug around... Does your issue started happening after this was merged https://github.com/netket/netket/pull/449, or is it independent ?

**Comment by jwnys** [comment]
Hi @gcarleo ,
Thanks for the reference. It seems that #48a0aebace8c6410750779677c8c9a05d04dbc2d might solve the issue. I'm working on a version slightly older (been stuck on this for a while)
```python
for (i, support) in enumerate(self._acting_on_list()):
```
indeed has the same effect as my proposal. I now obtain S^2 >= 0 :).
Thanks a lot! You can close this issue.

**Comment by fabienalet** [comment]
@jwnys : the first term ("single-spin operator") is a constant, right? Could this help, or was this example just for demonstration purpose?

**Comment by jwnys** [comment]
@fabienalet 
Not sure what you mean exactly.. Building the S^2 operator from LocalOperators is a valid approach, isn't is? S^2 can vary during the optimization (ground state of SU(2) invariant hamiltonians is then S^2=0). The goal is to monitor the presence of S^2>0 exited state contributions during optimization.

**Comment by fabienalet** [comment]
> Still, this type of implementations should work as well..

Yes indeed.

If you have a translation invariant system, I guess you can avoid the double sum in the second term too

**Comment by gcarleo** [comment]
Ok great to know that this was solved by that PR, please feel free to stress test this as much as possible to see if there is something else that escaped... (hopefully not)

**Comment by jwnys** [comment]
@fabienalet , indeed, but I'd rather monitor this to be certain that our wave-function ansatz is indeed translation invariant as well.
