### ISSUE TITLE
Need help with estimation of spin-spin correlations with NetKet 2.1.1

### ISSUE THREAD

**Issue by SemyonSinchenko** [netket/netket#465]
Hello!
At first I want to thank for that nice library!

Also I have a couple of questions about how to use it.

I try to reproduce the result from https://arxiv.org/pdf/1905.11066.pdf (Fig. 4) but fail with it. I use NetKet 2.1.1 and the following code for estimate spin-spin correlations <img src="https://latex.codecogs.com/gif.latex?S_{ij}=\sigma^z_i{\sigma^z_j}" />:
```python
...
from netket.operator.spin import sigmaz
...
for i in range(self.n_spins):
    for j in range(self.n_spins):
            self.corr_operators["{:d}-{:d}".format(i, j)] = sigmaz(
                self.hilbert, i
        ) * sigmaz(self.hilbert, j)
...
corrs = self.vmc.estimate(self.corr_operators)
corr_mat = np.zeros(shape=(self.n_spins, self.n_spins), dtype=np.float64)
for i in range(self.n_spins):
    for j in range(self.n_spins):
        corr_mat[i, j] = np.real(corrs["{:d}-{:d}".format(i, j)].mean)
...
```
Full code is [here](https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/python/SpinCorrelationSolver.py).
I found such example of using `LocalOperator` in NetKet tutorial. I use the VMC with SR and RBM as machine (code of my Ising solver [here](https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/python/IsingCorrelationsSolver.py)).

Energy converges to the exact solution, acceptance ratio and energy variance also converges to zero but spin-spin correlations matrix converges to something strange:
<img src=https://github.com/SemyonSinchenko/IsingCorrelations/raw/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/correlations/corr_plot_step_4.png width="300" height="300">
Full results for 12 spins, H=0.2 and J=1.0 are [here](https://github.com/SemyonSinchenko/IsingCorrelations/tree/master/output_spins_12_h_2.00E-01_j_1.00E%2B00).
I tried difference parameters of RBM, VMC, H, J and number of spins but nothing helped. What I do wrong?

Another question is what is the right way of using SR in VMC? I cannot find the VMC description in NetKet documentation and don't understand how to use it right. I looked at the source code of nk.Vmc and found a "duct tape" for me:
```python
self.vmc = nk.Vmc(
    hamiltonian=self.hamiltonian,
    sampler=self.sampler,
    optimizer=self.optimizer,
        n_samples=max([1500, self.n_spins * 50]),
        sr=nk.variational._SR(
            lsq_solver="LLT",
            diag_shift=1.0e-2,
            use_iterative=not use_cholesky,
            is_holomorphic=self.sampler.machine.is_holomorphic,
        ),
)
```
but it seems to me that direct call of "private" `nk.variational._SR` is something bad. Also I don't understand what exactly mean the row `lsq_solver="LLT"` and what other value can I put to this parameter...

Many thanks in advance and sorry for such "newbie" question!

**Comment by femtobit** [comment]
Hi Semyon: Thanks for the detailed question.

First, regarding your use of SR: What you are doing (passing `nk.variational._SR`) to `Vmc` is essentially correct. As you've noticed, `netket.variational._SR` is marked as private.
However, this is just an alias for `netket.optimizer.SR`, which is the actual (and officially supported) location of this class.

The fact that `_SR` it is available from `netket.variational` is just a side-effect of it being imported there for internal use - which is exactly why it is marked private in that location. These kinds of accidental imports are unfortunately unavoidable in Python (and not always marked as private; e.g., when using `matplotlib`, you can call `matplotlib.numpy` but that's also just a side-effect of the package using NumPy internally, and not intended to be public API).

The `lsq_solver="LLT"` option refers to the linear solver used to compute the parameter update from the linear SR equation `S ẋ = f`. The supported solvers in 2.1 come from the [Eigen3](https://eigen.tuxfamily.org/dox/group__TopicLinearAlgebraDecompositions.html) library, where, e.g., "LLT" refers to the Cholesky decomposition.

Regarding the spin correlators: On first glance, your code looks good to me. One quick sanity check you could do is to compute the ED ground state (not just the energy but the full eigenstate), which should be fast for N=12, and check what the spin correlators look like with ED. Something like this should work:
```python
r = netket.exact.lanczos_ed(hamiltonian, compute_eigenvectors=True)
psi0 = r.eigenvectors[0]
psi0 /= numpy.linalg.norm(psi0) # state vector might not be normalized

corr = numpy.vdot(psi0, corr_op.to_sparse().dot(psi0))
```
where `corr_op` is an operator. If this gives the same results as VMC, you know that it's not a convergence issue. In that case, maybe you could post your code defining the lattice and Hamiltonian. Maybe there is a difference in how the system is defined compared to your reference?

**Comment by SemyonSinchenko** [comment]
@femtobit Thank you! I've calculated an exact solution and I got a different result compared to VMC. It seems that it is a convergence issue... But it seems strange for me because the energy converges to ground state. It is an exact solution:
<img src="https://raw.githubusercontent.com/SemyonSinchenko/IsingCorrelations/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/exact/exact_corr_mat.png"/>

And it looks different from what I get from VMC. The last results from VMC looks like this:
<img src="https://raw.githubusercontent.com/SemyonSinchenko/IsingCorrelations/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/correlations/corr_plot_step_4.png"/>

I save correlations matrix at different steps and the whole dynamics is [here](https://github.com/SemyonSinchenko/IsingCorrelations/tree/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/correlations). 

Previously I already have tried different parameters of VMC and learning (density of hidden units, number of epoch etc.) but nothing helped. I have no idea how to control such things because energy converges right... Maybe any tips about it?

**Comment by femtobit** [comment]
@SemyonSinchenko Thanks for the update. Some more things you could try to isolate the source of the differences:

(1) Compute the expectation value of the correlators using the full NQS wavefunction (without VMC sampling). If you use `RbmSpin`, you can just do `psi = rbm.to_array(normalize=True)` to get the full state vector and then compute the expectation values as above for the ED eigenvector. That way you can be sure its not a weird sampling issue.

(2) How well converged is the energy, exactly, i.e., what is the error compared to the ED energy and what is the variance of the variational energy (which should be close to zero if you're indeed close to an eigenstate)? Also, what are the MC statistics on the spin correlators you show here (i.e., MC error, variance, etc.)? Are they maybe not converged (they usually need more samples than the energy)?

**Comment by gcarleo** [comment]
yes I would also compute the overlap with the ED ground state directly

**Comment by SemyonSinchenko** [comment]
@femtobit @gcarleo Thank you both for the help and such active participation in my problem!

Data from the last run:
- exact solution for energy: [-11.14040458378402](https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/exact/ground_state.txt)
- VMC estimation at the last step (640): [-11.174969508012186](https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/main_report.csv), variance: [0.001253237536708173](https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/main_report.csv)

It is interesting for me also how the mean energy of VMC samples can be less than exact but it is another story. Maybe the problem is that I got the real part only isn't it?

Exact solution for correlations:
<img src="https://raw.githubusercontent.com/SemyonSinchenko/IsingCorrelations/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/exact/exact_corr_mat.png" width=400/>

At one of the first step of learning:
- correlation matrix:
<img src="https://raw.githubusercontent.com/SemyonSinchenko/IsingCorrelations/master/output_spins_12_h_2.00E-01_j_1.00E%2B00/correlations/corr_plot_step_0.png" width=400/>
- variances matrix:
<img src="https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/output_spins_12_h_2.00E-01_j_1.00E+00/correlations/corr_var_plot_step_0.png?raw=true" width=400/>

At the last step of learning:
- correlation matrix:
<img src="https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/output_spins_12_h_2.00E-01_j_1.00E+00/correlations/corr_plot_step_4.png?raw=true" width=400/>
-variance matrix:
<img src="https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/output_spins_12_h_2.00E-01_j_1.00E+00/correlations/corr_var_plot_step_4.png?raw=true" width=400/>

Looks like it converges to something but not to exact solution...

VMC params:
```
Graph one the 12 vertices.
# RMSProp optimizer initialized with these parameters :
# Learning Rate = 0.001
# Beta = 0.9
# Epscut = 1e-07
Vmc(step_count=0, n_samples=1500, n_discard=38)
  Hamiltonian: <netket._C_netket.operator.GraphOperator object at 0x7fbfa8f3db30>
  Machine: <netket._C_netket.machine.RbmSpin object at 0x7fbfa8f3dbb0>
  Optimizer: <netket._C_netket.optimizer.RmsProp object at 0x7fbfa8f3daf0>
  SR solver:     Stochastic reconfiguration method for holomorphic wavefunctions
    Solver: LLT
```

Graph: ```nk.graph.Hypercube(length=self.n_spins, n_dim=1, pbc=False)```
Operator: ```nk.operator.Ising(hilbert=self.hilbert, h=self.h, J=self.j)```
(J=1.0, H=2e-1)
Hilbert: ```nk.hilbert.Spin(graph=self.graph, s=0.5)```
Machine: ```nk.machine.RbmSpin(hilbert=self.hilbert, alpha=3)```
Sampler: ```nk.sampler.MetropolisExchange(machine=self.machine)```
VMC: 
```nk.Vmc(
            hamiltonian=self.hamiltonian,
            sampler=self.sampler,
            optimizer=self.optimizer,
            n_samples=max([1500, self.n_spins * 50]),
            sr=nk.variational._SR(
                lsq_solver="LLT",
                diag_shift=1.0e-2,
                use_iterative=not use_cholesky,
                is_holomorphic=self.sampler.machine.is_holomorphic,
            ),
        )
```

Full code here: [https://github.com/SemyonSinchenko/IsingCorrelations](https://github.com/SemyonSinchenko/IsingCorrelations)
Reproduce command: ```mpirun -n 4 python main_ising.py --spins 12 --Hconst 0.2 --Jconst 1.0```
netket version: 2.1.1

Full results from the last run: [https://github.com/SemyonSinchenko/IsingCorrelations/tree/master/output_spins_12_h_2.00E-01_j_1.00E%2B00](https://github.com/SemyonSinchenko/IsingCorrelations/tree/master/output_spins_12_h_2.00E-01_j_1.00E%2B00)

I'll be happy for any tips... I have no idea how guys from [https://arxiv.org/pdf/1905.11066.pdf](https://arxiv.org/pdf/1905.11066.pdf) got such good estimation of correlations (Fig. 4)... Many thanks in advance!

**Comment by gcarleo** [comment]
I think the main issue is that you are using a "wrong" sampler. If I understand correctly you are using ```MetropolisExchange``` and not ```MetropolisLocal```? If that's the case, then you are fixing the total magnetization in the sampling and the sampling is highly non ergodic (I suspect that's also why you get a "wrong" (i.e. lower than the exact) energy when sampling, because expectation values are not correct!)

**Comment by SemyonSinchenko** [comment]
@gcarleo OMG Thanks a lot! It works! Perfect approximation:
<img src="https://github.com/SemyonSinchenko/IsingCorrelations/blob/master/output_spins_12_h_2.00E-01_j_1.00E+00/correlations/corr_plot_step_4.png?raw=true" width=500/>

I cannot express how I thank you for it! I've spend a huge amount of time in trying to get the same VMC estimation of corr-operator like in [https://arxiv.org/pdf/1905.11066.pdf](https://arxiv.org/pdf/1905.11066.pdf)! And now it works! Thanks again!
