### ISSUE TITLE
Time evolution

### ISSUE THREAD

**Issue by ericntunctu** [netket/netket#467]
Hi, I see the post that version 2.1 has added the time evolution.
https://github.com/netket/netket/issues/289
I have just a quantum state which was represented as RBM and I want to see its evolution under some particular Hamiltonian. I have seen this example:
https://github.com/netket/netket/blob/master/Examples/TimeEvolution/ising1d.py
But I can not run the code:
![image](https://user-images.githubusercontent.com/35599752/92154032-2b72c880-edf3-11ea-8ba8-8f754b42c06a.png)

Can you help me to do this?
Since the original paper study the quench dynamics, I also want to do the time evolution.

**Comment by PhilipVinc** [comment]
Closed by #1012
