### ISSUE TITLE
Getting acceptance of numpy metropolis_hastings

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#468]
The method defining the acceptance for `numpy/metropolis_hastings` in v3.0 is

```python
@property
def acceptance(self):
    """The measured acceptance probability."""
    return _mean(self._accepted_samples) / _mean(self._total_samples)
```

But `self._accepted_samples` and `self._total_samples` are ints. Don't know if this has been fixed in a PR, but if it's not, maybe it should be included.

**Comment by gcarleo** [comment]
willing to fix this in a PR? thanks!

**Comment by VolodyaCO** [comment]
Sure thing. I'll do that tomorrow morning.
