### ISSUE TITLE
Getting latest samples from VMC training

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#469]
# Short question

How do I get the latest configurations of the training phase of a Vmc `gs = nk.Vmc(hamiltonian=ha, sampler=sa, optimizer=op, n_samples=n_samples, sr=sr)`? `gs._samples` seems to be the correct variable, but it is not.

# Long question

I am trying to solve a Hamiltonian of 5 completely connected spins. The Hamiltonian has a 5-fold degenerate ground state, where any of the spins is up, and the rest is down. The implementation of the Hamiltonian is shown next:

```python
import netket as nk
import networkx as nx
from scipy.sparse.linalg import eigsh

L = 5
g = nx.complete_graph(L)
g = nk.graph.NetworkX(g)

hi = nk.hilbert.Spin(s=0.5, graph=g)

sz = np.array([[1, 0], [0, -1]])
ha = nk.operator.LocalOperator(hi)
for i in range(L):
    ha += nk.operator.LocalOperator(hi, 0.5*(L-2)*sz, [i])
    for j in range(L):
        if i != j:
            ha += nk.operator.LocalOperator(hi, 0.25*np.kron(sz, sz), [i, j])

ma = nk.machine.RbmSpin(alpha=1, hilbert=hi)
sa = nk.sampler.MetropolisLocal(ma, n_chains=32, sweep_size=1)
#sa = MetropolisLocalExchange(ma, n_chains=32, sweep_size=None)
op = nk.optimizer.Sgd(ma, learning_rate=0.05)
sr = nk.optimizer.SR(ma, diag_shift=0.1)
gs = nk.Vmc(hamiltonian=ha, sampler=sa, optimizer=op, n_samples=100, sr=sr)
gs.run(n_iter=250, out="test")
```
After I run this, the energy converges correctly to the -3.5 value that it should. Now, I want to see which spin configurations are relevant to the ground state. For this, I check which entries of the complete machine state are large:

```python
from qutip import state_index_number
psi_ma = ma.to_array()

idx = np.where(np.abs(psi_ma)**2>=1e-5)[0]
for i in idx:
    print(state_index_number([2]*L, i), "with coeff", (np.abs(psi_ma)**2)[i])
```

I got this:
```bash
[0, 0, 0, 1, 1] with coeff 1.4798755296251725e-05
[0, 1, 0, 0, 1] with coeff 1.4001762026219615e-05
[0, 1, 0, 1, 0] with coeff 1.5824190892762988e-05
[0, 1, 0, 1, 1] with coeff 0.004003922485146549
[0, 1, 1, 1, 1] with coeff 1.6373536077475163e-05
[1, 0, 0, 0, 1] with coeff 1.2678379200803993e-05
[1, 0, 0, 1, 0] with coeff 1.4328560384662225e-05
[1, 0, 0, 1, 1] with coeff 0.003625489953496893
[1, 0, 1, 1, 1] with coeff 1.4825983962557237e-05
[1, 1, 0, 0, 0] with coeff 1.3556889661874039e-05
[1, 1, 0, 0, 1] with coeff 0.003430237647768317
[1, 1, 0, 1, 0] with coeff 0.003876707463259443
[1, 1, 0, 1, 1] with coeff 0.9809055190037385
[1, 1, 1, 0, 1] with coeff 1.4027524281103155e-05
[1, 1, 1, 1, 0] with coeff 1.585330628826408e-05
[1, 1, 1, 1, 1] with coeff 0.004011289420208237
```

These configurations are read as 0 -> up spin, 1 -> down spin. Clearly, there is one state `[1, 1, 0, 1, 1] with coeff 0.9809055190037385` that gets almost all the probability. This is the correct solution (there are 5 correct solutions). However, this makes that all the other states get "noisy probabilities". Note that the state `[0, 1, 1, 1, 1] with coeff 1.6373536077475163e-05` is also a solution, but it was given a small probability (because the algorithm converged first to the other configuration. This is not a problem at all for what I need. However, I have extracted the probabilities by sampling the complete Hilbert space with `ma.to_array()`. I want, instead, to sample from netket's sampler to get a bunch of configurations, among which, I hope, there is a solution to the problem I'm looking for. Since the energy converged correctly, I assume that the latest samples contain the configuration `[1, 1, 0, 1, 1]`.

The question is, then, how do I retrieve this last batch of samples? For instance, `gs._samples` contains only these configurations (I print the unique ones):

```bash
[ 1.  1. -1. -1.  1.]
[ 1. -1. -1.  1.  1.]
[-1.  1. -1.  1.  1.]
[ 1.  1. -1.  1.  1.]
```

(Sorry for the change in notation, when 1 and -1 appear, those are spins. when 0 and 1 appear, 0 -> spin +1, 1 -> spin -1)

**Comment by VolodyaCO** [comment]
Found the `sa.samples(n_samples)` method, but it does not generate the configuration I want.

**Comment by gcarleo** [comment]
if you are using the same sampler, then indeed ```sa.samples(n_samples)``` will generate n_samples starting the markov chain from the latest state you have been sampling from (but please check the code for ""samples""" to see if the method "reset" is called). If reset is not called (and I think it is not called), then I would definitely expect that among the new samples generated you will find your state, unless your distribution is not strongly peaked around the state you want

**Comment by PhilipVinc** [comment]
@VolodyaCO If I recall correctly the answer to your question is `gs._samples`

**Comment by gcarleo** [comment]
@PhilipVinc ```gs._samples``` might give the last samples used in the Vmc but it's a private property so I wouldn't use it :) Sampling fresh samples from the sampler should work in this case though

**Comment by VolodyaCO** [comment]
`sa.samples(n_samples)` calls reset with a False argument (then it doesn't reset). This is how I'm printing the configurations in the sample:

```python
samples = []
for sample in sa.samples(100):
    samples.append(sample)
samples = np.array(samples)
samples_r = samples.reshape((-1, samples.shape[-1]))
unique_samples = lexsort_based(samples_r)
print(unique_samples)
```

where

```python
def lexsort_based(data):
    """
    based on https://stackoverflow.com/a/31097280/4107770
    """
    sorted_data =  data[np.lexsort(data.T),:]
    row_mask = np.append([True],np.any(np.diff(sorted_data,axis=0),1))
    return sorted_data[row_mask]
```
I'm still not getting the correct state within the sample. I know that the sample throughout the vmc contains this state because the ground state is a single configuration. If the sample didn't contain this configuration, the energy would be different than -3.5. When I sample I'm getting these two distinct samples:

```bash
Configuration [ 1.  1.  1. -1. -1.]
has relative log coefficient 4.025+0.000j
with energy 0.5000.
*-.-*-.-*-.-*-.-*-.-*-.-*-.-*-.-*-.-*
Configuration [ 1.  1.  1.  1. -1.]
has relative log coefficient 6.727+0.000j
with energy 5.5000.
```
where the energies are computed exactly. Clearly this new sample will not reproduce the -3.5 energy achieved at the end of vmc training.

**Comment by VolodyaCO** [comment]
@gcarleo I have printed at every iteration the generated samples. Indeed the configurations are quite strange. I have now this question. If sigma z is this matrix [[1, 0], [0, -1]], then it has two eigenstates: |+1> = [1, 0] with eigenvalue +1 and |-1> = [0, 1] with eigenvalue -1, right?

If I have, say 3 nodes in the states |+1>, |+1>, |-1>, then the state of the 3 node system would be |+1, +1, -1>. This configuration is shown by netket as [1,1,-1]? It seems to me netket is showing it as [-1,-1,1].

From my last comment, this configuration:
```bash
Configuration [ 1.  1.  1.  1. -1.]
has relative log coefficient 6.727+0.000j
with energy 5.5000.
```
where 1 is mapped to [1, 0] and -1 is mapped to [0, 1] has energy 5.5. But if I map them the other way around, I get an energy of -3.5.

Here's my code (for the first mapping):

```python
def get_relevant_states(machine, num_states, hamiltonian, latest_samples):
    
    spin2vec = {-1.: basis(2, 1), 1.: basis(2, 0)}

    # Initialise the Hamiltonian as a qutip object
    length = hamiltonian.hilbert.graph.n_nodes
    Ham = Qobj(hamiltonian.to_sparse(), dims=[[2]*length, [2]*length])

    # Create a bunch of samples (configurations)
    samples_r = samples.reshape((-1, latest_samples.shape[-1]))
    unique_samples = lexsort_based(samples_r)

    # Get the wavefunction coefficients
    coeffs = machine.log_val(unique_samples)

    # Order configurations according to the energy
    energies = np.array([expect(Ham, tensor(*[spin2vec[spin] for spin in config])) for config in unique_samples])
    sorted_idx = np.argsort(energies)[:num_states]

    for config, coeff, energy in zip(unique_samples[sorted_idx], coeffs[sorted_idx], energies[sorted_idx]):
        print("*-.-*-.-*-.-*-.-*-.-*-.-*-.-*-.-*-.-*")
        print(f"Configuration {config}")
        print(f"has relative log coefficient {coeff:.3f}")
        print(f"with energy {energy:.4f}.")
```

So it seems that netket is using 1 to refer to the state [0, 1] and -1 to the state [1, 0]. Is that right?

**Comment by gcarleo** [comment]
@VolodyaCO this is possible, I am trying to understand if there is a sorting issue when defining the local hilbert space in the new version, 3.0 

For the moment I would suggest to use sorted eigenvalues, this should always be consistent

```python
#Using sorted local states
hi = nk.hilbert.CustomHilbert(graph=g, local_states=[-1, 1])

# Using the corresponding sigma_z 
sz = [[-1, 0], [0, 1]]

ha = nk.operator.LocalOperator(hi, sz, [0])
```

**Comment by VolodyaCO** [comment]
Ok. Probably there is a sorting issue then. Do I leave this issue open for the moment?

The answer to my original question is definitely using the `gs.sample` method.

**Comment by gcarleo** [comment]
yes I will put a warning when an unsorted local hilbert space is found in LocalOperator, this is actually pretty important to solve, otherwise people might find some inconsistent behavior if they look at the individual configurations as you are doing

**Comment by PhilipVinc** [comment]
@gcarleo was this sorted out? did you add the warning?

**Comment by PhilipVinc** [comment]
#539 will close this, as it always sorts the local states in a Hilbert space automatically
