### ISSUE TITLE
jitting a complex neural network

### ISSUE THREAD

**Issue by tvieijra** [netket/netket#477]
While experimenting with a complex neural network as a jax machine, I came across compilation issues which impact the performance of optimizing.  The neural network which I am using is pretty complex in terms of code (it contains a nested loop, which is generally hard for jax to compile), but the operations it does are pretty simple and should not take much time.  Indeed, compiling this network in the first optimization step takes a long time.  Doing the first optimization step indeed takes a lot of time due to the initial compilation of functions.  Normally, you would expect that after this first iteration, execution time improves as jax can reuse the jitted functions from the first step.  However, when profiling the code, I observed that at every iteration step, jax has to do an additional compilation, which takes up to 80% of the execution time of a single iteration in my case.  

As far as I can trace it, I think the problem lies in the fact that the array of connected matrix elements has a variable batch size, due to different matrix elements being zero with different samples.  It is known that jax compilation needs a specific shape as input of a function to be jitted and reusing the compiled version for inputs with different shapes is not possible.  Hence, every time an unknown shape is passed to a function to be jitted, jax has to recompile the function.  The fact that the array of connected matrix elements has variable shape, essentially means that the forward pass to compute the log probabilities has to be recompiled every iteration, which becomes a bottleneck for complex architectures.  

I think a fix with minimal impact would be to divide the forward pass of a batch of samples in minibatches with a fixed shape, and padding the last minibatch with zeros.  In this way, every time the forward function is called, its input has the same shape and jax can reuse the compiled function.

**Comment by gcarleo** [comment]
Thanks @tvieijra , @PhilipVinc experimented with something similar for the density matrix case. 
In practice, it should be enough to do 

```python
get_conn_flattened(v._value, sections, pad=True)
```

(notice the option pad=True) when we call get_conn_flattened in ```netket/operator/_local_values.py```

Notice that this trick might work only for some specific Hamiltonians (say, with ```LocalOperator```). Please let us know if this improves the performance

**Comment by gcarleo** [comment]
In case it does, we might want to set the option ```pad=True`` by default, and implement that option in the one or two Hamiltonians who don't support this yet

**Comment by PhilipVinc** [comment]
@tvieijra Out of curiosity, did this work?

**Comment by tvieijra** [comment]
Thanks for the reply,  it does indeed work!  I think it would be a good idea to make this option True by default.  In our case, it speeds up the time of one iteration step by a factor of 20.  We get a similar speedup by writing a custom batching for the `log_val` function.

If I understand the padding correctly, it might however introduce a lot of extra connected elements for some hamiltonians.  So for simpler networks, padding by default might make it slower again.

**Comment by PhilipVinc** [comment]
Ideally we could run a function when you create an hamiltonian to gauge whever padding is worth it or not by looking at the distribution of the connected elements.

Surely we should expose this option somewhere.
