### ISSUE TITLE
Early stop when energy does not get any lower after some number of iterations

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#488]
Hi, I'd like to know if this feature is already implemented somewhere. When sweeping hamiltonian parameters or netket's hyperparameters this feature would be handy to avoid long run times.

**Comment by PhilipVinc** [comment]
No, netket does not support this yet, though I agree this would be useful.

However, adding it would be easy. Would you be willing to contribute this to netket? 
A design I'd like would be adding a new kwarg to `AbstractVariationalDriver.run(...callback=lambda *x: return True)`

The callback should be a function with signature
```python 
def my_callback(step, log_data, driver) -> Bool
```  

and upon returning `True` the optimisation continues, upon returning `False` the optimisation is blocked.

So you could then add it to `abstract_variational_driver.run`

```python
    def run(
        self,
        n_iter,
        out=None,
        obs=None,
        show_progress=True,
        save_params_every=50,  # for default logger
        write_every=50,  # for default logger
        step_size=1,  # for default logger
        callback=lambda *x: return True,
    ):
#... 
        with tqdm(
            self.iter(n_iter, step_size), total=n_iter, disable=not show_progress
        ) as itr:
            for step in itr:

                log_data = self.estimate(obs)

                # if the cost-function is defined then report it in the progress bar
                if self._loss_stats is not None:
                    itr.set_postfix_str(self._loss_name + "=" + str(self._loss_stats))
                    log_data[self._loss_name] = self._loss_stats

                for logger in loggers:
                    logger(self.step_count, log_data, self.machine)
        
                if not callback(step, log_data, self):
                     break
#... 
```

And then you can implement the callback you desire and maybe contribute it too and put it in a submodule `netket.callbacks` or something like that....

**Comment by VolodyaCO** [comment]
Yes, I can do this. Let me find some time this week.
