### ISSUE TITLE
recognize diagonal observable

### ISSUE THREAD

**Issue by dambuck** [netket/netket#503]
Hello,

I wanted to know, if netket realizes if an observable is diagonal or does it always compute the quotient for the local observable? 

Thanks

**Comment by PhilipVinc** [comment]
Hi dambuck,

No, netket does not special case diagonal observables.

**Comment by dambuck** [comment]
hello, 

thanks for answering. Is there maybe an easy way I could "tell" netket that my observable is diagonal? 
Otherwise it might be possible, that computing the observable by hand, by accessing the samples from the sampler is actually faster. This seems a bit like bad practice in terms of using netket though. Are there cleaner ways to speed things up for diagonal observables?

Thanks

**Comment by dambuck** [comment]
Just to add another minor question. I saw that the early stopping has been implemented now. How can I use that feature with my conda-forge installation of netket?

**Comment by PhilipVinc** [comment]
>Is there maybe an easy way I could "tell" netket that my observable is diagonal?
Not at the moment.

> Otherwise it might be possible, that computing the observable by hand, by accessing the samples from the sampler is actually faster
If you really need this speedup, yes. This is how you can do it.

It's an interesting feature to keep in mind, but unless you implement it yourself (I can guide you) I doubt anyone has time for this right now.

**Comment by PhilipVinc** [comment]
> Just to add another minor question. I saw that the early stopping has been implemented now. How can I use that feature with my conda-forge installation of netket?

The netket version on condo-forge is very outdated (v2.1). Everything that has been implemented in the last year is towards the (yet to be released v3.0), and it's not on pip or condo-forge. You are free to use it (and It's very stable) but there is little documentation and we might change the APIs without warning, as it's still in development.

**Comment by dambuck** [comment]
Thank you very much. As I am not too familiar with installing packages from source,  when installing the current netket from source, does the setup.py take care the installation of dependencies like jax or mpi etc?

**Comment by PhilipVinc** [comment]
Yes, setup.py takes care of installing dependencies. 
As this is all unreleased, it changes quite often but quite recently (few days ago) I updated it so that installing with pip the variant `netket[all]` would take care of installing everything.

That error on mpi4jax is because you are on an older version and jax recently got a breaking update. 
Are you sure you are on the latest version (v0.2.6)?

**Comment by dambuck** [comment]
indeed I was running on 0.2.5 because I was using conda, thanks

**Comment by PhilipVinc** [comment]
Closed by #954 

This can now be implemented easily with a custom operator as documented in the documentation about custom operators.

If you feel like that's not possible, please open a new issue with additional details.
