### ISSUE TITLE
Eigenvalues from full_ed

### ISSUE THREAD

**Issue by TimSkaras** [netket/netket#519]
In exact.py the function full_ed is supposed to fully diagonalize a given operator, but the function throws an error if you try to compute the maximum number of eigenvalues.

**Comment by PhilipVinc** [comment]
Hi @TimSkaras  and welcome!
Could you please be more specific and post the full extent of the error thrown?

**Comment by TimSkaras** [comment]
Hello! 

Yes, I'm sorry for not being more detailed. In my code I create a custom Hamiltonian that has 16 elements in its hilbert space (the Hamiltonian is 16x16). I then use full_ed to get all the eigenvalues:

```
# Custom Graph Hamiltonian operator
op = nk.operator.GraphOperator(hi, bondops=bond_operator, bondops_colors=bond_color)

# Find solutions
res = nk.exact.full_ed(op, first_n=16, compute_eigenvectors=False)
```

I ask for the first 16 eigenvalues (so all of them) and the program throws the following error:

```
 File "/home/tim/Documents/HeisenbergModel/J1J2Heisenberg2D.py", line 207, in <module>
    res = nk.exact.full_ed(op, first_n=16, compute_eigenvectors=False)

  File "/home/tim/.local/lib/python3.8/site-packages/netket/exact.py", line 163, in full_ed
    raise ValueError("first_n must be in range 1..dim(operator)")

ValueError: first_n must be in range 1..dim(operator)
```

I believe the bug is that in the file netket/exact.py in v2.1, the function full_ed contains the following code starting on line 162

```
if not (1 <= first_n < dense_op.shape[0]):
        raise ValueError("first_n must be in range 1..dim(operator)")

if compute_eigenvectors:
        w, v = eigh(dense_op)
        return EdResult(w[:first_n], v[:, :first_n])
else:
        w = eigvalsh(dense_op)
        return EdResult(w[:first_n], None)
```

but the first line should really read

`if not (1 <= first_n <= dense_op.shape[0]):`

**Comment by PhilipVinc** [comment]
Sorry for the late reply.
Indeed this is a bug.

However, we are no longer developing Netket v2 by now  and focusing on v3, where this bug is already fixed.
