### ISSUE TITLE
effect of automorphism

### ISSUE THREAD

**Issue by dambuck** [netket/netket#534]
Hello,

is there a way to compare a RBM with automorphisms to one without any automorphisms, but keeping the number of parameters fixed?
So far every automorphism reduces the number of parameters by N. Could I get a RBM with a Nx1 weight matrix without symmetrization? Its just about comparing the effect of using symmetries and I dont want to set alpha to N to get the fully connected RBM. 

Thanks a lot

**Comment by gcarleo** [comment]
you can construct the RBM with ```n_hidden``` instead of ```alpha```, then you can pass an arbitrary number of hidden units that is not necessarily of multiple of the visible units

**Comment by dambuck** [comment]
Thank you, dont know how I could have missed that argument...

**Comment by dambuck** [comment]
Sorry, there is one more thing related to this which is not very clear to me. 
When automorphisms are given to the machine, the parameters shapes are changed. (why is the visible bias set to shape 1 actually), then it seems to me, that the symmetries are enforced in the _set_bare_parameters method. It looks for example like some weights W_ij are set to the same value as Ws_lm of the symmetric weight matrix.  Both arrays are initialized as empty arrays, and passed to set_bare_parameters as array and not as numpy views or some pointer object. So my question is, are you putting constraints on the weight matrix here or what is actually going on in the symmetrization?

The thing is, that I always understood the way of adding symmetries to a RBM 
$\exp \left[ \sum_\alpha \log \cosh \left( b^\alpha + \sum_i W_i^\alpha \sigma_i ^z  \right) \right] $

by summing over the applied symmetry operations in the form of:
$\exp \left[ \sum_{sym} \sum_\alpha \log \cosh \left( b^\alpha + \sum_i W_i^\alpha \sigma_{sym(i)} ^z  \right) \right] $

But I struggle to see the parallels here. 

Thank you very much

**Comment by gcarleo** [comment]
set_bare_parameters is indeed setting the parameters W_ij in a way that they satisfy the symmetry requirements. That function is then putting constraints among the entries of W_ij, in way that some of the are identical

**Comment by gcarleo** [comment]
Is this clear now? I think you might be mixing different ways of imposing symmetries that have been proposed in the literature? The one that is implemented here is the one we used in the first paper, i.e. the weights are taken to be symmetric. There is another way of doing symmetries in which the weights are not taken to be symmetric, but the "total RBM" is taken to be the product of translated versions of itself. In that case the total number of parameters is identical to the RBM without symmetries, and it is not what is implemented here.
