### ISSUE TITLE
Issue with total_sz

### ISSUE THREAD

**Issue by DavidMihaiMMP** [netket/netket#541]
Hi,

I have just started using netket and I'm facing this problem.
Following the tutorials, I am trying to compute the ground state energy of a spin 1/2 system that contains only 2 spins. The Hamiltonian is given as:
`H=s1z+s2z`

By imposing the condition `total_sz=0.0` on the Spin Hilbert space, I expected the result to be 0, but no matter what I do it always returns the value -2.
It seems that this condition is neglected somehow. Could you please explain to me why this happens and what should I modify in order to obtain the desired result? 
Thanks a lot.

Here is my code:
```python
import netket as nk
import numpy as np

g = nk.graph.Hypercube(length=2, n_dim=1, pbc=False)


hi = nk.hilbert.Spin(s=0.5, total_sz=0.0, graph=g)


sigmaz = np.array([[1, 0], [0, -1]])

operators = []
sites = []


for i in range(2):
    operators.append((sigmaz).tolist())
    sites.append([i])

op = nk.operator.LocalOperator(hi, operators=operators, acting_on=sites)

res = nk.exact.lanczos_ed(op, first_n=1, compute_eigenvectors=False)
print("The ground state energy = {0:.3f}".format(res.eigenvalues[0]))
```

I am using netket v.2.1.1

**Comment by PhilipVinc** [comment]
If I recall correctly, Lanczos ignores constraints on the Hilbert space. @gcarleo

**Comment by gcarleo** [comment]
The version you are using did not handle constraints. The last version on
master (3.0) does that instead.
