### ISSUE TITLE
Reduce RAM for measurements

### ISSUE THREAD

**Issue by KieDani** [netket/netket#542]
Hello,

I really like using NetKet and I think it is a really good package. I especially enjoy, that I can easily train my models with a GPU.

I want to use NetKet for rather large Hamiltonians and machines. Therefore, I only use few samples for the training of the machine. This works fine with a GPU.
After the machine converged to the ground state, I want to measure an Observable. To get reasonable results, I need to approximate the wavefunction with many samples.
For the training I use this code: 
```python
gs = nk.Vmc(hamiltonian=my_ha, sampler=my_sa, optimizer=my_op, n_samples=500)
gs.run(n_iter=500)
```
For the measurement I use this code:
```python
gs = nk.Vmc(hamiltonian=my_ha, sampler=my_sa, optimizer=my_op, n_samples=100000)
gs.run(n_iter=20, obs=my_observables, write_every=4, save_params_every=4)
```
I use a current version of NetKet (master branch two weeks ago). You can find my code at https://github.com/KieDani/Masterarbeit

So far, I measure the observable by training the machine with many samples for few iterations. But by doing this, I need a lot of RAM and, therefore, I can not train it on a GPU anymore. This restricts the size of my problem extremely.

Is there any possibility to measure an observable in another way, so that it does not need that much RAM (-> e.g. construct a wavefunction out of multiple smaller batches)? Is it possible to measure the observable without training the machine (-> only doing the forward pass)?

Thank you for helping me.

**Comment by PhilipVinc** [comment]
IIRC, 
```python
O_avg = gs.estimate(O)
```
estimates the observable with the current parameters.

**Comment by KieDani** [comment]
Thank you for your answer,

But the method `exect(my_obs)` does not work and I can not find a method called `exect()` in _vmc.py. What did you mean with `gs.exect()`?

**Comment by PhilipVinc** [comment]
`estimate`

**Comment by KieDani** [comment]
It seems like `estimate` only works with the number of samples I used for the training. 
I get the error `RuntimeError: Vmc driver needs to perform a step before .estimate() can be called. To get VMC estimates outside of optimization, use netket.variational.estimate_expectations instead.`
If I remove the line `gs.n_samples = 1e5`, I do not get an error. But this is of course not what I need.
If I use `netket.variational.estimate_expectations`, NetKet needs a lot of RAM again, so this also does not seem like a good solution.
Is there anything else I could try?

**Comment by PhilipVinc** [comment]
`estimate_expectations` is the best you can do at the moment, as it will only run the sampler once and perform only a forward pass. if you can do 
```python
gs = nk.Vmc(hamiltonian=my_ha, sampler=my_sa, optimizer=my_op, n_samples=100000)
```
then you can surely use `netket.variational.estimate_expectations` with the same number of samples.

Can't you run it several times with whatever you manage and then average the result?

**Comment by KieDani** [comment]
Thank you very much. You are helping me a lot.

It seems like `netket.variational.estimate_expectations` is an improvement, even though it is not exactly what I thought  of.

If I run it 10 times with 10000 samples and compute the average, I will not get a result as good as if I use 100000 samples and compute the result just once (it is like \abs(a + b) \leq \abs(a) + \abs(b)). 
Therefore, I hoped that I could run 10000 samples and just save the output of the machine. I want to do this 10 times and then I load all of the 100000 saved outputs to compute the wavefunction. Consequently, I do not have to keep so many samples in the RAM.

I think something like this would be a great feature to include in NetKet. 
But so far, I will use `netket.variational.estimate_expectations`. This is better than what I did before.

**Comment by PhilipVinc** [comment]
What do you mean exactly with 
>   I will not get a result as good as if I use 100000 samples and compute the result just once
? It should not be the case if you properly set `n_discard` to a good enough value.

I mean, you are literally averaging stuff. Assuming you sampled correctly.

Yeah, of course it would be great to include in netket, 
Contributions are more than welcome.

**Comment by KieDani** [comment]
![number_of_samples](https://user-images.githubusercontent.com/58328535/105837775-74f4c780-5fcf-11eb-9dc0-893ceb10f961.png)
Is this correct? Or is NetKet doing something else?

**Comment by PhilipVinc** [comment]
regarding netket, what you wrote is wrong.
But I'm not sure what you mean exactly with $\ket{\psi_{10^5}}$?

**Comment by gcarleo** [comment]
The variational state itself does not depend on the number of samples you use to estimate the observables, that is clear...

**Comment by KieDani** [comment]
I took a closer look at equation 5 of https://doi.org/10.1016/j.softx.2019.100311
Now, I see, why I was wrong.

Therefore, the best solution is using `netket.variational.estimate_expectations` multiple times with fewer samples. This way, I am able to run it on GPU and still get a good result.

Thank you for your help.
