### ISSUE TITLE
Uniqueness check in lattice.py is faulty

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#547]
Lines 145-146 of `graph/lattice.py` do not work the intended way, as np.unique flattens the array even when turned into a list of tuples. They should be replaced with
```python
uniques = _np.unique(atoms_coord, axis=0)
```
which selects the unique rows of the array.

**Comment by gcarleo** [comment]
thank you @attila-i-szabo

**Comment by attila-i-szabo** [comment]
Thanks for adding this fix to nk3. Would it be possible to add it to the master branch too? It suffers from the same error.

**Comment by gcarleo** [comment]
we will merge nk3 into the master soon... the master is the development branch in any case, hopefully for the stable release (2.1) this wasn't an issue!

**Comment by gcarleo** [comment]
closing this because it's fixed in 3.0
