### ISSUE TITLE
unable to run tutorials

### ISSUE THREAD

**Issue by wu-zewen** [netket/netket#551]
when runing /netket/Tutorials/j1j2.ipynb, faced problems.
For netket installed using `pip install netket`, the error is that "nk.sampler.MetropolisExchange(machine=ffnn, graph=g, d_max = 2), no keyword 'graph'".
For netket installed using the master branch source code, the error is "nk.graph.CustomGraph(edge_colors), no attribute `CustomGraph`".
Is it a version problem? Which version of NetKet should be used?

**Comment by PhilipVinc** [comment]
Hi Wu, and welcome

What is on the website is supposed to be used with the version you install with `pip install` (so v2.X).
The notebook has an error, and that graph argument should be dropped assuming the same graph `g` was used to build your Hilbert space.

--

Netket installed from the master branch (v3) is under development and we will soon™ release a beta version.
The Tutorials have not been updated yet, only the examples.

As the error is telling you, in v3 CustomGraph operator has been removed. It's functionality has been replaced by `nk.graph.Graph(edge=edge_colors)`, I believe, but I have to check

**Comment by wu-zewen** [comment]
@PhilipVinc 
Thanks very much for your answer. This problem solved.

I found that there is no netket.unsupervised API in netket v2.1, which exists in netket v2.0. I think it has been deleted. 
I also found that there is netket.Qsr in v2.1. Is it equal to netket.unsupervised.Qsr? If so, how to use it? Their inputs are different.

**Comment by PhilipVinc** [comment]
`netket.Qsr` is `netket.unsupervised.Qsr`. I don't know what happened at the time...
Check their docstrings: `help(netket.Qsr)`

**Comment by wu-zewen** [comment]
OK, Thanks very much. If they are the same, I think I can figure out how to use it.
