### ISSUE TITLE
Missing Quantum State Reconstruction in 3.0

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#556]
Quantum State Reconstruction (```netket.Qsr``` in the last 2.1 version) is not currently available in the development branch (and soon to be released) v3.0 

Most likely we won't be able to include it in the first beta release of 3.0 but we should target having it in the first stable, non beta release of 3.0

**Comment by PhilipVinc** [comment]
Closed by #1427

**Comment by gcarleo** [comment]
It's nice to be able to close this issue, thank you
