### ISSUE TITLE
Including pytest-benchmark as a dependency while installing with the [dev] option using pip

### ISSUE THREAD

**Issue by rbktech** [netket/netket#558]
In reference to issue #68 on benchmarks, I believe it would be good to add pytest-benchmark to the list DEV_DEPENDENCIES in netket/setup.py

**Comment by PhilipVinc** [comment]
This is already addressed in #539

**Comment by PhilipVinc** [comment]
Ops, no, this is not addressed, of course.
Though If you make a PR with the benchmarks, you can take care of that!

**Comment by rbktech** [comment]
Sure, I will take care of it. Thanks!
