### ISSUE TITLE
Error when using Pauli string operator 

### ISSUE THREAD

**Issue by thorben-frank** [netket/netket#580]
Hey guys, just seen that you released a beta version of netket3. I skimmed over the documentation and ran a first few test and it looks super cool and runs very fast. Awesome work!

However, when I am trying to use the PauliString operator I get the following error: 
<img width="1728" alt="grafik" src="https://user-images.githubusercontent.com/50867386/112296334-19744c80-8c95-11eb-90b3-1ffcc2f91fb1.png">

My code looks the following: 
```python
import netket as nk
import numpy as np
import json
import time

ha = nk.operator.PauliStrings(operators=['XX','ZZ'], weights=[1,3])
hi = ha.hilbert
ma = nk.models.RBM(alpha=1)
sa = nk.sampler.MetropolisHamiltonian(hilbert=hi, hamiltonian=ha)
op = nk.optimizer.Sgd(learning_rate=0.01)
vs = nk.variational.MCState(sa, ma, n_samples=1000)
sr = nk.optimizer.SR(diag_shift=.1)
gs = nk.VMC(hamiltonian=ha,optimizer=op,sr=sr,variational_state=vs)
gs.run(n_iter=250)
```

Best
Thorben

**Comment by PhilipVinc** [comment]
Hi Thorben and thanks for the report.

Indeed `PauliString`s where missing a few makeovers for version 3.
You can already play with the fix by running 
```
pip install 'git+https://github.com/netket/netket.git#fix-paolo'
```

I need to add a few tests, but we will publish a hot fix soon.

**Comment by gcarleo** [comment]
now released on the official pypi

**Comment by PhilipVinc** [comment]
(Just do to update)
```
pip install --pre -U netket
```
