### ISSUE TITLE
Typo in the jax.ipynb tutorial

### ISSUE THREAD

**Issue by meandmytram** [netket/netket#584]
I think there is a typo in the jax.ipynb tutorial. In particular, the first formula should read 

H = -\sum_{i\in\textrm{nodes}}^{L} \sigma^x_{i} + J \sum_{(i,j)\in\textrm{edges}}\sigma_{i}^{z}\sigma_{j}^{z}

instead of

H = -\sum_{i\in\textrm{nodes}}^{L} \sigma^x_{i} + J \sum_{(i,j)\in\textrm{edges}}\sigma_{i}^{z}\sigma_{i}^{z}

with the second index of sigma_z being j, not i.

**Comment by PhilipVinc** [comment]
yep indeed, thanks for spotting that
