### ISSUE TITLE
Implement Group Equivariant Convolutions 

### ISSUE THREAD

**Issue by chrisrothUT** [netket/netket#588]
I plan to implement group equivariant convolutions as described in: http://proceedings.mlr.press/v48/cohenc16.pdf

This requires access to the algebra of the lattice symmetry group in order to map from convolution filters of shape [out_filters, in_filters, n_group] to a linear map [out_filters*n_group, in_filters*n_group].

My current plan is to add a property to Graph called group_algebra which is a tensor [n_group, n_group, n_group] that maps from absolute to relative poses. It will return None aside from a few graphs where I will manually implement it for.  

We also need to modify DenseSymm (which would be the first layer) so that it can output the graph isomorphisms in a particular order; right now it just uses the order NetworkX generates them in.

As an aside, isomorphisms_iter() may have some bugs. See the following code:

g = nk.graph.Hypercube(length=4, n_dim=2, pbc=True)
print(len(g.automorphisms()))
 
I get 384 when it should be 128.

**Comment by gcarleo** [comment]
thanks Chris, looking forward to this implementation in the new version of netket

Why is the automomorphisms() method wrong? that is essentially just the output of networkx... 

Concerning modifying ```DenseSymm``` maybe you can implement this model as a new layer entirely instead? I guess that would be a better solution

**Comment by PhilipVinc** [comment]
I think networkx gives us tons of automorphisms like reflexions, point rotations, and those composed with translations, and you usually don’t want those.

check out @femtobit’s recently added periodic_translations for what I think you might want.

**Comment by fabienalet** [comment]
@chrisrothUT I think it would actually be a good idea.

> g = nk.graph.Hypercube(length=4, n_dim=2, pbc=True)
> print(len(g.automorphisms()))

I don't think this is a bug. It turns out that the 16 sites square lattice graph has accidentally more symmetries than other square lattices graphs (it is also a hypercube of lenght 2 in 4 dimensions I think). And @PhilipVinc since networkx  indeed computes all point-group + translation symmetries, this is probably why you have more symmetries.

From the end user point of view, I think it would be good in netket to have both 'translations only' and 'all automorphisms' options, but this not may be too much to ask.

**Comment by femtobit** [comment]
@fabienalet (@PhilipVinc )

For `Grid`, of which `Hypercube` is a subclass, it is possible to only get the translations:
```python3
>>> g = nk.graph.Hypercube(length=4, n_dim=2, pbc=True)
>>> print(len(g.automorphisms()))
384
>>> print(len(g.periodic_translations()))
16
```

However, while "only translations" and "all automorphisms" are possible, there are of course intermediate subgroups of symmetries (like translations + rotations) etc. I'd be interested in discussing a more general way to expose these different symmetries in NetKet. In particular in such a way that generalizes to different types of graphs (even if specific symmetries have to be implemented manually, it'd be great if the interface was consistent).

Also, in principle, it would be great to be able to get more information on the group elements returned by `.automorphisms()` and `.periodic_translations()` - right now it's just a bunch of indices, there is no way (except manually looking) to reconstruct whether a given operation is a product of two translations, a translation plus rotation etc.

**Comment by chrisrothUT** [comment]
Thanks guys, these are all really good ideas. 

@gcarleo Since the input layer to the G-CNN is just DenseSymm with the group elements ordered correctly and only translation + space group automorphisms, we could have an option in DenseSymm of which automorphisms we want to symmetrize over. This seems like a generally useful property as on the 4x4 2-D hypercube you may not want to average over the 2x2 4-D automorphisms (thanks @fabienalet). This could also be useful if you want to find excited states with partially broken symmetry. 

@femtobit My first instinct is to separate into translations/space group/translations+space group/all automorphisms. According to @PhilipVinc NetworkX can do all of that, so I'll look into it. It's possible that I will have to do the group algebra by hand as we need to have a map from g^{-1}h -> g,h where g and h are group elements.

**Comment by femtobit** [comment]
@chrisrothUT 

> we could have an option in DenseSymm of which automorphisms we want to symmetrize over.

Note that `DenseSymm` supports any array of permutations - the creation function taking the graph is only for convenience -, so to my understanding the only thing needed here is a method to compute the "translation + space group automorphisms" for `Grid`.

I've recently added the code for the `Grid` translations here:
https://github.com/netket/netket/blob/82f55ca753cf45c929db2e93295b7b778dfb3874/netket/graph/grid.py#L125-L146
Extending this method to support space group symmetries (with some "ad-hoc" group algebra) should be doable. Do you want to give it a try?

**Comment by chrisrothUT** [comment]
@femtobit Sure, I can do that. I'm busy today but I'll do it over the weekend

@gcarleo I forgot that DenseSymm just takes whatever permutations you give it not Graph.isomorphisms(). Disregard what I said, DenseSymm doesn't need to be modified at all

**Comment by chrisrothUT** [comment]
FYI I have a working implementation of the G-CNN that makes no reference to the lattice shape, just the abstract SymmGroup object. Will PR when #600 is finished

**Comment by femtobit** [comment]
GCNNs have been added in PR #620.
