### ISSUE TITLE
Cannot fix the total magnetization to an odd value?

### ISSUE THREAD

**Issue by twesterhout** [netket/netket#61]
It seems that something's wrong with MC sampling for odd magnetizations. Example config:
```json
{ "Optimizer": {"Name": "AdaMax"}
, "Hamiltonian": {"Name": "Heisenberg", "TotalSz": 1}
, "Graph": {"Dimension": 1, "Name": "Hypercube", "Pbc": true, "L": 5}
, "GroundState": {"OutputFile": "test", "Diagshift": 0.1, "NiterOpt": 20, "UseIterative": true, "Nsamples": 2000.0, "Method": "Sr"}
, "Machine": {"Alpha": 2, "Name": "RbmSpin"}
, "Sampler": {"Name": "MetropolisHamiltonian"}
}
```
`netket` executable then terminates with the following error:
```
Cannot fix the total magnetization
```
It looks like a bug to me, because clearly 5 spins _can_ have a total magnetisation of 1. Am I missing something here?

**Comment by everthemore** [comment]
If they have quantum numbers +0.5 and -0.5 they won't have total Sz = 1, right? So single basis states can't be made to obey this. Does it work for L = 6?

**Comment by twesterhout** [comment]
> If they have quantum numbers +0.5 and -0.5 they won't have total Sz = 1, right?

Right! It makes sense, thanks. I assumed the one-halves weren't taken into account here but rather absorbed by the weights.

However, if I follow your advice and use `TotalSz = 0.5` instead, I get the very same error. So it seems that there's more to the story.
