### ISSUE TITLE
Implementing Boson Operators

### ISSUE THREAD

**Issue by alidiak** [netket/netket#63]
Hello!

This is just a practical question of how to implement boson operators - such as the creation operator b - and also how to implement correlation calculations. In particular, I am hoping to calculate a two-point correlation operator <b_{i}* b_{i+N/2}> for the 1D Bose-Hubbard model by implementing it in the bosehubbard1d.py tutorial code. In the Netket documentation, it is said that the custom observables are limited to lattice observables with local operators. So does that mean that correlators can't be practically calculated in the code yet or is there a way to do so? 

In the bosehubbard1d.py, so far I have attempted variations along the lines of:

b_dagger = np.diag(np.sqrt(range(1,Nmax+1)),k = -1).tolist()    # creation operator 
b = np.diag(np.sqrt(range(1,Nmax+1)),k = 1).tolist()    # annihilation operator 
zeromat = np.zeros(np.shape(b)).tolist()

twopointcorr=[]
sites=[]
for i in range(L):
    if i==1: 
        twopointcorr.append(b_dagger)
    elif i == round(L/2):
        twopointcorr.append(b)
    else:
        twopointcorr.append(zeromat)
    sites.append([i])

or
for i in range(L):
    hopping_term = (np.kron(b_dagger,b)).tolist()
    sites.append([1,1+L/2])

But these don't really make physical sense and neither do the results.
Any help and advice would be greatly appreciated! Thank you for your time and for creating this library!

**Comment by gcarleo** [comment]
Hi, sure, it is possible to implement the operators/observables you are looking for.
"Local" operator here simply means that it involves a limited number of sites (in your case you have two-site correlators, so this is OK). To define your observables you need to specify in sites the pair of indices your b*bdagger operators are acting on, and in the "operators" list the kronecker product of b and bdagger. There is an example in the "CustomHamiltonian" directory.
