### ISSUE TITLE
[Docs] Improve template for Flax modules automatic Docpages

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#630]
(Up for grabs for anyone who wants to do this)

Docpages generated for flax modules such as our models (RBM, RBMSymm, DenseSymm) are somehow... confused. 
That's because Flax modules have a lot of methods scattered around and the attributes get put a bit everywhere.

Moreover, attributes of the model/layer itself are mixed with attributes common to all flax modules that are not really relevant (name) and attributes from flax that should not be meddled with (scope, parent...)

See for example https://netket.readthedocs.io/en/latest/api/_generated/nn/netket.nn.blocks.MLP.html#netket.nn.blocks.MLP

The way to address this would be to write an auto summary template for Flax Classes and use it when generating the auto summaries of Flax objects.
Our current template for all classes is this one, and it's a good starting point https://github.com/netket/netket/blob/master/docs/assets/templates/autosummary/class.rst

Once a new template has been written, it should be used to generate only flax modules, by specifying the `:template:` argument in auto summary of `docs/api.rst`.

**Comment by Daniel-Haas-B** [comment]
Hi! Both links are broken. Is this issue still up?

**Comment by PhilipVinc** [comment]
Hi Daniel,

I fixed the links and they should point to the correct urls now.
The issue is still up, as all flax modules are rendered very ugly. 
I'm unsure what the best way to solve this is (at times I thought to give up and just hand-write/generate the docstrings of the flax modules), but if you want to give this a try, please do! I think the docstrings as they are now are not very useful.

If you need some guidance on how this works please do ask questions.

By the way, due to the particular sphinx theme we are using, we are stuck on an older version of sphinx. If you can fix this issue but need a more recent version of sphinx it would also be ok, as I can find a workaround for that.

**Comment by Daniel-Haas-B** [comment]
I'll give it some thought!
