### ISSUE TITLE
Worse accuracy of 3.0 comparing to 2.1.0

### ISSUE THREAD

**Issue by SemyonSinchenko** [netket/netket#646]
Hello!

I found that GPU/MPI performance of v3 is nice comparing to v2 but I couldn't achieve the same accuracy of approximation. I tried all the stuff from documentation, I played with Numpy/Jax sampling, I choose different parameters of optimizer and VMC and so on. Finally to exclude all reasons that problem is in the code I created a minimal reproducible example. In the exampled I use v2 and v3 with all the same parameters to estimate the ground state of the spin correlation operator. Both v2 and v3 I ran on CPU  3 times each. Results are the following:

- v2
```
Exact values:
	Energy: -3.6556072403909687
	Correlation: 0.10372078023520734
Results:
	Energies: -3.6531601366152464 -3.6526195111669715 -3.6502824685015427
	Correlations: 0.1044700892857143 0.1037107142857143 0.10489910714285713
```
- v3
```
Exact values:
	Energy: -3.6556072403909567
	Correlation: 0.10372078023520734
Results:
	Energies: -3.6507468010864947 -3.656252723341578 -3.6434605996542846
	Correlations: 0.12014840182648401 0.07819634703196346 0.08547374429223743
```

I created a simple repository where both v2 and v3 code is about 20-30 logical lines (plus about 30-40 lines of import and i/o). Additionally I put in this repository Dockerfiles with v2 and v3 version which I used.

Please help me to find the problem! I really inspired by NetKet v3 but this problem made me sad. I cannot imagine how the variational approximation in v3 could be lower than exact eigenvalue and how so different spins configurations could take so close values of energy. Seems that the problem is in the sampling process but I tried everything from documentation and nothing helps.

Many thanks in advance!

[Link to repository with reproducible examples and Dockerfiles](https://github.com/SemyonSinchenko/NetKetExamples)

**Comment by PhilipVinc** [comment]
Did you check the dtype of your model in netket v3? 
We switched to real-valued dtype in most models in v3, while in v2 the only option was complex-valued.

**Comment by SemyonSinchenko** [comment]
I used `RBMModPhase`

**Comment by gcarleo** [comment]
can you use the same model in both versions? otherwise it's very hard to understand what is going on! (just remember to set dtype=complex) in v3

**Comment by PhilipVinc** [comment]
So you are comparing two different things.
`RBMSpin` is really just an `RBM`. To make a fair comparison you should use `models.RBM`.
Also, you are initialziing your system with random numbers from gaussian of stddev=0.1 in v2, while you are using the default (0.01) in v3

**Comment by SemyonSinchenko** [comment]
I changed:

- `RBMModPhase` -> `RBM` with `dtype=np.complex`
- in v2 I changed sigma from 0.1 to 0.01

With new parameters I computed 3 iterations for v2 and result is the same (correlations 0.10182, 0.10282, 0.10299) and 1 iteration of v3 (correlation 0.04737). Seems that nothing changed significantly...

I push new parameters to the master.

**Comment by PhilipVinc** [comment]
Hmm...
So I assume np.complex means np.complex128 and not np.complex64? I’ve never used it and I don’t have a computer with me right now.

Assuming the above...
The other differences are that v3 cannot use cholesky (it would be a nice addition) but uses iterative Cg. I think you can make the old code use it, though I doubt it will make a difference...

I’m pretty sure the default diagonal shift is the same, 0.01...

I need to think about this. I’m not sure what might be causing the regression.

@femtobit do you spot anything?
Il 22 apr 2021, 18:23 +0200, Semyon ***@***.***>, ha scritto:

**Comment by SemyonSinchenko** [comment]
@PhilipVinc I found this warning in logs:
```
nqs.py:29: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
```
Seems `np.complex` is python `complex`.

**Comment by gcarleo** [comment]
I just ran a slightly modified script and found Energy=-3.65311+0.00007

**Comment by gcarleo** [comment]
main differences hes 

```python
        ma = nk.models.RBM(alpha=4, dtype=np.complex128)
        opt = optax.sgd(3e-2)
        sa = nk.sampler.MetropolisSampler(hilbert=hi, rule=nk.sampler.rules.LocalRule())
        vmc = nk.driver.VMC(
            hamiltonian=op,
            optimizer=opt,
            variational_state=nk.variational.MCState(
                sampler=sa,
                model=ma,
                n_samples=2000,
            ),
            sr=nk.optimizer.SR(),
        )
````

**Comment by gcarleo** [comment]
with momentum it converges faster actually, the plot below is for 4000 samples, n_discard =200

```python
        ma = nk.models.RBM(alpha=4, dtype=np.complex128)
        opt = optax.sgd(3e-2, momentum=0.9)
        sa = nk.sampler.MetropolisSampler(hilbert=hi, rule=nk.sampler.rules.LocalRule())
        vmc = nk.driver.VMC(
            hamiltonian=op,
            optimizer=opt,
            variational_state=nk.variational.MCState(
                sampler=sa, model=ma, n_samples=4000, n_discard=200
            ),
            sr=nk.optimizer.SR(),
        )
        vmc.run(n_iter=1000, save_params_every=100, write_every=100, out="tmp")
```
all seems OK to me? the energy is occasionally below the exact one, but that's within 4 sigmas of error, by eye, so it's most likely statistical fluctuations 

![Figure_1](https://user-images.githubusercontent.com/28149892/115754838-eb218400-a39c-11eb-895b-02f7c54c322d.png)

**Comment by SemyonSinchenko** [comment]
@gcarleo I wrote that the energy converged right. The main problem is spin-spin correlations op.

**Comment by gcarleo** [comment]
also notice that you were doing something like 
```python
vmc._variational_state.sample(n_samples=3500, n_discard=2000)
```

which means that of the 3500 samples you are actually discarding 2000, and using only 1500 to compute observables...

**Comment by gcarleo** [comment]
it's true that towards the end of the optimization the sampling seems to have some ergodicity issues, that's why the energy is often lower than the exact one. I am not sure what is the origin of this (maybe a strongly polarized phase where single spin flips are not enough?) one would need to check the acceptance rate etc...

**Comment by PhilipVinc** [comment]
@gcarleo your argument on the n_discard is not valid though. N_discard is on top of the samples you consider...

**Comment by SemyonSinchenko** [comment]
> also notice that you were doing something like
> 
> ```python
> vmc._variational_state.sample(n_samples=3500, n_discard=2000)
> ```
> 
> which means that of the 3500 samples you are actually discarding 2000, and using only 1500 to compute observables...

The same thing worked nice in v2:
```python
estimated_zz = nk.variational.estimate_expectations({"zz": zz}, sa, 3500, n_discard=2000)["zz"]
```
and I kept it in v3.

Anyway I made the following changes in v3:

- `np.complex` -> `np.complex128`
- `n_samples` from 2000 to 4000
- `n_discard`  to 200
- `n_samples` in `vmc._variational_state.sample` from 3500 to 4000 and `n_discard` from 2000 to 200

Unfortunately result is still worse than in v2 (with only 2000 samples in sampler):

- Energy converged nicely: -3.65653 (-3.65561 exact)
- Sz-Sz correlation is still bad: 0.13175 (0.10372 exact)

**Comment by gcarleo** [comment]
This is what you get with ```ExactSampler``` (and only 1000 samples) 

E (exact): -3.65543(-3.65561)
Correlations (exact): 0.10443(0.10372)

The issue is really that ```MetropolisLocal``` is not ergodic (that's why your energy is also lower than the exact one, even with many more samples). I would use a sampler that is more effective on this model, for example you can try parallel tempering or ```MetropolisHamiltonian``` I am just not sure why in 2.0 you seem to find a better result, but most likely that is a random fluctuation in the training

**Comment by PhilipVinc** [comment]
It might be worth looking at what states are generated at the beginning of the chain.
I remember that the old code was resetting the chain in more cases than the new one is (which by default never does).

You could try to change the sampler on the variational state before computing the final observables, which forces it to completely reset the chain:
```python
vstate.sampler = vstate.sampler
```

And repeat the process a bunch of times.

**Comment by gcarleo** [comment]
Indeed, changing to a sampler that does double spin flips etc it works... I think that the issue is that your hamiltonian's ground state has fixed magnetization, thus if you use a single spin flip sampler you just never (almost) accept the moves and the samples are just wrong. The same thing would happen on the Heisenberg model for example.  

E (exact): -3.65457(-3.65561)
Correlations (exact): 0.10390(0.10372)

```python
        sa = nk.sampler.MetropolisHamiltonianNumpy(
            hilbert=hi, hamiltonian=get_samp_op(SITES, hi)
        )
```
with
```python
def get_samp_op(n: int, hilbert: nk.hilbert.Spin) -> nk.operator.LocalOperator:

    ham = nk.operator.LocalOperator(hilbert, dtype=np.complex)

    for i in range(n - 1):
        k = i + 1
        ham += nk.operator.LocalOperator(hilbert, sx, [i])
        ham += nk.operator.LocalOperator(hilbert, np.kron(sx, sx).tolist(), [i, k])
        ham += nk.operator.LocalOperator(hilbert, np.kron(sy, sy).tolist(), [i, k])

    return ham
```

**Comment by PhilipVinc** [comment]
Inspecting the acceptance rate `state.sampler_state.acceptance` is always a good idea...

**Comment by SemyonSinchenko** [comment]
Thanks! I ll try Metropolis-Hamiltonian sampler!

**Comment by gcarleo** [comment]
apart from acceptance ratio, another strong indicator of lack of convergence is the fact that towards the end you start getting things like ```R̂=1.40``` for the [R hat](https://rdrr.io/cran/asbio/man/R.hat.html) . This should be really very close to 1, anything larger or smaller than 1 means that the sampling is off because of ergodicity. Anyways, @PhilipVinc do you think it is a good idea to start a FAQ on the website with general troubleshooting suggestions?

**Comment by PhilipVinc** [comment]
Yes, of course.
A new page called something like `FAQ: My simulations don't work` would be a good idea.
This is a prime example.

**Comment by femtobit** [comment]
Indeed it would be great to have some troubleshooting advice for MC convergence, including some tips how to use better sampler than MetropolisLocal for a given problem, and also highlight the `R_hat` diagnostic and what values to expect. A `R_hat` of 1.4 is quite bad already in my experience (I've seen this e.g. when one of the chains was stuck in one state in the Heisenberg model), which is not really intuitive.

**Comment by SemyonSinchenko** [comment]
Could you help me one more time please?
Trying `MetropolisHamiltonianNumpy` I got something strange:
![image](https://user-images.githubusercontent.com/29755009/115842555-9cb8c780-a426-11eb-9f45-7b455cefa3fa.png)

My changes (like in @gcarleo advice):
![image](https://user-images.githubusercontent.com/29755009/115842361-6aa76580-a426-11eb-93e4-1e2077831886.png)

Please could you explain me what do I wrong? Many thanks in advance!!!
