### ISSUE TITLE
[RFC] Redesigning SR interface (3.0 or later?)

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#649]
Me and @gcarleo were recently discussing the fact that we should also redesign the interface used to access the S matrix and to perform Stochastic Reconfiguration Natural Gradient.

The aim is to achieve easier extendability (so that anyone can write his own version of the S matrix if he wants) and composability (play well with solvers from jax/scipy and others, possibly without requiring to wrap them as it's needed now).

This Issue wants to discuss two items:
 - Whever we should do this redesign for v3.0, when to deprecate the old interface, or if we should put it on hold for a v3.1 or 3.2 later.
 - The design of the new system

To recap, the current interface is the following:

- A SR object holds settings on the type of S matrix representation used (dense, lazy-onthefly, lazy-jacobian...) and the algorithm used to solve Sx=F. Every object should correspond to only 1 set of choices (lazy-onthefly+cg, lazy-onthefly+gmres, ecc...) . In netket v3.0b1 there is only one possible representation of the S matrix so that was not a big issue.
  - As shown in the PR #648, this design has issues, as adding a new type of S matrix representation (lazy-jacobian in the PR) requires either duplicating all the types corresponding to solvers, which is inconvenient
  - The natural thing to do would be to split the S matrix representation from the solver used.

- The SR object can build the S matrix itself if it's given a variational state `S = sr.create_S(state)`.
- The S matrix keeps a reference to the SR object, so that you can do `S.solve(F)` and it will use the parameters from the sr object.

```python
sr = nk.optimizer.sr.LazyCG(diag_shift=0.01, maxiters=100)
S = vstate.quantum_geometric_tensor(sr) # equivalent to S = sr.create(vstate)
_, F = vstate.expect_and_grad(ham)

x, info = S.solve(F) # uses an inner field S.sr for the parameters and solve function
```

While the system described above, where all configuration is stored in a single structure, it makes it rather easy to use SR inside of a driver, as we can simply pass 

```python
gs = nk.VMC(ham, optim, variational_state=vstate, sr=sr)
```

and inside the  driver will use this object like shown above.

--

Tentative new design:

Goal: be able to use scipy/jax solvers out of the box.

- Every kind of SR matrix has it's own constructor. `SMatrixOnTheFly(vstate)`, `SMatrixJacbian(vstate)` etcetera that can be used explicitly.
- An helper function `SMatrix(SMatrixType, vstate) = SMatrixType(vstate)` is provided. If SMatrixType is not passed some sensible default representation that always works is used.
- `vstate.quantum_geometric_tensor()` will now take as input the `SMatrix` type and relay the call to the type. If no type is passed, a sensible default is used.

- All S matrix must have the methods `__matmul__` and `__call__` supporting both PyTrees and dense vectors, so that the matrix can be passed to sparse solvers.

With this, what is below should work.
```python
S = SMatrixOnTheFly(vstate)
x, info = jax.scipy.sparse.cg(S, F, maxiter=100)
```

A question arises: we often regularise the S matrix to have a shift in the diagonal. To support it under this API, we should also ask all implementation of the S matrix to support `___add__(self, x:Number)` and keep the diagonal shift in memory (if it's a lazy representation) or simply add it to the dense matrix if it's a dense representation.

Some implementations might even support `__mul__` or other conditionings.

We will then be able to do 
```python
S = SMatrixOnTheFly(vstate)
S = S + 0.01 # equivalent to S.diag_shift+=0.01
x, info = jax.scipy.sparse.cg(S, F, maxiter=100)
```

(Note: this is inconsistent with numpy api, where adding a number to a matrix adds it to all the entries in the matrix, but is consistent with our implementation of LocalOperators where adding a number to a local operator only adds it to the diagonal).

We could even get this to work with scipy (not jax) sparse solvers if we also implement `S.shape` to report the number of parameters.

```python
S = SMatrixOnTheFly(vstate)
# assuming S.shape = (vstate.n_parameters, vstate.n_parameters)
S = S + 0.01 # equivalent to S.diag_shift+=0.01
F_dense, F_unravel = nk.jax.ravel(F)
x, info = scipy.sparse.cg(S, F_dense, maxiter=100)
```

or even

```python
S = SMatrixOnTheFly(vstate)
S = S + 0.01 # equivalent to S.diag_shift+=0.01
Sm1 = np.linalg.pinv(S.to_dense)
x = Sm1@F_dense
```

So all seems great!
The only thing we need to think about is how to make all this play with the Driver API.

How to support this? we could accept two kwargs in the drivers:
```python
 - S_type: Optional[SMatrixType] = The type of the S Matrix you want to use, that should support doing `S = S_type(vstate)` 
 - SR_solver: Optional[Callable] = The function to solve the linear system Sx=F. It must have signature SR_solver(S:SMatrix, F:PyTree, **kwargs) -> Tuple[x:PyTree, info:Any] 
```

If both are not declared (None) sr is not used. If one of the two is passed we use SR and the unspecified kwarg goes to a default.
Internally we could do something like

```python
def __init__(S_type=None, SR_solver=None):
   if S_type is None and Sr_solver is None:
     self.use_sr = False
   else:
     self.use_sr = True

   if use_sr = True and S_type is None:
     S_type = default
   ...


def _forward_and_backward(self):
    """
    Performs a number of VMC optimization steps.
    """

    self.state.reset()

    # Compute the local energy estimator and average Energy
    self._loss_stats, self._loss_grad = self.state.expect_and_grad(self._ham)

    if self.sr is not None:
        self._S = self.S_type(self.vstate)

        # use the previous solution as an initial guess to speed up the solution of the linear system
        x0 = self._dp if self.sr_restart is False else None
        self._dp, self._sr_info = self.SR_solver(self._S, self._loss_grad, x0=x0)
```

For the user, to specify kwargs of the solver like we do now, he would need to consult the docs of that solver and specify it with a `functools.partial`. Example:

```python
from functools import partial

SR_solver = partial(jax.scipy.sparse.gmres, maxiter=300, restart=10)

# use default S_matrix type
gs = nk.VMC(ham, optim, variational_state=vstate, SR_solver= SR_solver) 
# or
gs = nk.VMC(ham, optim, variational_state=vstate, SR_solver= SR_solver, S_matrix=nk.optimizer.sr.SJacobian) 
```

However how to include the diagonal shift? One would have to do 
```python
def srsolver(S,F,**kwargs):
   return jax.scipy.sparse.gmres(S+0.01, F, **kwargs)

SR_solver = partial(srsolver, maxiter=300, restart=10)
```

which is not too clean...

**Comment by gcarleo** [comment]
oh I like this a LOT! 

just quick comment, also related to the last issue you raise. 
I think that it is the job of the solver to know about the diagonal shift, in the sense that most sparse solver implement the solution of linear systems with Lˆ2 penalty, and you specify in the solver the lagrange multiplier for the Lˆ2 penalty, which is exactly the diag shift. so, in a sense, gmres and the others should already support this internally

**Comment by PhilipVinc** [comment]
I see your point about the L2 penalty being the same as the diagonal shift (Still I'd like to check if numerically it is indeed the same...)

However by looking at scipy I don't see this [scipy.sparse.linalg.cg](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html) or [gmres](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.gmres.html)

**Comment by gcarleo** [comment]
yes it is a bit unfortunate, the "reference"implementations of these softwares all have the option to add a shift 
https://stanford.edu/group/SOL/software/minres/

**Comment by gcarleo** [comment]
this might just mean that we need to define another solver that is regularized and wraps the scipy one... ?

**Comment by PhilipVinc** [comment]
One advantage of this design is that we can avoid wrapping things (means less things that can break for us...) so I'd strive for that.

We could export a function
```python
def shift_diagonal_first_inpu(fun, eps):
    def _fun(S, *args, **kwargs):
        return fun(S+eps, *args, **kwargs)
    
    return _fun
```

and then you can use it 
```python
SR_solver = shift_diagonal_first_inpu(partial(srsolver, maxiter=300, restart=10),  0.01)
```

but that is ugly...

**Comment by PhilipVinc** [comment]
It's also a matter of sensible defaults.
In VMC it's usually a bad idea not to regularise the S matrix. 
So we need to find a way to instruct users to regularise solvers...
And users don't read the docs or docstrings.

**Comment by attila-i-szabo** [comment]
Using the L^2 penalty in the solvers would have ramifications for the lazy-Jacobian implementation or any others that allow for scaling the diagonal offset according to the gradient magnitudes (which is good practice especially for heterogeneous ansätze). In this case, you either scale the inputs and outputs (as I did in #648) or use a different offset for each diagonal entry, which would probably be too much for the solvers. Also, it would be good to explicitly precondition in this latter case, so we should think of a transparent way of supplying it from the `SRMatrix` object. Finally, the implementation of #648 is not in terms of pytrees (which is natural and probably more efficient), so I'm not a fan of running the solver using a matrix-pytree product that needs to ravel and unravel vectors in every iteration. Do you think having a `solve` routine would make things too opaque?

**Comment by PhilipVinc** [comment]
> Do you think having a solve routine would make things too opaque?

It makes the S matrix not a _standard_ object. So you have to know how to use it.
Counter to the API proposed in the OP (which apparently has issues) that would make the S matrix behave as a standard matrix you can throw at all normal solvers. That is what I'd like to achieve but... yeah. Let's see if it's possible.

Otherwise, we could make the S matrix provide a sort of `pre_solve` `post_solve` to do preprocessing on the y in Sx=y (effectively ravelling and unravelling in your case), this could be used inside netket, but again it's a weird api...

@inailuig Do you think it's possible to write the S@x product while storing the gradient but using `tree_map` & co and working at the level of the PyTrees (without jvp/vjp)?

**Comment by attila-i-szabo** [comment]
So if it comes with `__matmul__` and `__call__` routines, it is can still be thrown at solvers the usual way, it'd just be less efficient than using the `solve` routine. (And we can always provide a trivial implementation of `solve` in a superclass.) Also, there are very few places where these objects would be called, so the only limitation in it being nonstandard is when one wants to extend with their SR implementation...

As for your last question, it's entirely possible to calculate the gradients as a pytree, you'd have to tweak my code to look more similar to JAX's implementation `jacrev`. It's more that doing a huge matrix-vector product is probably more efficient than doing it in many smaller pieces on pytrees of high-dimensional tensors...

**Comment by attila-i-szabo** [comment]
An alternative for making things more standard: `LazySMatrix` provides `_rtruediv_` which I guess translates to a division operator of sorts. We could reference that where it's needed in NetKet, albeit that would require you to choose the solver before getting there...

**Comment by inailuig** [comment]
> @inailuig Do you think it's possible to write the S@x product while storing the gradient but using `tree_map` & co and working at the level of the PyTrees (without jvp/vjp)?

yep this is doable. Will post some code soon.

**Comment by attila-i-szabo** [comment]
@inailuig I'm not very familiar with JAX's ability to optimise over PyTrees, so I wonder if this would be much less efficient than storing the gradient as a matrix and doing one ravel/unravel at the start/end of `solve()`? Although my implementation has to unravel vectors when computing the gradient, so that might offset it...

**Comment by PhilipVinc** [comment]
(Copy pasting from the other PR...)

In short, the reason for `.solve` to exist is that some S matrix implementations might work better in the PyTree basis or in the dense-ravelled basis, even if they work with both.

For example:

- the current OnTheFly implementation works in the PyTree basis, and if you multiply it by a dense vector it will convert it to a PyTree (unravel), perform a matmul then ravel the result.
- Attila's JacobianSMatrix, which works in the dense basis. If you multiply it by a PyTree vector it will first ravel it, perform the matmul, then unravel the result. This means that to use it in a solver you could, in principle, just use it as-is, but you'll get better performance if you ravel the PyTree before calling solve, and unravel the result of solve, rather then ravel-matmul-unravel at every solver iteration.

Also, Atiila raises the point that some SMatrices might know how to precondition themselves, and those preconditioners are better applied by manipulating the y vector in the `Sx=y` equation before calling the solve method.

**Comment by inailuig** [comment]
> > @inailuig Do you think it's possible to write the S@x product while storing the gradient but using `tree_map` & co and working at the level of the PyTrees (without jvp/vjp)?
> 
> yep this is doable. Will post some code soon.


Have a look at https://github.com/netket/netket/pull/652 for the pytree version.

---

> @inailuig @PhilipVinc I'm not very familiar with JAX's ability to optimise over PyTrees, so I wonder if this would be much less efficient than storing the gradient as a matrix and doing one ravel/unravel at the start/end of `solve()`? Although my implementation has to unravel vectors when computing the gradient, so that might offset it...

In principle both are doing exactly the same number of floating point operations (at least for homogeneous parameters), just that the flattened one might have slightly better locality. But assuming the leave arrays are not too small I would not worry about this too much, however we should to benchmark it to find out (also especially on the GPU). I did some benchmarks on the cpu a while ago and iirc the matrix-vector product like you implemented it with jax wasn't running anywhere near peak performance anyway...

**Comment by attila-i-szabo** [comment]
### Some thoughts on the `solve` method and how to supply the solver thereto

A major source of ugliness in the existing SR interface and that in #648 and #650 right now is that there are several SR classes (`SRLazyCG`, `SRLazyGMRES`,...) that only differ by the solver supplied to them. Other than just being ugly, this limits the solvers one could use (I think there are other ones even in `jax.scipy.sparse.linalg`, but we don't need to limit ourselves to that either). The only upshot to these classes is that they allow passing parameters that are only taken by one kind of solver.

Instead of this setup, I'd recommend having a single `SRLazy` class (and so on for other implementations), with an extra field `solver`. In the simplest implementation, this would be a `Callable` that takes the kinds of argument that are now passed in the base `SRLazy` class (such as preconditioner), which we might want to supply directly. We can still pass the solver-specific arguments by `partial`ing this function - I suppose this is done rarely enough that having an ugly interface for it is OK.

It would also make sense to keep some "sensible defaults" so we can set up CG or GMRES without typing out the full function name. Therefore, I'd make`solver` a `Union[str, Callable]` to allow passing parameters like `"cg"` or `"gmres"` which would then default to a particular way of calling the CG and GMRES solvers. This would largely replicate the functionality of the existing subclasses, but more elegantly.

**FAQ: but why add this to the SR class at all?**

* See the arguments for having a `solve` routine above. We must supply a solver for such a routine
* We have to specify a solver _somewhere_. We can either do it here or in the `Vmc` class, where the inverted S matrix gets used, but since the solver is an implementation detail of the SR algorithm as opposed to the whole VMC optimisation, it is more natural to add it to the SR class.

@PhilipVinc  @inailuig @gcarleo what do you think? I could do this with the `SRJacobian` classes and maybe the `SRLazy` ones, hopefully not breaking anything in the process!

**Comment by attila-i-szabo** [comment]
Also, it might make sense to introduce an `SRIterative` class in the hierarchy of SR objects just below the basic `SR` class. This would keep all the solver-related fields (`solver` and common parameters like preconditioner) and implement `solve_fun` that translates the string `solver` options to actual solvers and `partial`s them with the parameters of the object. This would then be subclassed by both `SRLazy` and `SRJacobian`. Alternatively, we could add all of this to `SR` but that precludes a dense matrix implementation altogether  -- not that that would be a huge problem, but having a step in the hierarchy might be more logical still.

**Comment by PhilipVinc** [comment]
Sorry, I wanted to answer you this morning but I forgot...

>A major source of ugliness in the existing SR interface and that in #648 and #650 right now is that there are several SR classes (SRLazyCG, SRLazyGMRES,...) that only differ by the solver supplied to them

Indeed. The idea I presented is to decouple the solver from the S matrix itself.

> Instead of this setup, I'd recommend having a single SRLazy class (and so on for other implementations), with an extra field solver

My proposal was to have the SRLazy class be just a linear operator. Then you can call `myfancysolver(SRLazy, y)` (bad performance) or `SRLazy.solve(myfancysolver, y)` (guaranteed good performance). Arguments to the solver are `partial`ed. We can provide thin wrappers `partial` with decent defaults.

The point is that we do not need to store the solver itself in the `SRMatrix`. The `SRMatrix` just needs to know how to play well with solvers, nothing else.

We were discussing this a bit further, keeping in mind that we might also implement other techniques such as Block-diagonal Hessian optimisation or others.
Those are all preconditioners to the gradient. The preconditioning requires 2 things, the solver (that is only a function + syntactic sugar) and the format/wayto compute the S matrix/Hessian/whatever. 

If we decouple everything, implementing BDHessian optimisation is only about writing the new class for the block diagonal hessian, and everything else will support it out of the box.

**Comment by attila-i-szabo** [comment]
> My proposal was to have the SRLazy class be just a linear operator. Then you can call `myfancysolver(SRLazy, y)` (bad performance) or `SRLazy.solve(myfancysolver, y)` (guaranteed good performance). Arguments to the solver are `partial`ed. We can provide thin wrappers `partial` with decent defaults.

Ahh I see now. This sounds good indeed. There are just two more design choices to be made:
* Where do we put the wrappers? They would be quite important to make life comfortable for users. Say, we open an `nk.optimizers.SRSolvers` module?
* How do we pass the information about the solver on to `Vmc`? We could either make a separate kwarg for it (which is a bit wasteful seeing it also supports non-SR usage) or make the `sr` argument into an `(SR, solver)` tuple. It would also be good to support an absolute default solver, so the user doesn't have to pass one if they don't care.

**Comment by PhilipVinc** [comment]
I was discussing that with @gcarleo and we propose:

 - Rename `AbstractSRMatrix` to something like `AbstractLinearOperator` or `LinearOperator`. Put it somewhere (not sure where). not netket.jax though as it does not really make sense there
 - Rename `SJacboianMatrix` to `QGTJacobian` and `SOntheFlyMatrix` to `QGTOnTheFly`. Write docs somewhere to make it clear that quatum geometric tensor == S matrix of SR. 
 - Put those `QSTBLABLABLA` inside `netket.optimizer.qgt`.
   - I had also proposed `nk.qgt` but giuseppe did not like it. 
 - In principle we don't provide any solver. In practice we will give a bunch (to give good defaults and the diagonal shift as a kwarg) and we put those things in something like `nk.optimizer.linalg` (better proposals?) because those are not specific to SR
 - Also provide `nk.optimizer.SR(solver, matrixtype)` object to combine the two things together. It's just some syntactic sugar to constructing a tuple with defaults for what you don't specify, containing the solver and the matrix type.
 - Drivers accept a new parameter `preconditioner`. That is by default none. You can pass `SR()`, `SR(cg(diag_shift=0.1))` or `SR(cg(...), QGTOnTheFly)` or combinations of those objects.

What do you guys think?

**Comment by attila-i-szabo** [comment]
I like this! We could start a `netket.linalg` module (or maybe put it in `utils`, it's not a priori related to `optimizer` though) with the `AbstractLinearOperator` basis class and the "good defaults" solvers.

> * Also provide `nk.optimizer.SR(solver, matrixtype)` object to combine the two things together. It's just some syntactic sugar to constructing a tuple with defaults for what you don't specify, containing the solver and the matrix type.

It's not just sugar though. In the current implementation, an `SJacobianMatrix` object can't be `__init__`ed from the usual arguments (like `apply_fun`) directly because of the limitations `flax.struct.dataclass` puts on the object (or at least I don't know how to get around it), so `SRJacobian.create()` has to do nontrivial things! 
We can put a factory method into the S matrix class to deal with that, but that would mess with the nice `AbstractLinearOperator` interface... Maybe have a `netket.optimizer.qct.QCT` that subclasses `AbstractLinearOperator` and provides for the factory?

> * Put those `QSTBLABLABLA` inside `netket.optimizer.qgt`.
>   
>   * I had also proposed `nk.qgt` but giuseppe did not like it.

Agreed, it's not quite so fundamental, and I don't see where else we'd use it...

> * In principle we don't provide any solver. In practice we will give a bunch (to give good defaults and the diagonal shift as a kwarg) and we put those things in something like `nk.optimizer.linalg` (better proposals?) because those are not specific to SR

I'm still not fully sold on lumping the diagonal shift with the solver rather than the SR object. Sure, it is the to help with linear algebra, but I'm not sure how transparent that point is to our users who (I think) come from a VMC background and may think that `diag_shift` is properly a part of SR...

**Comment by PhilipVinc** [comment]
> It's not just sugar though. In the current implementation, an SJacobianMatrix object can't be __init__ed from the usual arguments (like apply_fun) directly because of the limitations

Yeah sorry, i did not spell out the whole thing i had in mind. I don't like sr.create().
My idea is that in general `ThisMatrixType(variational_State)` should work and should be the standard way to construct those objects. It can do arbitrary things. This could go through plum dispatch so that if we add new variational state types it's easy to add support for everything.

The simplest way to do this would be to have the actual classes be `QGTJacobianT` and the constructor function be `QGTJacobian` and so on. I don't know if there are more elegant solutions. (btw, we kind of do this for samplers)


About the shift: yes i see your point. 
Still, the shift would be a property of QGTJacobian and others and we can have fancy __add__ so that doing S+0.01 does that, as i proposed in the original post.

Then one can always write `jax.scipy.linalg.solve(QGTJacobian(state) + 0.01, y, maxiter=30)`.
We can provide some wrappers for jax.scipy methods that do just that through a closure.

**Comment by femtobit** [comment]
@PhilipVinc's suggestions in https://github.com/netket/netket/issues/649#issuecomment-829267314 sound pretty good to me.

> It's not just sugar though. In the current implementation, an SJacobianMatrix object can't be __init__ed from the usual arguments (like apply_fun) directly because of the limitations flax.struct.dataclass puts on the object (or at least I don't know how to get around it), so SRJacobian.create() has to do nontrivial things!

Does it have to be a dataclass, though? The fact that the SR objects encompass some non-trivial logic (enough for us needing to implement `SR.create` (or the `QGTJacobianT` / `QGTJacobian` duality) seems to indicate to me that they are maybe just not suitable as dataclasses (which are meant to be essentially fancy `namedtuple`s) and if they aren't we can simplify the creation/initialization logic.

**Comment by PhilipVinc** [comment]
>Does it have to be a dataclass, though?  

Being a (flax) data class allows it to be passed to jax-jitted function with no problems, as a simple object.
It's something I'd like to keep.

I know that having `ThisObjectT` and `ThisObject` is damn ugly. 
The problem is that we cannot override the constructor of data classes. If you have better alternatives, I'm all ears!

Just 2 things on my mind right now: we could override the [`__new__` method](https://stackoverflow.com/questions/54927763/control-initialize-order-when-python-dataclass-inheriting-a-class) maybe. I'll also try to nag flax developers about this now that we have several examples of why this is bad.

**Comment by PhilipVinc** [comment]
@attila-i-szabo @femtobit 
Iterating on the currently proposed design, there is an issue:

The current proposal is that operators should support being passed to standard `scipy` solvers and to jax solvers.
And to achieve better performance, one can call `QSTMatrix.solve(solve_method, y, x0=...)` where solve method must have a scipy linalg sparse solver-like interface.

The question now is: do we jax-jit `QSTMatrix.solve` or not?
If we jit it, we can no longer use it with code that is non jax-jittable (eg: scipy). But if we don't jit it we are losing performance, in a method that is supposed to be performant.

Alternatively, we could ask the user to jit his `solve_method`. And since we will provide our own solve_methods wrapping jax we can make them jitted. 
But is this really the best design?

**Comment by attila-i-szabo** [comment]
> Being a (flax) data class allows it to be passed to jax-jitted function with no problems, as a simple object.
> It's something I'd like to keep.

Seconded. Getting a custom object to play nicely with jit is a pain, keeping it a dataclass makes a big difference.

> I know that having `ThisObjectT` and `ThisObject` is damn ugly.
> The problem is that we cannot override the constructor of data classes. If you have better alternatives, I'm all ears!

One thing which I wasn't sure about: can we pass a class type and a Callable on the same field into the `Vmc` object? I mean, the class constructor is technically a Callable, but I don't know if the typing logic is clever enough for this?

> Just 2 things on my mind right now: we could override the [`__new__` method](https://stackoverflow.com/questions/54927763/control-initialize-order-when-python-dataclass-inheriting-a-class) maybe. 

This seems viable and maybe less ugly than a free-floating factory method... Is the idea then that `__new__()` takes the `vstate` parameter, does the logic, and calls the default `__init__` with the freshly calculated parameters?

> I'll also try to nag flax developers about this now that we have several examples of why this is bad.

That would be great!

> The question now is: do we jax-jit `QSTMatrix.solve` or not?
> If we jit it, we can no longer use it with code that is non jax-jittable (eg: scipy). But if we don't jit it we are losing performance, in a method that is supposed to be performant.

I think we should jit it. Two questions:
* I thought scipy solvers were written in pure python when I last checked -- why can't they be jitted?
* Do scipy solvers even take PyTrees as right-hand sides? If not, this point is pretty moot.

**Comment by femtobit** [comment]
> I mean, the class constructor is technically a Callable, but I don't know if the typing logic is clever enough for this?

Since noting enforces the types, that's not much of an issue in any case. But yes, types are indeed `Callable`:
```python
>>> from typing import Callable
>>> class A: pass
>>> isinstance(A, Callable)
True
>>> issubclass(type(A), Callable)
True
```

**Comment by PhilipVinc** [comment]
>Since nothing enforces the types, that's not much of an issue in any case. But yes, types are indeed Callable:

I'm a bit lost and unsure what this implies.
The problem is that we need the class and a constructor in any case. We cannot have the same name for both (or can we?)

**Comment by attila-i-szabo** [comment]
I just pop this here
```
def SR(QGT = QGTOnTheFly, solver = jax.sparse.linalg.cg, **kwargs):
	return partial(QGT, **kwargs), solver
```
I added actual defaults (`QGTOnTheFly` is better for now because it works OK with any differentiation modes)

**Comment by PhilipVinc** [comment]
So status update. The implementation work in #674 is done and I'm waiting for #689 to be merged back. 
The new code internally is very clean and makes it easy to use an arbitrary function to use SR.

However I think there are still some rough edges on the API. I'd like a comment from @gcarleo too.
The final design that has been settled for is roughly the one described in the post above this one: `SR` is a tuple (actually a NamedTuple) that contains the matrix type used for SR and the solver. 
To build `SR`, in general, you might want to specify both flags/options for the solver and for the QGT matrix. Examples are `maxiter` or `tolerance`, that are flags of solvers, and `diag_shift` or `centered` that is a flag of the QGT.

In the current implementation, the drivers take a tuple of two `functool.partials`, one of the solver with all the flags set, and one with the QGT constructor with all the flags set. 
Essentially, the _raw_ api is the following:

```python
from functools import partial
import jax

solver = partial(jax.scipy.sparse.linalg.gmres, maxiter=100, tol=1e-7)
qgt = partial(nk.optimizer.qgt.QGTOnTheFly, centered=False)
...
gs = nk.VMC(ha, op, variational_state=vs, preconditioner=(solver,qgt))
```

We provide a convenience function (sketched by @attila-i-szabo above) , `nk.optimiser.SR` which builds this tuple and uses some good defaults (the `QGT` is chosen automatically if not specified according to some heuristics, and the solver is cg if not specified)

In principle the convenience function `nk.optimiser.SR` takes as input two optional objects, solver and qgt, and _fills the gap_ of what is not specified with its defaults.
To make life easier to people, we also make it accept arbitrary options relating to the QGT and wrap them in a Partial for QGT only. That means that the code above becomes:

```python
from functools import partial
import jax

solver = partial(jax.scipy.sparse.linalg.gmres, maxiter=100, tol=1e-7)
sr = nk.optimizer.SR(nk.optimizer.qgt.QGTOnTheFly, solver= solver, centered=False)
...
gs = nk.VMC(ha, op, variational_state=vs, preconditioner=sr)
```

I have two issues with this design:
 1. It's somehow asymmetric, and one still has to wrap kwargs for the solver in  a partial. It was argued that one does this much less often for solver kwargs than for SR and that's why we ended up with this design.
 2. it's not entirely transparent to the end-user that additional kwargs to `nk.optimizer.SR` correspond to those of the QGT.

Lastly, in an ideal world we would be adding back to netket the `cholesky` and `svd` solvers for the linear system.
Those are largely 3-liners so we could wrap them in `nk.optimizer.linalg/solver.(cholesky,svd...)` but then we'd have a rather verbose API. Which maybe isn't too bad for now, we can refine and make it less verbose in the future.
But I'd like us to agree on it.

See this example below:it's quite verbose.
```python
from functools import partial
import jax

solver=partial(nk.optimizer.solver.cholesky, threshold=1e-6)
sr = nk.optimizer.SR(nk.optimizer.qgt.QGTOnTheFly, solver=solver, centered=False)
...
gs = nk.VMC(ha, op, variational_state=vs, preconditioner=sr)
```

**Comment by femtobit** [comment]
@PhilipVinc I agree the asymmetry between the treatment of solver and QGT options in `SR` is ugly. In fact, I don't think it is really true in practise that adjusting the solver options is somehow less common than the QGT ones. Things like maximum iterations and tolerance of `gmres` are pretty standard hyperparameters to tune. (Definetly more so that, say, `centered` on the QGT.)

There is a reasonably Pythonic way to treat them on equal footing, though:
```python
sr = SR(
    QGTOnTheFly,
    jax.scipy.sparse.linalg.gmres,
    qgt_options={
        centered=False,
    },
    solver_options={
        maxiter=100,
        tol=1e-7,
    },
)
```
So we just pass an option dict for both.

**Comment by attila-i-szabo** [comment]
> I have two issues with this design:
> 
>     1. It's somehow asymmetric, and one still has to wrap kwargs for the solver in  a partial. It was argued that one does this much less often for solver kwargs than for SR and that's why we ended up with this design.

I don't think we could make it symmetric with a reasonable amount of work. Basically, you'd have to tabulate what kwargs tend to show up in which half, which would keep expanding as we allow for more things.  
My own argument for passing the QGT args rather than the solver ones, if we are down to one of them, is that those affect what the SR is *supposed to do*, rather than tweaking to make it actually do that.

>     2. it's not entirely transparent to the end-user that additional kwargs to `nk.optimizer.SR` correspond to those of the QGT.

I think this is mostly a matter of documentation.

> Lastly, in an ideal world we would be adding back to netket the `cholesky` and `svd` solvers for the linear system.
> Those are largely 3-liners in the new interface, and we could wrap them in `nk.optimizer.linalg/solver.(cholesky,svd...)` but then we'd have a rather verbose API. Which maybe isn't too bad for now, we can refine and make it less verbose in the future.
> But I'd like us to agree on it.

I thought the purpose of wrapping stuff like `cg` in netket was to provide defaults which can be overridden through kwargs, so you'd have stuff like
```
def cg(maxiter=10, tol=1e-7,...):
    return partial(jax.cg, ...)
```
This would make the interface less verbose (or at least less partial-heavy)

**Comment by femtobit** [comment]
> I thought the purpose of wrapping stuff like cg in netket was to provide defaults which can be overridden through kwargs, so you'd have stuff like

This would require us to wrap all solvers in this way, which seems a lot of overhead just for hiding `partial` compared to just passing explicit option dicts...

**Comment by attila-i-szabo** [comment]
> @PhilipVinc I agree the asymmetry between the treatment of solver and QGT options in `SR` is ugly. In fact, I don't think it is really true in practice that adjusting the solver options is somehow less common than the QGT ones. Things like maximum iterations and tolerance of `gmres` are pretty standard hyperparameters to tune. (Definetly more so that, say, `centered` on the QGT.)
> 
> There is a reasonably Pythonic way to treat them on equal footing, though:
> 
> ```python
> sr = SR(
>     QGTOnTheFly,
>     jax.scipy.sparse.linalg.gmres,
>     qgt_options=dict(
>         centered=False,
>     ),
>     solver_options=dict(
>         maxiter=100,
>         tol=1e-7,
>     ),
> )
> ```
> 
> So we just pass an option dict for both and users don't have to use any `partial` if they don't want to (and those who are happy to wrap things in `partial` don't need `SR` anyways).

I think this interface is even clunkier than `partial`ing everything. My idea for supporting something like this was to allow the user to write `SR(diag_shift=0.01)` (or maybe pick the QGT implementation) without having to write out a pile of syntax.

**Comment by PhilipVinc** [comment]
>I think this interface is even clunkier than partialing everything. My idea for supporting something like this was to allow the user to write SR(diag_shift=0.01) (or maybe pick the QGT implementation) without having to write out a pile of syntax.

The `QGTAuto` could still work.  This is only about handling the additional kwargs...

>I think this is mostly a matter of documentation.

True, but most people don't read documentation properly...

>I don't think we could make it symmetric with a reasonable amount of work. Basically, you'd have to tabulate what kwargs tend to show up in which half, which would keep expanding as we allow for more things.

This is the kind of thing I'd want to avoid: it's brittle!

**Comment by PhilipVinc** [comment]
Alternatively, the crazy proposal would be to create a `nk.optimizer.solver` magic module with a bunch of things inside (`svd, cholesky, eigh...` ) and then any unknown symbol can be auto-forwarded to `jax.scipy.sparse.linalg` and wrapped in the partial.

It could work, but... it's also brittle. Maybe easier to use but. Damn it. It's going to create problems later on I think.

**Comment by attila-i-szabo** [comment]
> > I think this interface is even clunkier than partialing everything. My idea for supporting something like this was to allow the user to write SR(diag_shift=0.01) (or maybe pick the QGT implementation) without having to write out a pile of syntax.
> 
> The `QGTAuto` could still work. This is only about handling the additional kwargs...

Sure, I'm just saying that @femtobit's version is more uncomfortable to use than `partial`ing both solver and QGT (especially if they come with sensible defaults so you don't have to partial if you don't want to) and passing it as a tuple.  
Imo we should either make `SR` something that makes life easier for the garden-variety user, or abandon it

> > I think this is mostly a matter of documentation.
> 
> True, but most people don't read documentation properly...

We're talking about users who want to go beyond what's put in front of their faces. Let them read docs!

> > I don't think we could make it symmetric with a reasonable amount of work. Basically, you'd have to tabulate what kwargs tend to show up in which half, which would keep expanding as we allow for more things.
> 
> This is the kind of thing I'd want to avoid: it's brittle!

Agreed!

**Comment by attila-i-szabo** [comment]
> Alternatively, the crazy proposal would be to create a `nk.optimizer.solver` magic module with a bunch of things inside (`svd, cholesky, eigh...` ) and then any unknown symbol can be auto-forwarded to `jax.scipy.sparse.linalg` and wrapped in the partial.
> 
> It could work, but... it's also brittle. Maybe easier to use but. Damn it. It's going to create problems later on I think if jax people change something.

To quote @femtobit:

> seems a lot of overhead just for hiding `partial`

**Comment by attila-i-szabo** [comment]
> This isn't an interface aimed at users who have intimate knowledge of netket...

DIsclaimer: I'm a fan of FFTW's three-tier interface, hiding complications from entry-level users is a Good Thing
