### ISSUE TITLE
Callbacks and MPI Syncronization -> deadlocks. what to do? 

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#651]
Right now the Callbacks are executed on all MPI ranks. That is different from loggers, which are only executed on the root rank.

```python
# Log only non-root nodes
if self._mynode == 0:
  # if out is a path, create an overwriting Json Log for output
  if isinstance(out, str):
    loggers = (JsonLog(out, "w", save_params_every, write_every),)
  else:
    loggers = _to_iterable(out)
else:
  loggers = tuple()
  show_progress = False

callbacks = _to_iterable(callback)
callback_stop = False

for step in itr:
  for callback in callbacks:
    if not callback(step, log_data, self):
      callback_stop = True

    for logger in loggers:
      logger(self.step_count, log_data, self.state)

    if callback_stop:
       break
```

That means that if a callabkack signals the driver to stop the evolution only on one rank (for whatever reason), then that rank will stop while the overs will continue leading to a deadlock.

We have two solutions: run the callbacks only on the root node and then send the signal to stop to all other nodes, or run the callbacks on all nodes, and run `MPI.Allreduce(MPI.LOR)` (logical or) on the `callback_stop` among all ranks so that if at least one signals to stop, all of them stop.

I would go with the latter option `MPI.Allreduce(MPI.LOR)`. @femtobit do you agree?

**Comment by PhilipVinc** [comment]
cc @VolodyaCO  who wrote that code

**Comment by femtobit** [comment]
I agree that the `Allreduce` option is probably the best one. Even where it only makes sense for a callback to run on the root node (which I think is true for `EarlyStopping`, since it only depends on statistics that are already synchronized), there is either not much harm if it is run on all nodes (as it is computationally insignificant) or otherwise we can wrap the code in
```python
if is_root_node:
    # run callback code and return True or False
else:
    return False  # no influence on result
```

**Comment by PhilipVinc** [comment]
I'll open a pr at some point to do that..
