### ISSUE TITLE
Installing Netket 3.0 on Apple Silicon Chips

### ISSUE THREAD

**Issue by JoeyT1994** [netket/netket#666]
I recently installed Netket on a Macbook with an M1 chip - using miniforge3 to install its dependencies and a `pip install --pre netket' for Netket itself.

The version it installed, however, is V2.1.1 and if I uninstall Netket and try to force V3 with pip install netket==3.0b1.post7 I get:

 ERROR: Could not find a version that satisfies the requirement jaxlib>=0.1.57 (from netket) (from versions:none)
 ERROR: No matching distributions found for jaxlib>=0.1.57

Is netket 3.0 dependent on jaxlib but earlier versions of netket are not? I cannot find a version of jaxlib to install in either the conda or pip repositories. Perhaps jaxlib is not supported on the ARM architecture at the moment and this is causing the problem.

**Comment by PhilipVinc** [comment]
> Is netket 3.0 dependent on jaxlib but earlier versions of netket are not? 

yes.

> ERROR: No matching distributions found for jaxlib>=0.1.57

I suspect you installed a native M1 python version.
JaxLib is [not available yet](https://github.com/google/jax/issues/5501) as a _native_ M1 binary, and i think you will have to wait 1 or 2 more months before prebuilt wheels are released.

With that said, I never use conda (and always have problems with it) so i cannot say.
However if you use the x86 version of python you'll be able to `pip install jaxlib` with no problems, as it will be running under rosetta and he thinks it's a standard intel processor. This will allow you to install netket 3. It won't be native but it will run more than fine.

**Comment by JoeyT1994** [comment]
Yes I am currently using a version of python specifically for the M1 architecture.

I will have a go using Rosetta for now then.

Thank you for clearing that up!
