### ISSUE TITLE
On character tables, projections, and equivariance

### ISSUE THREAD

**Issue by attila-i-szabo** [netket/netket#698]
This is a physics bug report of sorts, related to the equivariant network implemented in #620 and implementing #658.

One finds in standard texts on representation theory (e.g. [here](https://www.amazon.co.uk/Group-Theory-Quantum-Mechanics-Introduction/dp/0486458784)) that the operator
(1) *P<sub>α</sub>* = Σ<sub>*g*</sub> *χ<sub>α</sub>*(_g_)* _ĝ_
projects onto the part of the Hilbert space that transforms according to an irrep _α_, described by the characters *χ<sub>α</sub>* (the sum runs over the elements of the symmetry group).

Compared to this, @chrisrothUT's [recent paper](https://arxiv.org/pdf/2104.05085.pdf) (which I assume #620 is based on) gives the following projection rule:
(2) *ψ<sub>α</sub>*(*σ*) = Σ<sub>*g*</sub> *χ<sub>α</sub>*(_g_)* _ψ_(_gσ_).
These look superficially similar. However, _s_ in the first one acts not on the basis states but the wave vector _ψ_. Since
(3) _ψ_(_sσ_) = ⟨_sσ_|_ψ_⟩ = ⟨_σ_|*s*<sup>–1</sup>|_ψ_⟩,
the two projectors differ by using the character of _s_ vs. *s*<sup>–1</sup>. These are complex conjugates of one another, so equal in many space groups, but it is not necessary.

In general, we will have to be careful (to document) what we mean by a wave function with a given wave vector (for this complex conjugation would be undone by swapping _k_ and _–k_), etc. However, we probably should stick to the proper meaning of the projection operator, (1). This changes (2) to
(2') *ψ<sub>α</sub>*(*σ*) = Σ<sub>*g*</sub> *χ<sub>α</sub>*(_g_) _ψ_(_gσ_).
~so the desirable meaning of the equivariant output becomes (cf. Eq. (5) in the paper)
(4) *ψ<sub>g</sub>*(*σ*) = *ψ*(*gσ*).~

* I think the equivariant layer defined in Eq. (10,13) in the paper is watertight: if its input satisfies either (4) or the version in the paper, the output will, too. (Eq. (11) in the paper doesn't assume anything about the origin of the input features.)
* ~The input layer, defined in Eq. (12), and I suppose implemented in `DenseSymm` needs changing to
(5) *f<sub>g</sub>* = Σ<sub>*x*</sub> *W<sub>gx</sub> σ<sub>x</sub>*:
this works since
Σ<sub>*x*</sub> *W<sub>gx</sub> σ<sub>x</sub>* = Σ<sub>*x*</sub> *W<sub>x</sub> σ<sub>g⁻¹x</sub>* = Σ<sub>*x*</sub> *W<sub>x</sub>* (*gσ*)<sub>*x*</sub> = *F*(*gσ*);
the second equality follows from thinking about what it means to translate/... a spin configuration rather than the point where it's evaluated (similar distinction to that in (3)).~
* ~Likewise, the final layer proposed in Eq. (14), but never implemented beyond the trivial irrep, would turn into (2'): this only requires dropping complex conjugation from the characters.~

~Funnily enough, the two proposed changes cancel each other out: the assignment of *ψ<sub>g</sub>*(*σ*) is arbitrary, so if it is set to *ψ*(*g*<sup>–1</sup>*σ*) in the first layer (as it is done now), that propagates through without problem, and meets a projection rule that also swaps _g_ and *g*<sup>–1</sup>. However, it would be good to get the semantics right.~

EDIT: The covariant implementation (which is available now) is semantically sensible, too:
* setting *ψ<sub>g</sub>*(*σ*) = *ψ*(*g*<sup>–1</sup>*σ*) means that |*ψ<sub>g</sub>*⟩ = *g*|*ψ*⟩ (cf. (3));
* the final layer, as written in Eq. (14) of the paper, is directly consistent with (1).

To be honest, this might be even better, we just have to get everything straight, and make sure that `DenseSymm` does what we think it does.

EDIT 2: In fact, only this implementation makes sense. If we wanted *ψ<sub>g</sub>*(*σ*) = *ψ*(*gσ*), we would need a group conv. layer that is equivariant w.r.t. multiplying from the right, which is not what we have. (It could be adapted, but there is just no good reason for it...) See https://github.com/netket/netket/issues/698#issuecomment-835382734 for details.

## Action items

* Check the discussion above in case I got something wrong (there are many delicate bits...)
* Checking `DenseSymm` for usage of _g_ vs. *g*<sup>–1</sup> – I don't really understand the code, so if someone (@chrisrothUT?) could make sure it implements *f<sub>g</sub>* = Σ<sub>*x*</sub> *W<sub>g⁻¹x</sub> σ<sub>x</sub>* as it is, that'd be great
* Deciding which of the two possible conventions we'd like to use (See https://github.com/netket/netket/issues/698#issuecomment-835382734, we don't have much choice.)
* ~`DenseSymm` should be changed to implement (5). Unfortunately, I don't really understand how the code works, so I need help with this, @chrisrothUT?~
* ~When implementing #658, we should remember to use (2') rather than (2) in the final layer.~ 
* Note to self: I'll think about what the best convention for the wave vector → translation irrep mapping would be in my representation theory notes, which would set the convention for the character-table implementation to be built in #658. (Done in #700)

**Comment by chrisrothUT** [comment]
Yes, I agree this is an issue we need to get sorted, although I don’t think it’s too difficult. It’s just a matter of keeping track of when we’ve done an involution (mapping g->g^{-1}) over the group elements.

The G-convolution is actually an involution (see Eqn. 13 of (this paper)[(http://proceedings.mlr.press/v48/cohenc16.pdf]), as otherwise you have to transform the feature map which is more computationally intensive. You can check the tests and see that DenseEquivariant does indeed produce an involution. I’m not sure if DenseSymm produces an involution, I’ll have to see how it’s implemented. 

In any case, the easiest way to deal with this is just to check how many involutions we’ve done and complex conjugate the eigvals if we’ve done an odd number.

**Comment by attila-i-szabo** [comment]
> The G-convolution is actually an involution (see Eqn. 13 of [this paper](http://proceedings.mlr.press/v48/cohenc16.pdf)), as otherwise you have to transform the feature map which is more computationally intensive. You can check the tests and see that DenseEquivariant does indeed produce an involution. I’m not sure if DenseSymm produces an involution, I’ll have to see how it’s implemented.

This is weird, though. Eq. 11 in your paper shows that the form in (10) (which looks identical to Cohen's Eq. 11) is not an involution, and it does transform the filters W. Am I missing something?

**Comment by attila-i-szabo** [comment]
> In any case, the easiest way to deal with this is just to check how many involutions we’ve done and complex conjugate the eigvals if we’ve done an odd number.

That doesn't sound like something we can easily tack at the end of a network without introspection, though...

**Comment by chrisrothUT** [comment]
Yeah I think this is largely a case of bad notation, I think it would be be better to write:

$$ C_{g^{-1}} = \sum_h {\bf W}_{g^{-1} h} \cdot {\bf f}_h $$

Then it would be easy to see that 

$$ \sum_h {\bf W}_{g^{-1} h} \cdot {\bf f}_{uh} = \sum_h {\bf W}_{g^{-1} u^{-1} h} \cdot {\bf f}_{h} = C_{ {ug}^{-1}} $$

The equation you wrote doesn’t preserve the group structure:

$$ \sum_h {\bf W}_{g h} \cdot {\bf f}_{uh} = \sum_h {\bf W}_{g u^{-1} h} \cdot {\bf f}_{uh} = f_{g u^{-1}} $$

Anyway, I think if there was a way to not do an involution, Cohen and Welling would have figured it out.

**Comment by attila-i-szabo** [comment]
> C_{g^{-1}}` = \sum_h {\bf W}_{g^{-1} h} \cdot {\bf f}_h

I'd say that this is bad notation, unless you really want to get an involution. Since W is implemented as a dense filter, we can assign the outputs in any way we want, and we **should** pick the assignment that doesn't lead to an involution.

PS. Github Markdown doesn't support latex in any form, the starting comment uses MD and HTML syntax

**Comment by attila-i-szabo** [comment]
> The equation you wrote doesn’t preserve the group structure:

Yep, because this is an involution, the C<sub>g</sub> transform according to the times table of the g<sup>–1</sup>

**Comment by chrisrothUT** [comment]
That equation produces an involution. They say it right after + I’ve tested it. I don’t have a good grasp on why it does though.

**Comment by attila-i-szabo** [comment]
> That equation produces an involution

It doesn't, you, I, and they all calculated it and it doesn't.

> They say it right after

They say that the outputs of f * ψ and ψ * f are involutions of one another. If you work out what ψ * f does, it flips the group structure similarly to my spoof involution in https://github.com/netket/netket/issues/698#issuecomment-834850199

> I’ve tested it

What was your test?

**Comment by chrisrothUT** [comment]
> What was your test?

The function test_DenseEquviarant [here](https://github.com/netket/netket/blob/master/Test/Models/test_nn.py). You can see that applying sym_op on the input is transposed on the output. Basically the test you described

> It doesn't, you, I, and they all calculated it and it doesn't.

I don’t agree with this. We’re just giving the output the label “g” but the elements “g” and “h” belong to groups that are involutions of eachother. 

Quote from Cohen “Note that if G is not commutative, neither the G-correlation nor the G-convolution is commutative”. Equation 13 is basically saying that transforming the feature maps doesn’t produce an involution but transforming the weights does.

**Comment by attila-i-szabo** [comment]
> > What was your test?
> 
> The function test_DenseEquviarant [here](https://github.com/netket/netket/blob/master/Test/Models/test_nn.py). You can see that applying sym_op on the input is transposed on the output. Basically the test you described

I can't really follow what this is doing, I guess I'd have to familiarise myself with how the `SymmGroup` class works. 
I'll run some very basic checks tomorrow.

> I don’t agree with this. We’re just giving the output the label “g” but the elements “g” and “h” belong to groups that are involutions of eachother.

I don't think this is a meaningful point. The contents of the group and its "involution" are the same, just with a different times table (the transpose of the original). And Cohen's (12) shows that with this labelling, (10) preserves the original times table, not the transposed one. And that's all you need for equivariance.

> Quote from Cohen “Note that if G is not commutative, neither the G-correlation nor the G-convolution is commutative”. 

Sure, but also irrelevant.

> Equation 13 is basically saying that transforming the feature maps doesn’t produce an involution but transforming the weights does.

The other way around. I'm really not sure what their point is with the whole involution business, after having shown that the mapping they calculate is properly equivariant.

**Comment by attila-i-szabo** [comment]
> I don’t agree with this. We’re just giving the output the label “g” but the elements “g” and “h” belong to groups that are involutions of eachother.

Put it another way: suppose you set it up such that you get an involution (i.e., if the output for *f(g)* is *C(g)*, the output for *f'(g) = f(ug)* is *C'(g) = C(gu<sup>–1</sup>)*), then you can apply an extra kernel that maps *C(g)* to *Q(g) = C(g<sup>–1</sup>)* to get a non-involution. That's simply a relabelling, and choosing the appropriate labelling fuses this extra kernel into *W*

**Comment by chrisrothUT** [comment]
> The problem is that sym_op.transpose(0, 1) doesn't actually transpose the matrix

Thanks for catching that, quite a silly bug.

> DenseSymm embeds the spin configuration in a way that is compatible with a left-equivariant network

I think DenseSymm has to produce a left-equivariant transformation, otherwise the output would not be invariant at all. Whether it produces an involution is another story. 

>  @chrisrothUT, could you write a test for a full GCNN

Right now I still have no computer. If anyone knows a good way to develop remotely that would be very helpful. In any case, hopefully I’ll have one by the end of this week.

**Comment by chrisrothUT** [comment]
Also feel free to disregard all of my arguments above, Atilla was clearly right!

**Comment by attila-i-szabo** [comment]
> I think DenseSymm has to produce a left-equivariant transformation, otherwise the output would not be invariant at all.

It could be that `DenseEquivariant` is right-equivariant and `DenseSymm` also happens to produce the opposite embedding. I checked them separately and they are both left-equivariant, though.

> > @chrisrothUT, could you write a test for a full GCNN
> 
> Right now I still have no computer. If anyone knows a good way to develop remotely that would be very helpful. In any case, hopefully I’ll have one by the end of this week.

That's unfortunate. Also, I noticed there were tests for the full GCNN (sorry for not spotting them earlier!), and you're right, it would have caught mixed equivariance.

> Whether it produces an involution is another story.

I'll die puzzled by that sentence in Cohen et al. They prove that the layer they implement is equivariant, and then they go on to construct this weird object that isn't equivariant and go apologetic about the properly constructed one... I just can't get what confused them so much.
The weirdest thing is that even if they are unfamiliar with group theory, the involution they talk about is not something that happens in a normal CNN context, either...

> Also feel free to disregard all of my arguments above, Atilla was clearly right!

I hope it's not just the bug fix that convinced you :)

**Comment by attila-i-szabo** [comment]
I guess we're mostly done with the questions raised here. The original point (how to hook up a character table with a GCNN) is already treated formally in #700, and we clarified what exactly each part of the GCNN calculates. 

I'll split #700 into two notes and put in a PR to fix the bug in the test. In the same go, I'd remove the sentence in your GCNN tutorial about the involutions as it is wrong and isn't really needed there anyway.
