### ISSUE TITLE
Running with MPI on a SLURM cluster 

### ISSUE THREAD

**Issue by guglami** [netket/netket#699]
Hello! I'm running some simulations on a cluster that uses SLRUM as a job scheduling system. My NetKet Version is 3.0 Beta 1 Post9. In my code, I optimize a custom model defined in the Flax Linen API framework and then I write some data (values of energy etc.) on a .txt file. In order to speed up the computation, I'm trying to use MPI parallelization. For this purpose, I'm setting ntasks>1 in my job script and I'm running with: mpirun python my_programm.py. I realized that every time I run the code, the program produces several .txt files, not one (as expected). I presume that mpi is not working properly. However, if I run mpirun -np 2 python3 -m netket.tools.check_mpi, as recommended here https://www.netket.org/docs/sharp-bits.html#parallelization, I get a reasonable result, for example (by setting ntasks=3 and cpus-per-task=10):

```
mpi_available                : True
mpi4jax_available            : True
avalable_cpus (rank 0)       : 2
n_nodes                      : 2
mpi4py | MPI version         : (3, 1)
mpi4py | MPI library_version : Open MPI v3.1.4, package: Open MPI abuild@ohpc1 Distribution, ident: 3.1.4, repo rev: v3.1.4, Apr 15, 2019
```

As you can see, my openmpi version is 3.1.4 (since there are no more advanced versions available on the cluster). Have you any idea of what is happening?

**Comment by PhilipVinc** [comment]
`check_mpi` reports that your MPI is set up correctly, so I'd expect netket to be running fine.

How are you saving the data in .txt files? 
The way MPI works is that your code is being executed on every node, so if you don't 'hide' your serialization code behind a flag like
```python
import netket as nk
# run your computation

if nk.utils.mpi.rank == 0:
    with open("my file.txt", "w") as f:
         f.write(data)
```
all ranks will be executing the serialization code.

Did you try using NetKet's loggers like `netket.logging.JsonLog` ? Together with `VMC.run(...out=nk.logging.JsonLog("output")) ` ?  This will do this automatically for you.

**Comment by PhilipVinc** [comment]
However... 
Are you sure the output of checkmpi you posted is for `ntask==3` and `ncpus_per_task==10` ? 

What I see there is that you have `2` tasks (n_nodes) with `2` cpus per task (avalable_cpus (rank 0)).

(N_nodes is what is reported by `MPI.Get_Size()` and `available cpus` are the cpus that this MPI process has...)

By the way, I'd suggest setting max 2 cpus per task for optimal performance, not more.

**Comment by guglami** [comment]
Thanks for your help! Indeed, by adding your flag I don't get multiple .txt files, so hopefully MPI is working. 

However, I am not seeing a significant increase in the computation speed. Just as a check, I tried with the Jastrow part of your tutorial code https://www.netket.org/tutorials/Heisenberg1d.html (which apparently you ran in 21.09753 seconds). With the same parameters and by setting --ntasks=3 and --cpus-per-task=2, I get 48 seconds; 
with --ntasks=9 and --cpus-per-task=2, I get 46 seconds; 
with --ntasks=12 and --cpus-per-task=2 I get 39 seconds... 

It seems quite slow, isn't it? 

In reply to your questions: actually I set n_tasks=2 and not 3 as I wrote (my mistake). However, I realized that sometimes 
the number avalable_cpus (rank 0) does not seem to match with the parameter cpus-per-task I set in my SLURM job script. 
Should I specify other options in addition to -np X when using mpirun (like CPUs options)? I set X equal to n_tasks, okay?

**Comment by guglami** [comment]
> If you do this under MPI with 2 nodes you will have ((1000/16) + 100)*16 = 163*16 = 2608 samples.

I don't clearly understand your calculation. When you write (1000/16) + 100, I presume you are writing 16 since (in your example) n_chains*n_nodes=16, isn't it? However, since we are doing parallel computation, why are you multiplying by the same factor (i.e. ((1000/16) + 100)*16)? I thought that, since we have n_chains*n_nodes different Markov chains running in parallel, the time was just proportional to (1000/(n_chains*n_nodes)) + 100) ... 

> Can you tell me in which cases you get a mismatch in the available cpus reported from what you set with mpirun? 

Ok I will check about this...

Just another question: if I want to run my optimization with different values of the hamiltonian parameters, what I need to do? 
What if I just use a for cycle? Are there better ways in the case I'm using parallel computation (MPI)? 

P.S. thank you again!

**Comment by PhilipVinc** [comment]
> I don't clearly understand your calculation. When you write (1000/16) + 100, I presume you are writing 16 since (in your example) n_chains*n_nodes=16, isn't it? However, since we are doing parallel computation, why are you multiplying by the same factor (i.e. ((1000/16) + 100)*16)? I thought that, since we have n_chains*n_nodes different Markov chains running in parallel, the time was just proportional to (1000/(n_chains*n_nodes)) + 100) ...

Yes, but then the cost is 225 vs 163, which is just a 20% improvement.

> Just another question: if I want to run my optimization with different values of the hamiltonian parameters, what I need to do?
What if I just use a for cycle? Are there better ways in the case I'm using parallel computation (MPI)?

Anything is good
