### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#725]
We are now at this stage 
- [x] Variational state interface
- [x] new SR interface based on QGT
- [x] Samplers `n_chains`/`n_chain_per_rank`
- [x] new lattice interface + symmetries

I think we can safely tag the beta 2 `v3.0b2` now, which will contain basically all breaking changes that we are doing to the interface.

Then I think we can have a `v3.0b3` once the new lattice stuff is merged and 1-2 weeks later tag the final 3.0, because while that PR adds many new things, it does not break much API anymore.

I think the user-facing api is now stable. 
Internal APIs like samplers and how to dispatch to the code computing expectation values of different operators are not stable and will be changed (switched to use dispatching). 
I hoped to do it for 3.0 I think it will just come when ready and we would be better release 3.0 once and for all.

Also, I had hoped to switch to the opposite ordering of the spin basis but that requires a rewrite of local operator and I think this will also be something left for the future.

**Comment by femtobit** [comment]
> Internal APIs like samplers and how to dispatch to the code computing expectation values of different operators are not stable and will be changed (switched to use dispatching).

Is it clearly documented somewhere parts are meant to be external API and stable and which aren't? As far as I can tell, it is not always clear from the module structure. At least when you say "internal APIs like samplers" that would probably affect everyone building their own Metropolis rules or similar and the corresponding classes are available from `sampler` or `sampler.rules` just like the main samplers.

I guess this is true for many other modules and submodules as well (e.g., do we consider `netket.utils` internal (not `utils.group`, at the very least)? What about submodules of `utils` or `netket.jax`?

**Comment by PhilipVinc** [comment]
Yeah, I plan on writing it at the top of the API page or somewhere else what exactly we consider stable api and what we don't.

For me, what is stable is the whole `user-facing` API built around of the variational state and the constructors of the various bits and pieces.

Indeed not having a stable `sampler` API might be annoying for some. But there are still some minor issues to be addressed and it makes no sense in keeping an unreleased 3.0 for months until those are addressed.
Regardless, I suspect the changes will be very small, probably just about returning an extra field (`model_state`) from the sampler, and we might even be able to soft-deprecate it.

About `variational.expect` and using dispatch, this stuff is already non-extensible, so changing it's api to make it extensible is a clear win.

About `netket.utils`, `group` and `jax`... again, my take is that netket modules are stable api for everything publicly exported (except otherwise noted).

`netket.utils` is not stable as it's an internal thing, with exceptions.

**Comment by femtobit** [comment]
> netket modules are stable api for everything publicly exported (except otherwise noted).

That reasonable.

Though there is still a bit uncertainty wrt to what "publicly exported" means. at least for me. I can import `netket.nn.linear.*`, but only the things in that file that are re-exported in `netket.nn` are actually meant to be stable. The same pattern is present in other modules. However, while we stick to that kind-of implicit rule often, it is different for, e.g., `netket.operator.spin`, the contents of which are also public.

Maybe we should be more rigorous in naming submodules`_something.py` when they are meant to be internal? (We can do that once before tagging v3.0, no ned to cause merge conflicts earlier.) On the positive side, we don't need to prefix internal variables and imports with `_`s in those files because the public objects are re-exported in the non-internal modules anyways.

**Comment by PhilipVinc** [comment]
what I mean by publicly exported is that it's not hidden behind some `_`. I think this is the traditional Python interpretation of public api.
So kind-of that autocompletion shows it to you.

I don't get your point about importing `*` (which BTW, it's discouraged syntax and should not be used...). Shouldn't it import all visible (aka non leading-underscore) things, so it respects what I stated above?
The example about `.nn` is flawed (see below). While for `operator.spin` everything works as expected?
```
>>> nk.operator.spin.sigma
nk.operator.spin.sigmam( nk.operator.spin.sigmap( nk.operator.spin.sigmax( nk.operator.spin.sigmay( nk.operator.spin.sigmaz(
```
I know that this is a module and explicitly delete symbols from that file in order to clean it up.

>Maybe we should be more rigorous in naming submodules_something.py

I tried very hard to enforce this, though I might have failed somewhere...
That's what `hide_submodules` does for all files by default: hide everything behind an underscore unless specified.
Doesn't do it with Subpackages (aka folders) but at least for now we don't really have those anywhere except in utils.

The two exceptions to my efforts are `utils` and `nn`

`netket.nn` which was supposed to just be a (partial) re-packaging of `flax.linen` (soon to be `flax.nn`) to make it work with complex numbers before we upstream those things. 
Since I literally copy-pasted flax code and they were not as clean as we are there are some issues there...
we should think a bit more about API stability guarantees around `netket.nn`...

**Comment by femtobit** [comment]
Okay, my `nn` example was probably not the best. Let me take a better example: If import
```python
from netket.sampler.rules.exchange import compute_clusters
```
Is this supposed to be stable per the no-underscores rule?

**Comment by PhilipVinc** [comment]
Ah i see.
According to my rule, which is about what is visible, `rules.exchange` is not visible. See what the autocomplete gives you:
```python
>>> netket.sampler.rules.
netket.sampler.rules.CustomRuleNumpy(      netket.sampler.rules.HamiltonianRule(      netket.sampler.rules.LocalRule(
netket.sampler.rules.ExchangeRule(         netket.sampler.rules.HamiltonianRuleNumpy( netket.sampler.rules.LocalRuleNumpy(
>>> netket.sampler.rules._
netket.sampler.rules._custom_numpy      netket.sampler.rules._hamiltonian       netket.sampler.rules._local
netket.sampler.rules._exchange          netket.sampler.rules._hamiltonian_numpy netket.sampler.rules._local_numpy
```

The problem is the way I do the `underscorirzation` can be worked around by importing directly as you did above.

The only actual solutions to it is either properly give `underscores` to basically... all our files.
Or move everything to a `/_src` directory as jax does and create a `fake` netket package importing stuff from `_src` (this is nice because then our public interface is very visible, but it completely breaks history and PRs).

**Comment by PhilipVinc** [comment]
And why this instead of moving everything to `_src` a la jax?

**Comment by femtobit** [comment]
I thought it was a bit simpler that way. But I am fine with either solution.

**Comment by PhilipVinc** [comment]
I think the diff is simpler if we move everything to `_src` and we create a new folder structure and explicitly export things one by one in the `export` files.
Also I personally dislike all those files starting with `_`.

But I'll try to give a proper look.

In any case this will break all PRs regardless so let's wait to merge what's cooking right now before doing it.

**Comment by PhilipVinc** [comment]
Since ~I don't have a life~ I am waiting for a pizza I was reading emlp implementation of groups. Interestingly, they use [this decorator: `@export`(https://github.com/mfinzi/equivariant-MLP/blob/8257ad12c1cd017843fb98a6dd189bcc8af77307/emlp/groups.py#L13), defined [here](https://github.com/mfinzi/olive-oil-ml/blob/47ee56ae01348d2ced0dbc6d105a759f6cfb5a46/oil/utils/utils.py#L23):

```python
def export(fn):
    mod = sys.modules[fn.__module__]
    if hasattr(mod, '__all__'):
        mod.__all__.append(fn.__name__)
    else:
        mod.__all__ = [fn.__name__]
    return fn
```

Which just changes how `__all__` is defined.
As far as I know `__all__` only changes how `from package import *` works so I thought that's kind of useless. 
But it turns out that... according to [PEP8:Public and Internal Interfaces](https://www.python.org/dev/peps/pep-0008/#id50) `__all__` is the ultimate source of truth of what is public and what isn't

**Comment by PhilipVinc** [comment]
I am starting to think that the right thing to do is releasing 3.0 and that's that. 
The amount of deprecations is untenable and I want to get rid of them.

I'm leaning towards documenting what is considered public and what ain't and call it a day.

It makes no sense to wait `feature-completeness` ad infinitum...

**Comment by gcarleo** [comment]
the problem is not too much feature completeness but the fact that we keep changing the APIs...

**Comment by femtobit** [comment]
@PhilipVinc This was more or less the original plan, wasn't it? The last open point from your first post here is to finalize the symmetry/lattice features, which is now (almost) done.

**Comment by PhilipVinc** [comment]
Yes, I just had a gripe moment.
