### ISSUE TITLE
rewrite MPS

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#726]
Our MPS implementation has a quadratic complexity on the number of samples, which leads to crazy high memory requirements.
The reason is because a tensor to be contracted with `N_samples^2 x bond_dim^2` size is built and then reduced, instead of doing a loop over the tensors without storing the intermediate value. 
We should completely rewrite it.

**Comment by meandmytram** [comment]
Hey @PhilipVinc, I'd like to contribute to solving this issue (I have some experience in coding, tensor networks etc), but I've never contributed to any large-scale library, can you bring me a bit up to date with this issue please?

**Comment by PhilipVinc** [comment]
Hi @meandmytram , thanks for chiming in!
There has not been much development on the issue: Our [implementation of MPS](https://github.com/netket/netket/blob/master/netket/models/mps.py) is slow and scales poorly with the number of samples, which is something we don't want because in principle we'd like it to scale linearly with the number of samples.

While in principle it's easy to implement, something better, in practice it is non-trivial because of the way you are supposed to write jax code (no loops, no variable sized arrays...). However, it should still be relatively easy, I believe.
There is also a Google library, [TensorNetworks](https://github.com/google/TensorNetwork/blob/f62cc5269dfc09662ae9ced7325ba8787b0a2c27/tensornetwork/matrixproductstates/mps.py), which implements MPS in jax. Some inspiration might be taken from there too if needed 

If you'd like to work on this, you'd need to write the MPS Model to generate the initial parameters and to compute the log-amplitude given a single spsin configuration. Ideally in Flax or any other Jax framework you like.

**Comment by LionSR** [comment]
This is being addressed in #1745.
