### ISSUE TITLE
Look ups for derivative

### ISSUE THREAD

**Issue by stavros11** [netket/netket#73]
Hello,

Thanks to everyone for developing and releasing this code.

Please excuse my C++ inexperience, I would like  to ask a quick (and possibly simple) question: In the `abstract_machine.hpp`, is there any reason that there is no `DerLog` function that takes look ups as argument, similarly to `LogVal` and `LogValDiff`? I am assuming that it has to do with the way the derivative and the look up update is handled in the VMC part (for which I haven't checked the code), however wouldn't in principle to be possible to use already calculated look ups for more efficient calculation of derivative?

I am implementing some custom machines based on MPS, where all the left and right contractions are required for the full derivative. These contractions can also serve as look ups to assist `LogValDiff` calculations (particularly in the one-flip case). I am wondering whether it is possible to use them directly in `DerLog` without contracting from scratch every time. I tried defining private look up variables within my class for this and update them within `UpdateLookup` but this did not work, I am guessing because `UpdateLookup` is not called before every derivative calculation.

**Comment by gcarleo** [comment]
Hi Stavros, this is an excellent point. 

Indeed we were thinking of adding lookup-based derivatives as well. These might be useful for example also for feed-forward neural networks. The way to go is to add a method to the abstract machine, something like ```DerLogDiff``` taking as an input the lookup table and the visible configuration. In order for this to work, one has to change a little bit how things are implemented in the Variational code (at the moment I think we are not computing derivatives after each sweep, but at the end, once all the sampled visible configurations have been collected. I would be happy to help you with this part, it is an improvement which could speed-up calculations for some families of variational states

**Comment by stavros11** [comment]
Hi Giuseppe, thank you for the response.

Yes, I can see that the gradient is calculated after sampling, so this excludes the use of lookup. I guess one should move the calculation of `Ok_` and `elocs_` vectors in the sweep loop for this to work, assuming that the sampler updates the lookup every time a flip is accepted. Are there any plans to do this in the future? Also changing the abstract machine could complicate things, as every machine should probably be updated then.
I am not how much it would help in terms of speed, at least for the MPS it might already be costly to constantly update the lookup, however since this is done anyway for `LogValDiff`, it could be used in the derivative too.
