### ISSUE TITLE
Duplicate edges and self-loops in `Lattice` with PBC

### ISSUE THREAD

**Issue by femtobit** [netket/netket#743]
The `Lattice` class and, by consequence, the new `Grid` implementation, adds self-loops and duplicate edges when PBC are enabled:

Consider the following cases:
```python
>>> print(Grid([1]).edges())
[(0, 0)]
>>> print(Grid([2, 1]).edges())
[(0, 0), (0, 1), (0, 1), (1, 1)]
>>> print(Grid([3, 2]).edges())
[(0, 2), (0, 4), (0, 1), (0, 1), (1, 3), (1, 5), (2, 3), (2, 3), (2, 4), (3, 5), (4, 5), (4, 5)]
```

While one can argue that the first two cases are ill-formed and should just throw and error, the third case does make sense if not for the fact that additional periodic edges are added along the short direction.

Since PBC along that direction do not make sense, but OTOH it would be tedious to require users to manually specify `pbc=[True, False]` in such as case in my opinion, I think this should just default to assuming `pbc=False` along directions of `extent <= 2` (this would also address the first two problems).

I can make a PR for this, if everyone agrees this is the correct solution.

**Comment by gcarleo** [comment]
thanks @femtobit, I agree those are really wrong... however I am not too comfortable with having the default argument for pbc depend on another argument... I think a good solution is to throw an error if pbc=True in those cases ?

**Comment by femtobit** [comment]
Fair enough, requiring people to explicitly specify PBC for short directions is reasonable.

**Comment by PhilipVinc** [comment]
I think that PBC along a direction of two sites does not make sense, because it's already periodic.

You actually have to be careful because having PBC (in the sense of a double edge) is essentially multiplying by two the bond amplitude, so when you do simulations comparing 2x2, 4x4, 8x8 you actually have to turn off PBC on 2x2 otherwise it does not show the proper scaling.

So I'd be more in favour of changing the PBC depending on the length, as @femtobit had proposed at the beginning.

**Comment by femtobit** [comment]
Yes, thinking about it, it seems clear to me which grids the following graphs correspond to:
```
Grid([2, 2])
Grid([8, 2])
```
but if we throw an error, people would need to create them with
```
Grid([2, 2], pbc=False)
Grid([8, 2], pbc=[True, False])
```
which seems overly verbose. (I am happy with throwing an error for `[8, 1]` or similar, though maybe that should also not be done for consistency with the first cases here.)

**Comment by PhilipVinc** [comment]
I don’t see a reason to throw an error for 8,1...
I think we can either document that pbc is always off for directions where there are less than 3 sites.

or default to false unless explicitly asked for (and error otherwise) if we want to have some extra code.

**Comment by femtobit** [comment]
Okay, for `Grid`-like lattices the case is clear and I'd be happy to just go back to the previous behavior (also for backwards-compatibility).

However, the case is less clear for lattices with multiple sites per unit cell. Take, for example,
```python
nk.graph.Lattice([[1, 0], [0, 3]], extent=[3, 1], site_offsets=[[0, 0], [0, 1], [0, 2]])
```
which just looks like this (so it's just a Square lattice with non-primitive unit cell):
```
| | |
O-O-O-
| | |
O-O-O-
| | |
O-O-O-
```
If we only look at the `extent` (which is 1 along one direction), this would have half-open boundary conditions by default which would be surprising to me.

Maybe just removing multi-edges and loops during `__init__` is fine as an alternative choice? For the grids, this gives the same result as what we've discussed.

**Comment by gcarleo** [comment]
I think that removing duplicate edges is by far the easiest solution... then just add a warning if that happens?

**Comment by femtobit** [comment]
@gcarleo Yes, agreed on removing the edges. Not sure about the warning: It would also apply to `Hypercube(2, 2)`, which should not warn I think. And since `Hypercube` etc. delegate to `Lattice`, its some more work to selectively silence the warning.

**Comment by gcarleo** [comment]
ok as you see... but indeed let's just remove the self edges and duplicated ones because that's certainly a bug we have now!
