### ISSUE TITLE
Make graph.edge a property and not a method

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#750]
I'd also change nodes to be a property, too.

@femtobit Will you open a PR to do this if you have some time?

**Comment by femtobit** [comment]
> Will you open a PR to do this if you have some time?

Yes, I'll do that.

**Comment by PhilipVinc** [comment]
Though on a second thought, maybe we can keep the current interface, and maybe just change how the color kwarg works

**Comment by femtobit** [comment]
I don't know. We are 1) not happy with the current interface and 2) the current interface is different from  NetKet v2, while the proposed change brings us back to the original interface. Seems like a good choice to me.

**Comment by PhilipVinc** [comment]
Ah, for a moment I thought it was a change.
That’s why I thought about not changing it 

Though arguably most people are playing around with one of the development, never released versions, I think...
