### ISSUE TITLE
Unary RBM

### ISSUE THREAD

**Issue by cmendl** [netket/netket#76]
Concerning implementing https://arxiv.org/abs/1810.02352 in NetKet: the authors of the paper provide a detailed derivation (in the appendix) of how to choose the RBM parameters for the unary layer to ensure that only certain states (like |100>, |010>, |001> for the spin-1 example) are allowed (i.e., other states have coefficient 0). However, since the unary layer is fixed anyway, as a "shortcut" one could simply set the coefficient 0 directly (for states different from |100>, |010>, |001>). In other words, why is a RBM representation of the unary layer required in the first place?

**Comment by gcarleo** [comment]
Hi Christian, I just see this unary representation as an alternative to the
MultiVal representation currently used for larger spins. It's just a maybe
more rubust way to encode larger local Hilbert spaces in a binary rbm...
Then I agree that it is not essential to set the weights for unphysical
states, since those are never sampled...

**Comment by cmendl** [comment]
OK, thanks, this makes sense...

**Comment by cmendl** [comment]
The main difference compared to NetKet's RbmMultival class seems to be that the "unary representation" would encode a state like |100...> as |up,down,down,...> (i.e., |1, -1, -1,...>); does this sound reasonable?

**Comment by gcarleo** [comment]
I thought that if you have one spin +1 this is encoded as |+1>=|001>, |0>=|010>, |-1>=|100> or something along those lines... so basically the number of visible units you need in the RBM is the local size of the hilbert space time the total number of original spins. Basically this is a [one-hot encoding](https://en.wikipedia.org/wiki/One-hot), as far as I understand

**Comment by cmendl** [comment]
Yes, that's what I also thought. It just seems that MultiVal likewise performs such a one-hot encoding, see ComputeVtilde(); accordingly, the internal "vtilde" vector has length nv_ * ls_ ...

**Comment by gcarleo** [comment]
Oh.... I see. I am really sorry, I completely forgot that I used already this encoding there. I thought I was using a binary encoding actually... So this means that RbmMultiVal should already give the exact result for the AKLT model.

**Comment by cmendl** [comment]
OK, thanks for the clarification; then I'll try to get RbmMultival actually working for the AKLT model...

**Comment by cmendl** [comment]
Here's a short update concerning the AKLT model: it still doesn't seem straightforward to get RbmMultival working for the AKLT model (see code below). After running NetKet for about an hour on my laptop, the last line of the log file reads `{"Acceptance":[0.38572727272727275],"Energy":{"Mean":0.20547643289018816,"Sigma":0.012284238626357113,"Taucorr":0.08831164246365386},"EnergyVariance":{"Mean":0.21198436856893774,"Sigma":0.06058738451198915,"Taucorr":0.29529103488172714},"Iteration":3999}` , i.e., it doesn't reach the ground state energy zero. For comparison, running ED with the same Hamiltonian yields the expected zero energy after a few seconds. Am I missing something here? Any suggestions how to modify the configuration file? Thanks!

```
from __future__ import print_function
import json
import numpy as np

# Exact ground state energy of AKLT model is zero

sigmaz     = [[1, 0, 0], [0, 0, 0], [0, 0, -1]]
sigmaplus  = [[0, np.sqrt(2), 0], [0, 0, np.sqrt(2)], [0, 0, 0]]
sigmaminus = [[0, 0, 0], [np.sqrt(2), 0, 0], [0, np.sqrt(2), 0]]

heisenberg = np.kron(sigmaz, sigmaz) + \
             0.5*np.kron(sigmaplus, sigmaminus) + \
             0.5*np.kron(sigmaminus, sigmaplus)

# System size
L = 10

pars = {}
pars['Graph'] = {
    'Name': 'Hypercube',
    'L': L,
    'Dimension': 1,
    'Pbc': True,
}

# Setting up the Hilbert space
pars['Hilbert'] = {
    'S': 1,
    'Nspins': L,
    'TotalSz': 0,
    'Name': "Spin",
}

# defining a custom bond hamiltonian
pars['Hamiltonian'] = {
    'Name': 'Graph',
    'BondOps': [(0.5*heisenberg + np.dot(heisenberg, heisenberg)/6. + \
                 np.identity(9)/3.).tolist()]
}

# defining the wave function
pars['Machine'] = {
    'Name': 'RbmMultival',
    'Alpha': 4,
}

# defining the sampler
pars['Sampler'] = {
    'Name': 'MetropolisHamiltonian',
}

# defining the Optimizer
# here we use AdaMax
pars['Optimizer'] = {
    'Name': 'AdaMax',
}

# defining the GroundState method
# here we use the Stochastic Reconfiguration Method
pars['GroundState'] = {
    'Method': 'Sr',
    'Nsamples': 1.0e3,
    'NiterOpt': 4000,
    'Diagshift': 5.0e-3,
    'UseIterative': False,
    'OutputFile': 'test',
}

json_file = "AKLT.json"
with open(json_file, 'w') as outfile:
    json.dump(pars, outfile)

print("\nGenerated Json input file: ", json_file)
print("\nNow you have two options to run NetKet: ")
print("\n1) Serial mode: netket " + json_file)
print("\n2) Parallel mode: mpirun -n N_proc netket " + json_file)
```

**Comment by cmendl** [comment]
@lazerjet I'm currently still working on that (see also issue #140). Maybe a good starting point is a "pen and paper" RBM representation of the AKLT ground state. So far I've explicitly represented the singlet bonds of the AKLT ground state using a RBM. (BTW the conventions in  https://arxiv.org/abs/1810.02352 seem somewhat unconventional...) The next step would then be a mapping of pairs of spin 1/2 to the physical spin-1, i.e., the projection in Fig. 4b in the paper, but I'm not sure how to achieve that using a single RBM...

**Comment by cmendl** [comment]
In a recent discussion, Jan Budich provided an explanation why the RBM Ansatz cannot easily represent the AKLT ground state, namely due to its hidden (string) long-range order (i.e., a spin +1 followed by an arbitrary number of spin 0s can only be followed by a spin -1). This long-range order is hard/impossible to capture by the RBM Ansatz, since one would need to couple all pairs of distant sites via the hidden parameters. Now of course the question is why https://arxiv.org/abs/1810.02352 seems to claim the opposite... My explanation is that the authors devise a way how to mimic the valence-bond singlets of the AKLT groundstate construction using the RBM machinery, but then "manually" project pairs of spin-1/2 into the local spin-1 space (Fig. 4b in the paper). In my opinion, while this projection could be achieved via hidden units, it would require an additional layer, in other words a deep Boltzmann machine...

**Comment by gcarleo** [comment]
They have done numerical experiments on the AKLT in  https://journals.aps.org/prx/pdf/10.1103/PhysRevX.8.011006, and I believe they converged to the exact state, maybe with more parameters than their string bond state, but it should work... 
We can ask maybe ask further details to Ivan or @stavros11

**Comment by cmendl** [comment]
In the paper the authors use the modified RBM version in Eq. (27) according to Fig. 4... Also note that the system size is relatively small (8 spins). So maybe a standard RBM with a large number of hidden units would work, too?
