### ISSUE TITLE
nk.nn.logcosh() always returns 0 when the argument is a purely imaginary number

### ISSUE THREAD

**Issue by Cai-Fangxu** [netket/netket#768]
There's a little bug in nk.nn.logcosh(): when its argument is a purely imaginary number, it would always return 0.
```python
import netket as nk
import jax.numpy as jnp

print(nk.nn.logcosh(0.1j))
print(jnp.log(jnp.cosh(0.1j)))
```
```
0j
(-0.005008355623235254+0j)
```

**Comment by femtobit** [comment]
Good catch, thanks.

This seems to happen because `jnp.sign(0) == 0` in
https://github.com/netket/netket/blob/3bdf4ffc823353005744ff8026140cc98052b9d9/netket/nn/activation.py#L90

**Comment by PhilipVinc** [comment]
The code of `logcosh` is 
```
def logcosh(x):
    x = x * jnp.sign(x.real)
    return x + jnp.log(1.0 + jnp.exp(-2.0 * x)) - jnp.log(2.0)
```

which i have taken from the old netket without much thinking about it.

This formula is wrong. 
One should get rid of the jnp.sign(x.real), i think.

**Comment by PhilipVinc** [comment]
So the derivation is as follows:
```python
log(cosh(x) = log( (e^x + e^(-x)) / 2) =  log(e^x + e^(-x)) - log(2)
```

Now we need to numerically stabilize the `logsumexp` or `log(e^x + e^(-x))` into a more stable form.
The correct way to do this is to check the sign of the real part of x.

So if `x.real >0` we should compute it as
```python
-x + log(1 + exp(2x))
```

else if `x.real <0` we should use
```python
x + log(1 + exp(-2x))
```

**Comment by PhilipVinc** [comment]
we could change the call `jnp.sign(x.real)` to `(x.real >= 0)`

**Comment by PhilipVinc** [comment]
Also, `log(1 + x)` should become `jnp.log1p(jnp.exp(...))`
