### ISSUE TITLE
In the documentation website, sr=sr is missing in nk.VMC()

### ISSUE THREAD

**Issue by Cai-Fangxu** [netket/netket#774]
Hi, this issue is about the documentation website. In [https://www.netket.org/docs/sr.html#using-stochastic-reconfiguration](https://www.netket.org/docs/sr.html#using-stochastic-reconfiguration) and in the tutorials, codes like:
```python
gs = nk.VMC(hamiltonian, optimizer, variational_state=vstate, preconditioner=sr)
```
are actually not using SR. One has to use
```python
gs = nk.VMC(hamiltonian, optimizer, variational_state=vstate, preconditioner=sr, sr=sr)
```
to work with SR.

**Comment by PhilipVinc** [comment]
No, we essentially renamed the sr keyword argument to preconditioner in the last beta release.

what version of netket are you using?

**Comment by Cai-Fangxu** [comment]
I see, thanks. I'm using 3.0b1.post9, I'll update it.
