### ISSUE TITLE
Docstring for ```sampler.is_exact``` is not... exact 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#776]
[This docstring](https://github.com/netket/netket/blob/ad832f07470dc30bd299ec2ee833860f62b1c63d/netket/sampler/base.py#L151) is a bit ambiguous: it says 

> The sampler is exact if the samples are always distributed according to the        chosen power of the variational state. 

However I would argue that the sampler is exact if all the samples are exactly distributed according to the chosen power of the variational state and (also, crucially) **there is no correlation among them**

**Comment by wdphy16** [comment]
Ok, let me change this
