### ISSUE TITLE
Loggers names

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#814]
The names of the loggers are somehow redundant/ not so clear 
I would propose the following changes 

```nk.logging.RuntimeLog``` ->  ```nk.logging.Runtime```
```nk.logging.TBLog``` -> ```nk.logging.TensorBoard```

etc

**Comment by PhilipVinc** [comment]
JsonLog -> json?

we should also rename the output (it should be `.json` instead of `.log`)

**Comment by femtobit** [comment]
Stripping the `Log` part makes it maybe a bit confusing. If you do `from netket.logging import Runtime, Json` then you have some very generically named objects in scope. `RuntimeLog` and `JsonLog` are clearer.

I'd definitely prefer names like `TensorBoardLog` to `TBLog` though.
