### ISSUE TITLE
Jaxlib 0.1.69 doesn't recognize GPU

### ISSUE THREAD

**Issue by chrisrothUT** [netket/netket#825]
When I install the newest version of Netket, Jax fails to recognize the GPU. I think the error is related to the newest version of Jaxlib because the software works fine when I downgrade Jaxlib to version 0.1.66.

`pip install --upgrade jax jaxlib==0.1.66+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html`

**Comment by PhilipVinc** [comment]
I would be surprised if the latest release of jax, which was released 8 days ago, had such an evident bug and nobody noticed.

More likely, I bumped the minimum jaxlib to be sure that a fix to `log cosh` is shipped to netket users, and pip updates using the pypi wheels which do not support CUDA. You must install manually the CUDA wheels for the latest jaxlib version.

```
pip install --upgrade jax jaxlib==0.1.69+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

If this is really a bug, please nag jax developers! Open an issue on their repository (with a little bit more information, maybe). They can't know about problems unless you bring it to their attention.
