### ISSUE TITLE
Why does each graph store an adjacency list?

### ISSUE THREAD

**Issue by twesterhout** [netket/netket#84]
Looking at current master, the only meaningful use case for the adjacency list is DFS. DFS is in turn only used during initialisation, and seeing as it's O(N), it's no big deal to create a temporary adjacency list. That way creation of an adjacency list becomes an internal thing we can test and trust; we don't have to accept it as an argument which simplifies the interface (i.e. no more choosing between `edges` and `adjacency_list`) as well as the code. All of that without touching the hot path.

**Comment by gcarleo** [comment]
Can I close this?
