### ISSUE TITLE
Docs for sigma operators

### ISSUE THREAD

**Issue by mmezic** [netket/netket#845]
The documentation of the ladder operator `netket.operator.spin.sigmap` says `σ^+ = σ^x + i σ^y`, but in fact it is defined as `σ^+ = 1/2(σ^x + i σ^y)` in the code.

The same error is in the documentation of `netket.operator.spin.sigmam` operator.

**Comment by femtobit** [comment]
@mmezic Thanks for spotting this, you are right. This is also confirmed by the tests:
https://github.com/netket/netket/blob/00d4607806885f0320ab6ddead9bf497aea268c5/test/operator/test_spin.py#L24-L27

The docs should be fixed.
