### ISSUE TITLE
Show the changelog rendered on the website? 

### ISSUE THREAD

**Issue by gcarleo** [netket/netket#858]
I think at the moment it is visible only browsing the repository on github

**Comment by PhilipVinc** [comment]
https://www.netket.org/docs/changelog.html

**Comment by PhilipVinc** [comment]
or do you want to move it?

**Comment by gcarleo** [comment]
oh I see, it's not particularly visible there but ok at the moment I don't know what a better position might be (maybe a separate entry in the menu on the top might be too much

**Comment by PhilipVinc** [comment]
I think it's not relevant enough to put it at the top...

I copied jax when i put it there: https://jax.readthedocs.io/en/latest/changelog.html

**Comment by gcarleo** [comment]
yes indeed at the top it's too much, it's ok to leave it there then I guess...
