### ISSUE TITLE
Add standard typedefs for matrices and vectors

### ISSUE THREAD

**Issue by femtobit** [netket/netket#86]
Suggestion for discussion:

There are many places in the codebase where we use typedefs such as `using Vector = Eigen::VectorXcd` or `using Matrix = Eigen::MatrixXcd` which I think is somewhat redundant and can be a bit tedious.

I suggest adding a couple of standard typedefs to `netket.hpp` or a custom header file, such as (current names are just for illustration)
```
using NkVector = Eigen::VectorXcd;
using NkMatrix = Eigen::MatrixXcd;

// if needed:
using NkRealMatrix = ...
using NkRealVector = ...
```
It could also be convenient to have a shorthand for `std::complex<double>`.

Of course, there might be legitimate cases where something else should be used (e.g., fixed-size Eigen vectors for performance reasons), but I think we do not loose much by using the types above by default and declaring them globally and only adding template parameters or different typedefs if they are really needed. (Compare the [YAGNI principle](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it)).

This could also help reduce the amount of template parameters we have which are only ever instantiated with one type.

**Comment by twesterhout** [comment]
@femtobit good point! I'd say something like this
```cpp
namespace netket {
    using Eigen::VectorXcd;
    using Eigen::MatrixXcd;
    ...
} // namespace netket
```
should do the trick, no need to invent new names.
The question where to put them is a more interesting one. Perhaps it's time we created a light-weight `NetKet/config.hpp` and put these typedefs there... I'm somewhat concerned about putting an `#include <Eigen/Core>` into a "config" file, but well, that's life ;)
