### ISSUE TITLE
Is Windows supported?

### ISSUE THREAD

**Issue by twesterhout** [netket/netket#88]
I noticed a few Windows specific code paths in `setup.py`. Is building under Windows supported and tested? Or is this code just noise from copy-pasting?

**Comment by gcarleo** [comment]
Copy pasted from the pybind11 repo. No windows support, but in principle it
should work there. You can just remove the offending parts

**Comment by twesterhout** [comment]
@gcarleo thanks! I just really need support for passing arguments to cmake (e.g. *tons* of C++ compilers on my system). So I decided to play around with it, or someone already working on it?

**Comment by gcarleo** [comment]
No, it's good. Please try to figure out also how to enforce memory leaks
checks, using the sanitizer. I didn't configure the debug mode yet in the
python install... I'm not sure how to do that

**Comment by VolodyaCO** [comment]
Is windows supported now? I think this boils down to JAX support on windows, right?
