### ISSUE TITLE
QGTJacobian(mode="real")

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#883]
I think that `mode=real/complex/holomorphic` only needs to take on two values, `holomorphic` or not.
Because in the code we never check for anything other than `holomorphic`.

So we could change this to only be `real` and `holomoprhic`.
Where `real` will split all parts.

Do you agree @attila-i-szabo ?

**Comment by attila-i-szabo** [comment]
We do distinguish `real/complex` [here](https://github.com/netket/netket/blob/b3966e4596fcc341f886a1fef213b0a211103fc5/netket/optimizer/qgt/qgt_jacobian_pytree_logic.py#L223).

It would be possible to eliminate this by looking at the output dtype. The reason I am against that is that you can have ansätze for real but not all positive wave functions. Then, Im log ψ is either 0 or π so it never yields a gradient, but you'd still waste a lot of memory on storing it. 

I don't think it hurts to have this option, and the `auto` mode already has the dtype-based choice.

**Comment by PhilipVinc** [comment]
Yes indeed you are right.
Sorry,  imissed that part of the code
