### ISSUE TITLE
space_group_irreps should accept a vararg

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#898]
space_group_irreps takes an iterable input as argument. It would be nicer if it could accept a vararg so that we can do

`space_group_irreps(pi)` instead of `space_group_irreps([pi])` and `space_group_irreps(pi,0)` instead of `space_group_irreps([pi,0])`

**Comment by attila-i-szabo** [comment]
Isn't this just putting a `*` on [this line](https://github.com/netket/netket/blob/89f9a47b11df05f7c3a0a6bb97a8b71c098fc1b0/netket/graph/space_group.py#L229)? However, if we do that, there are a couple of other things with a similar calling sequence, so we should eb consistent.

**Comment by PhilipVinc** [comment]
basically yes. 
Maybe we'd also have to convert the resulting tuple to a np.array but i don't remember anymore.

**Comment by attila-i-szabo** [comment]
I think `np.tensordot` takes care of that at the start of the function. I'll PR this in a sec.
