### ISSUE TITLE
Make eigen as a submodule

### ISSUE THREAD

**Issue by Roger-luo** [netket/netket#9]
Just had a brief look at your repo. It would be better to make eigen as an git submodule. And write a CMake file to download/load this as dependency. This will make your repository cleaner. About how to use a git submodule: https://git-scm.com/docs/git-submodule

There is a mirror for eigen3 on github: https://github.com/eigenteam/eigen-git-mirror

IMHO, a standard modern C++ library should use [CMake](https://cmake.org/) rather than Makefile. 

Furthermore, since this will be a some kind of python library. I would suggest to use [xtensor](https://github.com/QuantStack/xtensor) with self defined operators instead,. For quantum many-body system, I believe the use of high dimensional array (like numpy's strided array) is quite often. Eigen does not have a mature support for this at the moment.

**Comment by gcarleo** [comment]
I was looking into using submodules before releasing. 
One potential issue is that here we are interested only in Eigen headers, and not the full Eigen repository, which contains much more. 

If you know of a simple way to add it as a submodule but then just taking the Eigen/ folder, that would be helpful. 

Concerning Makefile, vs CMake : building NetKet is purposely meant to be as simple as possible. The Makefile is actually not even needed, it's just a few lines. 

We should decide what strategy is the best. There is also this discussion #8 which is related. 

xtensors seems an interesting project. The reason I chose Eigen is that it has all the BLAS/Lapack linear algebra built-in and more. Also, they have a tensor module, even though at the moment this is not used/needed in NetKet.

**Comment by Roger-luo** [comment]
You can always use only headers, if you make it as an submodule. And then you can easily track the up stream. Just simply follow the instructions in documents and you can create a submodule with only one line. Cmake is not about make this complex, but is about make this stable. Cmake offer you a stable way to load dependencies and tests , etc. I also notice that netket is lack of unit tests. There's no test coverage information and contiguous integration enabled. These tools and rules will help you manage a open-source project.

Less code means less stability and less compatibility. There's no silver bullet.

**Comment by gcarleo** [comment]
As far as I understand there is no clean way to get only the headers of a repository, using sudmodules. Please provide an example if you managed to do that in a clean way (see also this discussion https://stackoverflow.com/questions/3866733/how-to-clone-only-a-folder-from-a-git-submodule) . 

Unit tests have not been pushed yet to the repo, I am still working on those. They will be added as soon as possible.

**Comment by Roger-luo** [comment]
Is there any release version of header only eigen? If there's not I believe you should use the entire package as dependencies. Or if you insist on a header only library, you can maintain a custom fork of Eigen. But including it in the repo is definitely not clean.

**Comment by gcarleo** [comment]
@Roger-luo , in the branch "AllObjects" I implemented a CMake setup. You might want to have a look and comment.

**Comment by Roger-luo** [comment]
Looks nice. But be careful if you have openmp support, there are some workarounds for different platforms. There are some other work around you might need. This would be a good example

https://github.com/pytorch/pytorch/blob/master/aten/CMakeLists.txt#L160

But I think we can discuss this after there is unit tests for netket.

**Comment by gcarleo** [comment]
I am closing this issue at the moment, since I haven't found a clean strategy to include external libraries using submodules. Indeed it seems that many other projects have some folder in the repo with external libraries,
