### ISSUE TITLE
OverflowError when using random_state with Fock space

### ISSUE THREAD

**Issue by femtobit** [netket/netket#917]
This produces an `OverflowError` on my system:
```python
import netket as nk

hi = nk.hilbert.Fock(N=1)
print(hi) # Fock(n_max=INT_MAX, N=1)

rng = nk.jax.PRNGSeq(0)
hi.random_state(next(seq))
```
```
OverflowError: Python int 9223372036854775808 too large to convert to int64
```

Note that `9223372036854775808` is `hi.n_max + 1` so it appears to be an off-by-one error somewhere.

**Comment by PhilipVinc** [comment]
I was trying to fix this but then I realised that this does not play well with our samplers: we need to have integer samples otherwise this will break down...

**Comment by PhilipVinc** [comment]
as well as integer hi.random_state
