### ISSUE TITLE
Reimplement efficient local operator matmul

### ISSUE THREAD

**Issue by PhilipVinc** [netket/netket#950]
Back in the C++ days we had an efficient implementation of localoperator@vector.
Then we lost it in the move to python.
It would be nice if someone would implement this more efficiently-

The relevant code should go here

https://github.com/netket/netket/blob/8fae8babb67ab487fe79c526d6aeff6866ea3cbb/netket/operator/_discrete_operator.py#L245

and an override for LocalOpeartor in https://github.com/netket/netket/blob/8fae8babb67ab487fe79c526d6aeff6866ea3cbb/netket/operator/_local_operator.py

**Comment by gcarleo** [comment]
sorry why is the current implementation inefficient? if you convert local operators to sparse matrices and then multiply by a vector, that is essentially optimal already I would argue

**Comment by PhilipVinc** [comment]
Ah, i flipped them around, i thuoght we do `dense->sparse` but we do `sparse->dense`, indeed...
