### ISSUE TITLE
Broken link in readme (installation)

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#996]
The installation paragraphs show a link which is old, I guess, and there's a 404 error shown. The link in the readme is https://www.netket.org/website/get_started.html

I can solve this in a couple of hours when I go to my personal computer @PhilipVinc

**Comment by PhilipVinc** [comment]
https://www.netket.org/getting_started.html

**Comment by VolodyaCO** [comment]
Is that link preferred to https://www.netket.org/docs/getting_started.html?

**Comment by PhilipVinc** [comment]
I am not opinionated, but the one i linked is more terse.
Can you open a PR?
