### ISSUE TITLE
Initialisers behave strangely in RBMs

### ISSUE THREAD

**Issue by VolodyaCO** [netket/netket#999]
I'm playing around with some symmetrised versions of the RBM and noticed that if I initialise the biases with the `default_kernel_init = normal(stddev=0.01)` initialiser:

```python
...
    kernel_init: NNInitFunc = default_kernel_init
    """Initializer for the Dense layer matrix."""
    hidden_bias_init: NNInitFunc = default_kernel_init
    """Initializer for the hidden bias."""
    visible_bias_init: NNInitFunc = default_kernel_init
    """Initializer for the visible bias."""
```
I get results that get stuck at an energy which are not correct (red).  However, if instead of `default_kernel_init` I use `normal(stddev=0.01)` I get the correct results(green): 
<img width="424" alt="Screenshot 2021-11-26 at 11 59 32 AM" src="https://user-images.githubusercontent.com/31494271/143612756-317e18d1-9600-414f-9bd8-f94e39492ce8.png">

Is there any reason for this behaviour? Seems quite strange! Also in the implementation of RBMSymm you have `normal()` instead of the default thing, which is, I think, why there are no weird behaviours as the ones I see.

**Comment by PhilipVinc** [comment]
Do you have a reproducer? 
Also, are you saying that if you use `normal(stddev=0.01)` instead of the default one (which should be equivalent) you get different results?

**Comment by VolodyaCO** [comment]
Yeah, just by changing that. The example is kind of long, though. Can I send it to you by a Slack message?

**Comment by PhilipVinc** [comment]
ys

**Comment by VolodyaCO** [comment]
As pointed out by @PhilipVinc in Slack messages, the problem was that I was using the `default_kernel_init=normal(stddev=0.01)` and in other experiments I was using `normal(stddev=0.1)`. After some further experimentation I noticed that if I always use `normal(stddev=0.1)`, I get the best results. This might be relevant to #863.

For the record, here I show the energy curves of my problem:


<img width="390" alt="Screenshot 2021-11-29 at 7 39 46 AM" src="https://user-images.githubusercontent.com/31494271/143869721-2a2bbe20-f761-4003-a6fd-3008950bfe67.png">
